### ISSUE TITLE
Expose parameter for tuning EBS throughput

### ISSUE THREAD

**Issue by ysawa0** [buildkite/elastic-ci-stack-for-aws#1026]
**Is your feature request related to a problem? Please describe.**
gp3 EBS volumes have a throughput parameter that can be configured. Currently this is not exposed in the elastic stack
When this is not set, it uses a default thruput 125MB/s which may not be sufficient for some heavy workloads.

**Describe the solution you'd like**
Add a new throughput parameter that is configurable when using gp3 EBS

**Comment by moskyb** [comment]
This is a good idea. We'll add it it our backlog, and when progress is made, i'll update here :)

**Comment by tinder-jlee** [comment]
any update on this? we'd like to have some more option to tune that up.
also i believe this is not at all a difficult update -- probably a few of lines of changes in the CF stack template.
simply we don't want to fork the template, resulting in a drifted version of it.
