### ISSUE TITLE
Customise EC2 instance name

### ISSUE THREAD

**Issue by ChrisLane** [buildkite/elastic-ci-stack-for-aws#1028]
**Is your feature request related to a problem? Please describe.**
I have several buildkite nodes representing several different queues but all of them are named "buildkite-agent" on the AWS EC2 page, this makes it hard to distinguish between them at a glance.

**Describe the solution you'd like**
I would like to be able to customise the EC2 instance name to something other than "buildkite-agent".

**Describe alternatives you've considered**
I am able to filter based on resource tags but that's more effort than having a more unique instance name.

**Additional context**
This seems to have been suggested in the past https://github.com/buildkite/elastic-ci-stack-for-aws/pull/237#issuecomment-273953273
I couldn't find any current solutions.

**Comment by moskyb** [comment]
kia ora @ChrisLane! i feel your pain on this one, we have a good couple of stacks in our account and it's difficult and annoying to find the one you want sometimes.

We've been talking about this internally, and what we'd ideally like to do is just add the stack name to the instance name - ie `buildkite-agent-my-cool-elastic-stack-name-goes-here`. Unfortunately though, the past shackles us, and that's probably a pretty breaking change - other people could be monitoring all the instances called `buildkite-agent`, for instance.

A happy middle ground would be to add a param to customise the instance name per stack, which we can do without too much trouble. We'll put this on our backlog and get to it at some point, hopefully soon.
