### ISSUE TITLE
Customise agent scaler ExecutionRole

### ISSUE THREAD

**Issue by ChrisLane** [buildkite/elastic-ci-stack-for-aws#1029]
**Is your feature request related to a problem? Please describe.**
Due to [limitations in the agent scaler](https://github.com/buildkite/buildkite-agent-scaler/issues/65) my stack cannot automatically scale when using secrets manager for buildkite agent token storage without manual intervention (update policies manually.

**Describe the solution you'd like**
I would like to specify a role to be used as the agent scaler execution role (so that I can create my own role that includes missing secrets manager permissions)
OR
I would like to be able to customise what managed policies are attached to the execution role similar to what is done for the instance role (so that I can attach my own policies to the generated role)

**Describe alternatives you've considered**
I've attempted to programmatically update the role in my CDK stack however since the role name cloudformation output doesn't have a name and the role name contains random characters, I've been unable to do so.

**Additional context**

**Comment by moskyb** [comment]
see [this related issue](https://github.com/buildkite/buildkite-agent-scaler/issues/65#issuecomment-1169545616).

**Comment by ChrisLane** [comment]
I _think_ this can now be done with the `ScalerManagedPolicyARNs` parameter. Not tested yet.
