### ISSUE TITLE
Can't access aws-stack.yml for v5.10.0

### ISSUE THREAD

**Issue by emilio-notable** [buildkite/elastic-ci-stack-for-aws#1037]
**Describe the bug**
When i try to access the aws-stack.yml for the [release v5.10.0](https://github.com/buildkite/elastic-ci-stack-for-aws/releases/tag/v5.10.0)  (https://s3.amazonaws.com/buildkite-aws-stack/v5.10.0/aws-stack.yml), I'm getting an `Access Denied ` S3 error

**Steps To Reproduce**
1. Go to https://s3.amazonaws.com/buildkite-aws-stack/v5.10.0/aws-stack.yml

**Expected behavior**
shows the right yml to be able to update the cloud formation stack

**Actual behaviour**
get an Access Denied error

**Comment by nicwise** [comment]
@pda yes, this :)

**Comment by moskyb** [comment]
heya! this should be fixed now, there was a minor snafu on our end that went unnoticed. many apologies!

**Comment by emilio-notable** [comment]
thanks @moskyb ! seems to be working correctly now
