### ISSUE TITLE
Suggestion for smoother autoscaling

### ISSUE THREAD

**Issue by mtibben** [buildkite/elastic-ci-stack-for-aws#107]
The current rules seem to give a hard scale up to max, and a hard scale down to min when idle. This might fit a typical workday in one office, but because we have a few developers in different timezones using the elastic stack, this doesn't really fit because we have a lot of unused resources when this hard scale up occurs in the middle of the night. I'd prefer a more reactive stack that could scale to fit the demand at the time.

Typically the way I've used autoscaling is to peg average CPU utilisation, adding instances at 60%, and removing instances at 40%. Agents are a little different as we've literally got a queue being processed, which means our stack stats are very spiky. Builds that come in spawn multiple jobs, so the `RunningJobsCount` and `UnfinishedJobs` bounces around quite a bit. 

So the metric I _think_ will give us better results would be a "agents busy" percentage averaged over 5 minutes or so. Then we could trigger a more gentle scale up maybe at 70%, and a gentle scale down at maybe 20%. Hopefully that would give the elastic stack room to bounce around between 20-70%, but will nudge the cluster size in the right direction once utilisation increases or decreases past those points. And we would keep the existing scale up trigger if the `ScheduledJobsCount` rises above 0 to make sure we scale in the first place and on demand.

Thoughts @toolmantim @lox ?

**Comment by toolmantim** [comment]
How hard/soft the scales are is configurable though yes? I find it hard to find a good number with a mix of pipelines when some need a large number of agents per build, and others need less.

So that's one other thing to consider.

There's also stepped scaling as well? Which could do much more context-sensitive scaling depending on the queue size. But nothing's been yet done to spike that.

**Comment by toolmantim** [comment]
Relates to #93

**Comment by lox** [comment]
Is this addressed by https://github.com/buildkite/elastic-ci-stack-for-aws/pull/151?

**Comment by lox** [comment]
Ignore that, I don't think it is. How has this played out over time @mtibben?

**Comment by mtibben** [comment]
The current auto-scaling rules are wasteful for our use-case. I haven't put any time into trying to resolve this recently. This chart is total agents vs busy agents over the course of day

![screen shot 2016-11-11 at 1 58 40 pm](https://cloud.githubusercontent.com/assets/980499/20202914/330ad81a-a817-11e6-80c6-e6cb0a1f6be1.png)

**Comment by toolmantim** [comment]
@mtibben have you tried out the latest master? It's changed the rules since this issue was opened, and I think it might be better for you now.

**Comment by lox** [comment]
I'm going to close this, @mtibben let us know if the recent versions released don't fix this for you.
