### ISSUE TITLE
bashrc does not update after bootstrap script completes running

### ISSUE THREAD

**Issue by GZLiew** [buildkite/elastic-ci-stack-for-aws#1076]
**Describe the bug**
We have a written a bootstrap script that updates the bashrc in the ec2 instance
the tool we are trying to install is asdf https://asdf-vm.com/guide/getting-started.html#_3-install-asdf

**Steps To Reproduce**
1. Create a elastic ci stack 
2. Add a bootstrap script to install asdf
3. deploy the stack
5. run buildkite pipeline

**Expected behavior**
asdf command should be defined.

**Actual behaviour**
asdf command not found. the bashrc script should be sourced again

**Stack parameters (please complete the following information):**
 - AWS Region: [e.g. us-east-1]
 - Version [e.g. v5.6.1]

**Comment by DrJosh9000** [comment]
Hi @GZLiew, thanks for raising the issue. I can imagine a couple of ways this could be going wrong for you. For instance, [.bashrc files aren't sourced in some cases](https://www.gnu.org/savannah-checkouts/gnu/bash/manual/bash.html#Bash-Startup-Files), such as may be used by the agent daemon.

Is it possible for you to source your .bashrc inside a [hook](https://buildkite.com/docs/agent/v3/hooks), e.g. a command hook?
