### ISSUE TITLE
Termination policy

### ISSUE THREAD

**Issue by mtibben** [buildkite/elastic-ci-stack-for-aws#108]
The [termination policy](http://docs.aws.amazon.com/autoscaling/latest/userguide/as-instance-termination.html) is currently `Default`, however I think it should be `ClosestToNextInstanceHour`- to get the best $ utilisation for when we scale down. The Default policy cares about AZs and launch configurations which probably aren't of concern to ephemeral CI instances

**Comment by toolmantim** [comment]
Thanks for the suggestion, that absolutely sounds sensible! If you have a chance could you send through a PR, but if not we'll get to it sometime soon.
