### ISSUE TITLE
Upgrade linux kernel to 5.13

### ISSUE THREAD

**Issue by DanielHeath** [buildkite/elastic-ci-stack-for-aws#1082]
I'm running into (what appears to be) https://github.com/moby/buildkit/issues/1459 fairly frequently. 

Multiple posters on that issue claim that the 5.13 kernel resolves this - however, I would prefer not to maintain my own AMIs just to see if it helps.

`sudo amazon-linux-extras | grep kernel` currently lists 
```
  _  kernel-5.4               available    [ =stable ]
 55  kernel-5.10=latest       enabled      [ =stable ]
 62  kernel-5.15              available    [ =stable ]
```

Is there a good reason to stick with the older kernel? Adding `sudo amazon-linux-extras install kernel-5.15 -y` to the packer build script should be enough to update it.

(Normally I would use an instance-boot script to install/update packages, but updating the kernel requires a restart, which doesn't help in an autoscaling environment).

**Comment by triarius** [comment]
Hi @DanielHeath thanks for letting us know. This does look like a good reason to upgrade the kernel, so we've made a PR to try this out. It should be available in a release of the stack shortly.

**Comment by triarius** [comment]
This is now merged to master, so you should be able to see something like
```
sh-4.2$ uname -a
Linux ip-10-0-2-192.ec2.internal 5.15.86-53.137.amzn2.x86_64 #1 SMP Sat Dec 31 18:40:35 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```
on a newly launched stack. This will be included in the next minor release of the agent.
