### ISSUE TITLE
Amazon Linux 2022

### ISSUE THREAD

**Issue by razbomi** [buildkite/elastic-ci-stack-for-aws#1096]
**Is your feature request related to a problem? Please describe.**
I am having trouble with using node 18 with the default buildkite agent AMI on elastic stack version v5.16.1. 

```
node: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by node)
node: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by node)
```

This is because amazon linux 2 doesn't support the latest LTS for nodejs.
https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/setting-up-node-on-ec2-instance.html

Amazon recommend using node 16 instead.

**Describe the solution you'd like**
Do you have any plans to upgrade to a newer version of [amazon linux](https://docs.aws.amazon.com/linux/al2022/release-notes/relnotes-20230118.html)?
I'm happy to raise a PR if it would be helpful.

**Describe alternatives you've considered**
I am running docker in docker which is causing slow builds and build failures for various reasons.
I have considered installing `glibc` in the the host bootstrap script.
I am happy to try any alternative suggestions.

**Additional context**
Build failure using the following [asdf plugin](https://github.com/byerobot/asdf-buildkite-plugin):

<img width="1593" alt="Screenshot 2023-02-21 at 8 59 06 pm" src="https://user-images.githubusercontent.com/1096424/220313126-f37c86a1-f4c8-4ea7-8167-d33c28cebc7b.png">

This is my `.tool-versions`:

```
terraform 1.0.10
terragrunt 0.35.5
nodejs 18.14.1
```

**Comment by toothbrush** [comment]
We actually _just_ got bitten by this, and i was thinking the same (i could open a PR).  However, looking at the Packer config:

https://github.com/buildkite/elastic-ci-stack-for-aws/blob/8022cb599c3693fa741d0f5d9d11cf3fbe153b91/packer/linux/buildkite-ami.json#L14

And searching for AMIs in AWS Console, it looks as if it will in fact select the newest version? 🤔 I'm a bit confused, i'd have expected to see a 5.15 kernel available at least, since that's what you get when you `docker run --rm -it amazonlinux`:

```shellsession
bash-4.2# uname -a
Linux 5c241319d407 5.15.49-linuxkit #1 SMP PREEMPT Tue Sep 13 07:51:32 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux
```

**Comment by toothbrush** [comment]
Ah right, AL2 is apparently being replaced by AL2022, but that's still [in Release Candidate phase](https://aws.amazon.com/linux/amazon-linux-2022/?amazon-linux-whats-new.sort-by=item.additionalFields.postDateTime&amazon-linux-whats-new.sort-order=desc). TIL.

**Comment by razbomi** [comment]
> Ah right, AL2 is apparently being replaced by AL2022, but that's still [in Release Candidate phase](https://aws.amazon.com/linux/amazon-linux-2022/?amazon-linux-whats-new.sort-by=item.additionalFields.postDateTime&amazon-linux-whats-new.sort-order=desc). TIL.

Yeah AL2022 one of these ones, I assume. It has been in [preview since 2021](https://aws.amazon.com/about-aws/whats-new/2021/11/preview-amazon-linux-2022/), I don't see any indication of when they plan to GA though 😕. 
 
<img width="1343" alt="Screenshot 2023-02-22 at 11 52 55 am" src="https://user-images.githubusercontent.com/1096424/220492646-d06835f4-6e78-4094-9168-ae65300bd5dc.png">

**Comment by triarius** [comment]
Have you considered running node in a docker container?

**Comment by triarius** [comment]
As for the situation with AL2022, we can't commit to basing an Elastic CI Stack until it is GAed. We are also waiting for that to happen, but please ping us if it does, and we will get the ball rolling.

**Comment by GZLiew** [comment]
we just got bitten by this issue as well! some of our dependencies requires node18. We fallback to the docker approach but since we already have node setup on our agent. We will prefer using the from the agent instead.
Cant wait for amazon to release it soon

**Comment by razbomi** [comment]
@triarius If I understand correctly ... AL2022 will be end of life in June and we will have to jump to 2023.

**Comment by triarius** [comment]
Not sure. AL2023 in some ways seems like a complete rename of AL2022. The [repo](https://github.com/amazonlinux/amazon-linux-2022) is redirected, for example.

AL2 EOL has been extended to June 2025, however. Hopefully, AL202x will be GA by then.
See https://aws.amazon.com/amazon-linux-2/faqs/, https://aws.amazon.com/linux/amazon-linux-2023/faqs/
![See https://aws.amazon.com/amazon-linux-2/faqs/](https://user-images.githubusercontent.com/11096602/223620115-7e2f8b57-d47d-459e-9f0e-04a819e21826.png)

**Comment by ChrisLane** [comment]
As mentioned in #998, Amazon Linux 2023 has been released now.

**Comment by edify42** [comment]
Nice one buildkite team :clap: 

Any date on when it will go from beta (currently) to a proper release?
