### ISSUE TITLE
Docs improvement for docker user namespacing on by default.

### ISSUE THREAD

**Issue by hrfuller** [buildkite/elastic-ci-stack-for-aws#1105]
**Is your feature request related to a problem? Please describe.**
I had to bang my head against a build failing in the aws container due to various permissions issues before I figured out it had to do with namespacing, which I then turned off.

**Describe the solution you'd like**
It would be great if there was a troubleshooting section about this in the docs somewhere, other than just the parameter specification. I'm not a docker superuser so it took me a while to figure out that namespace isolation could cause a bunch of disparate issues.

**Describe alternatives you've considered**
Flipping the default namespace isolation to false.

**Additional context**

Edit for those curious the parameter in question to change to false was `EnableDockerUserNamespaceRemap`

**Comment by triarius** [comment]
Thanks for using the Elastic CI Stack for AWS @hrfuller. We are working on uplifting the docs and a "Troubleshooting" section is something we are strongly considering. If you want to share some more specific error messages you encountered, letting us include them in the docs might be very helpful to future users. Just be sure, if you are sharing anything, to scrub any sensitive information.

**Comment by hrfuller** [comment]
Sure: The context for this was building a docker image. Operations with apt-get inside container would fail with dmesg or dpkg error when trying to remove the `.deb`s in root directories. IIUC the namespace mapping maps the UID 0 inside the container to that of `buildkite-agent` on the host so some of these actions were mapped to a host operation, and denied. Since this is permissions related it manifests in a ton of different ways, though. Here is one:
```
$ tar xzvf <some file> -C /`
#11 504.3 tar: ./usr: Cannot utime: Operation not permitted
--
  | #11 504.3 tar: ./usr: Cannot change ownership to uid 0, gid 0: Operation not permitted
  | #11 504.3 tar: Exiting with failure status due to previous errors
```

Here is another 
```
sudo apt-get autoremove -y -qq &&   rm -rf /var/lib/apt/lists/*:
--
  | #50 163.5 dpkg: error processing package libgdal-dev (--remove):
  | #50 163.5  cannot remove '/usr/lib/libgdal.so': Permission denied
  | #50 163.5 dmesg: read kernel buffer failed: Operation not permitted
  | #50 163.5 dpkg: too many errors, stopping
  | #50 163.5 Errors were encountered while processing:
  | #50 163.5  libgdal-dev
  | #50 163.5 Processing was halted because there were too many errors.
```
Hope that helps

**Comment by triarius** [comment]
Thanks! We've updated the docs: https://buildkite.com/docs/agent/v3/elastic-ci-aws/troubleshooting#permission-errors-when-running-docker-images-with-volume-mounts
