### ISSUE TITLE
AWS ECR login creds are clobbered by pre-command

### ISSUE THREAD

**Issue by toolmantim** [buildkite/elastic-ci-stack-for-aws#111]
At the moment there's no way to login to ECR to use the `docker-compose` build/push support.

If you add an `env` hook that performs:

```
$(aws ecr get-login --region us-west-2)
```

then because of [our pre-command hook](https://github.com/buildkite/elastic-ci-stack-for-aws/blob/76990cb0ca0422b0d3c61e6ca0bdf335243ea56c/packer/conf/buildkite-agent/hooks/pre-command#L5) the creds get removed before any commands are run.

The pre-command hook basically undoes the env hook.

I propose we:

* Don't `rm` the docker config files (but if we must keep it, at least move it into the conditional)
* Add built-in support for `AWS_ECR_LOGIN=<region>` which performs the login for you

We could also add support for logins in https://github.com/buildkite-plugins/docker-compose-buildkite-plugin itself?

**Comment by bforchhammer** [comment]
Oh man, I tried to `docker login` via the env script, as suggested in the README, but keep getting 403s... now I know why! :wink: 

My "env" file now contains the following 2 additional lines...

    echo "Removing /etc/buildkite-agent/hooks/pre-command, as it messes with docker login"
    rm /etc/buildkite-agent/hooks/pre-command
    docker login ...

**Comment by lox** [comment]
Hrm, why do we do the login stuff in a pre-command hook rather than the environment hook?

**Comment by lox** [comment]
Seems like at a minimum we should have a conditional guard around deleting existing creds only if `DOCKER_HUB_*` is specified.

**Comment by toolmantim** [comment]
@lox I have no idea why it's in the pre-command hook, no reason we can't move it into the environment hook.

**Comment by lox** [comment]
I suspect I was trying to ensure that credentials from a past command couldn't be accidentally leaked to a subsequent command, but the env hook should do that fine.

**Comment by bforchhammer** [comment]
Doesn't the `docker login` command always look the same, i.e. could the hook not just support a generic login mechanism? I wouldn't mind the config cleanup, if I could provide docker credentials some other way... 

From looking at the pre-command hook, email would need to be optional (it's deprecated with newer docker versions), and we would need a way to add the "repository service url". 

We're using `quay.io` and the login command in the end looks like this: `docker login -u username -p password quay.io`.

**Comment by toolmantim** [comment]
I just pushed changes for this to #127

@bforchhammer this would look like this now for quay.io:

```bash
export DOCKER_LOGIN_USERNAME=username
export DOCKER_LOGIN_PASSWORD=password
export DOCKER_LOGIN_SERVER=quay.io
```

For Docker Hub it's simply:

```bash
export DOCKER_LOGIN_USERNAME=username
export DOCKER_LOGIN_PASSWORD=password
```

For AWS ECR it's:

```bash
export AWS_ECR_LOGIN=true
```

For ECR registries in other accounts:

```
export AWS_ECR_LOGIN_REGISTRY_IDS=account-id-1,account-id-2
```

I should probably update the Readme to read like the above… with sub-headings for whichever registry you use.

**Comment by bforchhammer** [comment]
I finally got around to testing this... Works perfectly, thank you! @toolmantim

**Comment by toolmantim** [comment]
Awesome, great stuff @bforchhammer!

**Comment by bforchhammer** [comment]
Oh before I forget, please note that the actual env variable name in code is actually `DOCKER_LOGIN_USER` and not `DOCKER_LOGIN_USERNAME`... just in case anyone stumbles on this issue and tries to follow your instructions above ;-)

**Comment by toolmantim** [comment]
@bforchhammer thanks!

**Comment by singhrcode** [comment]
@lox  how can see the debug messages for env hooks . i have put docker login credential there and nothing is happenning , not sure  how to debug if those scripts are getting invoked or not

**Comment by lox** [comment]
Wanna send us an email at support@buildkite.com with some context @singhrcode? Doesn't sound related to the above issue.
