### ISSUE TITLE
Recent spike in "agent lost" build failures

### ISSUE THREAD

**Issue by DanielHeath** [buildkite/elastic-ci-stack-for-aws#1152]
**Describe the bug**

Over the past week or so, I'm getting 10% or so of CI builds failed with "agent lost". Previously, I estimate it was closer to 1%.

**Steps To Reproduce**

Run a bunch of builds

**Expected behavior**

Builds run to completion

**Actual behaviour**

Multiple build failures with an unclear error message

**Stack parameters (please complete the following information):**
 - AWS Region: us-east-2
 - Version 5.17.0

**Comment by triarius** [comment]
Hi @DanielHeath can you raise this with support@buildkite.com. They will be able to work with you to diagnose the issue.
