### ISSUE TITLE
Propagate CostAllocationTag to EBS

### ISSUE THREAD

**Issue by keatmin** [buildkite/elastic-ci-stack-for-aws#1154]
**Is your feature request related to a problem? Please describe.**
Cost Allocation Tag is available but the tag is not being propagated to EBS volume of the launch template. It is important to have cost allocation tag being propagated into the volume as well to determine a more accurate cost attribution of infra. 

**Describe the solution you'd like**
Under [TagsSpecification](https://github.com/buildkite/elastic-ci-stack-for-aws/blob/128a3a007d1fe9ab2957027eccd6956666e4c217/templates/aws-stack.yml#L1105) of the stack launch template, we can add a [ResourceType: volume](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-launchtemplate-tagspecification.html) as per the documentation and propagate `UseCostAllocationTags`, `CostAllocationTagName`, and `CostAllocationTagValue` into the EBS Volume of the launch template

**Describe alternatives you've considered**
Manually adding one into the EBS volume or creating the tag 

**Additional context**
n/a

**Comment by moskyb** [comment]
hey, this is a great idea - would you be willing to submit a PR for it?
