### ISSUE TITLE
WARN: "The git-mirrors experiment has been promoted to a stable feature"

### ISSUE THREAD

**Issue by DanielHeath** [buildkite/elastic-ci-stack-for-aws#1156]
**Describe the bug**
After upgrading to 5-21-0 (linux, arm instances), builds get a warning printed.

**Steps To Reproduce**
Run a build on a current stack with the "EnableAgentGitMirrorsExperiment" flag enabled.

**Expected behavior**
The "EnableAgentGitMirrorsExperiment" parameter should not be available in the stack, since the feature is enabled by default and the agent warns you if you still use it.

**Comment by moskyb** [comment]
This will be fixed in V6, due out Very Soon™️ :)

**Comment by triarius** [comment]
v6 is out, let us know if this is still an issue.
