### ISSUE TITLE
Agents lost error after stack upgrade

### ISSUE THREAD

**Issue by anta-semenov** [buildkite/elastic-ci-stack-for-aws#1160]
**Describe the bug**
After upgrading stack to version 5.22.0 (previous version was from 2020, don't remeber exact number) the jobs start to fail with `Exited with status -1 (agent lost)` error.
The `ScaleInIdlePeriod` paameter is set to 1800, but jobs faing even after 9 minutes after the start.
It usually happens on running unit tests with jest.
After multiple retries (2 - 4) it usually finishes

**Expected behavior**
The jobs shouldn't loose an agent during build

**Stack parameters (please complete the following information):**
 - AWS Region: multiple regions eu-west-1, eu-west-2
 - Version v5.22.0

**Additional context**
The stacks were updated from the previous ones, by selecting `Update` -> `Replace current template`

**Comment by moskyb** [comment]
kia ora @anta-semenov! this will be a lot easier to debug if we have access to your builds - can you email support@buildkite.com and include links to some of the builds that failed?

**Comment by triarius** [comment]
@anta-semenov We're going to close this. Please let us know if it's a blocker for you and send some build URLs, and we will gladly open it back up.
