### ISSUE TITLE
YAMLColonInFlowContext error while downloading v6.2.0

### ISSUE THREAD

**Issue by GZLiew** [buildkite/elastic-ci-stack-for-aws#1195]
**Describe the bug**
Hi all we are getting an error while downloading the template from your S3 bucket
https://s3.amazonaws.com/buildkite-aws-stack/v6.2.0/aws-stack.yml

**Expected behavior**
Should download stack ci file without error.

**Actual behaviour**
```
$ trap 'kill -- $' INT TERM QUIT; ./infra/deploy-cicd-stack.sh x86
--
  | Downloading Buildkite Elastic CI Stack template
  |  
  | while scanning a plain scalar
  | in "<string>", line 1150, column 66:
  | ... eStackNameForInstanceName, !Ref AWS::StackName, !Ref InstanceName ]
  | ^
  | found unexpected ':'
  | in "<string>", line 1150, column 69:
  | ... ackNameForInstanceName, !Ref AWS::StackName, !Ref InstanceName ]
  | ^
  | Please check http://pyyaml.org/wiki/YAMLColonInFlowContext for details.

```

**Stack parameters (please complete the following information):**
 - AWS Region: [e.g. ap-southeast-2]
 - Version [e.g. v6.2.0]

**Comment by DrJosh9000** [comment]
Hi @GZLiew, thanks for the report! 

We're pretty confident that launching the stack using the AWS Console UI works, so AWS accepts it as valid. We can't see exactly what your `./infra/deploy-cicd-stack.sh` script is doing, other than using PyYAML at some point.

Are you using an outdated version of the AWS CLI, or manually parsing the stack some other way?

**Comment by GZLiew** [comment]
hey @DrJosh9000 I believe you could be right about a outdated aws cli

we currently download the template and directly call the cli on our server

```
echo "Downloading Buildkite Elastic CI Stack template"
curl -sO "https://s3.amazonaws.com/buildkite-aws-stack/$STACK_VERSION/aws-stack.yml"

# shellcheck disable=SC2086
aws cloudformation deploy \
	--stack-name "$STACK_NAME" \
	--template-file ./aws-stack.yml \
	--capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND \
	--parameter-overrides $PARAMETERS
```

**Comment by triarius** [comment]
@GZLiew we're going to close this. Let us know if it's still an issue on the latest aws cli, and we'll open it back up.
