### ISSUE TITLE
Ephemerality breaks with minsize > 0

### ISSUE THREAD

**Issue by dtertman** [buildkite/elastic-ci-stack-for-aws#1261]
We want two things out of our runner pool : all runners should be ephemeral (one-job), and we should be able to reserve capacity so that developers aren't waiting for runners to boot.

While the elastic stack does have the `BuildKiteTerminateInstanceAfterJob` parameter, we have found it fails if the MinSize is greater than 0. The error message from AWS is:

```
An error occurred (ValidationError) when calling the TerminateInstanceInAutoScalingGroup operation: Currently, desiredSize equals minSize (1). Terminating instance without replacement will violate group's min size constraint. Either set shouldDecrementDesiredCapacity flag to false or lower group's min size.
```

The error message tells us how this could be resolved -- in the case of an agent terminating after its one job, the call to terminate could keep set `shouldDecrementDesiredCapacity` to false. In testing from the command line, this worked -- the instance successfully terminated and a new one immediately rose to replace it.

**Steps To Reproduce**
1. Create a stack with BuildKiteTerminateInstanceAfterJob true and MinSize 1
2. Run a workflow on a runner from that stack
3. Check the logs and see the error
4. Run the workflow again and notice it is assigned to the same instance-id.

**Expected behavior**
Our expectation was that BuildKiteTerminateInstanceAfterJob would be able to kill the instance, and MinSize would immediately launch a new one.

**Actual behaviour**
The instance stayed up.

**Stack parameters (please complete the following information):**
 - us-east-1
 - Version 6.3.0

**Comment by triarius** [comment]
Hi @dtertman, we did some [work](https://github.com/buildkite/elastic-ci-stack-for-aws/releases/tag/v6.9.0) recently to address something like this. Can you try upgrading to (v6.10.0)[https://github.com/buildkite/elastic-ci-stack-for-aws/releases/tag/v6.10.0] and see if you can reproduce the issue?

**Comment by dtertman** [comment]
Oh nice, that looks like my problem exactly -- didn't realize we were so far behind in releases. Will close this out and open a new one if I find newer versions not working.
