### ISSUE TITLE
CI Stack not working for ARM64 instances 

### ISSUE THREAD

**Issue by oh-tarnished** [buildkite/elastic-ci-stack-for-aws#1268]
**Describe the bug**

> When deploying the Buildkite Elastic CI Stack using AWS CloudFormation on ARM64 instances like `t4g.large` with AMI `ami-07d67603110c131fb`, the Buildkite agent, Docker, and SSH keys from the secret bucket are not installed on the EC2 instance. Additionally, the IAM role does not seem to be correctly assigned.

**Steps To Reproduce**

  1. Deploy the CI stack using AWS CloudFormation.
  2. Specify ARM64 instances `(t4g.large)` and use AMI `ami-07d67603110c131fb`.
  3. After the CI process completes and the EC2 instance is up, SSH into the instance.
  4. Observe the absence of the Buildkite agent, Docker, and SSH keys.

**Expected behavior**

> The EC2 instance spun up should have the Buildkite agent installed, Docker set up, and access to SSH keys from the secret bucket. The instance should also correctly assume the specified IAM role.

**Actual behaviour**

> The EC2 instance lacks the Buildkite agent and Docker installation. SSH keys from the secret bucket and the IAM role are not correctly assigned.

**Stack parameters (please complete the following information):**

  - AWS Region: `ap-south-1`
  - Version `v6.10.0`

**Additional context**

> This issue hinders the utilization of ARM64 instances in our CI pipeline, affecting the potential for performance improvements and cost optimization.

**Comment by oh-tarnished** [comment]
Hey @triarius, Well we were able to deploy it properly i think it issue only comes up when used it with this ami `ami-07d67603110c131fb`

**Comment by DrJosh9000** [comment]
Hi @oh-tarnished, can you tell us more about how you are using ami-07d67603110c131fb and why (compared with launching with a Buildkite AMI)? It looks like that AMI is just the base Amazon Linux 2023 image, which would lack the Buildkite Agent, Docker, etc.
