### ISSUE TITLE
Support Docker v25 for remote image caching

### ISSUE THREAD

**Issue by JacobEvelyn** [buildkite/elastic-ci-stack-for-aws#1287]
**Is your feature request related to a problem? Please describe.**
We use Buildkite to push docker images to AWS ECR (using https://github.com/buildkite-plugins/ecr-buildkite-plugin) and would like to be able to do something like [this](https://aws.amazon.com/blogs/containers/announcing-remote-cache-support-in-amazon-ecr-for-buildkit-clients/) to take advantage of remote caching and minimize docker build times. My understanding is that this is [available in docker v25.0](https://github.com/moby/moby/issues/45926), but when I try those changes with v6.14.0 of this stack I get:

```
ERROR: Cache export is not supported for the docker driver.
Switch to a different driver, or turn on the containerd image store, and try again.
Learn more at https://docs.docker.com/go/build-cache-backends/
```

**Describe the solution you'd like**
I'd like to be able to use this feature to speed up our Buildkite builds! My hope is all that's required is a bump to Docker v25.0+.

**Describe alternatives you've considered**
I've tried searching the Buildkite plugin ecosystem for similar functionality. This feature seems to be available with https://github.com/buildkite-plugins/docker-compose-buildkite-plugin but I'd like to be able to use it with native docker, not docker compose. I also found https://github.com/seek-oss/docker-ecr-cache-buildkite-plugin but don't understand why this should require a third-party plugin.

**Additional context**
I couldn't find a lot of documentation on this so it's very possible I simply misconfigured something!

**Comment by triarius** [comment]
Hi @JacobEvelyn we follow the version of Docker in the base Amazon Linux AMI. The latest elastic stack (v6.14.0) is based off Amazon Linux 2023.3.20240122.0, which [appears](https://docs.aws.amazon.com/linux/al2023/release-notes/relnotes-2023.3.html) [to be](https://docs.aws.amazon.com/linux/al2023/release-notes/relnotes.html) the latest version at the time of writing.

I've raised [an issue](https://github.com/amazonlinux/amazon-linux-2023/issues/624) in the Amazon Linux repository, so we should be able to update to the latest version of Amazon Linux when they release it.

As for the remote caching, maybe you might have some luck using the other tool mentioned in the announcement, [finch](https://github.com/runfinch/finch). You should be able to install it in a Bootstrap script, which you can upload to S3 and point the [BootstrapScriptUrl](https://buildkite.com/docs/agent/v3/elastic-ci-aws/parameters#BootstrapScriptUrl) parameter at.

**Comment by JacobEvelyn** [comment]
Hi @triarius ! It looks like the other issue you raised is resolved—is there a timeline for when this stack might be updated to take advantage of that update?

**Comment by triarius** [comment]
Stacks launched from the [`main`](https://s3.amazonaws.com/buildkite-aws-stack/main/aws-stack.yml) template will have v25 in it now. We are working on releasing it soon.

**Comment by triarius** [comment]
@JacobEvelyn [`v6.17.0`](https://github.com/buildkite/elastic-ci-stack-for-aws/releases/tag/v6.17.0) is out and should have Docker 25 in it.

**Comment by baileywickham** [comment]
Hi, @JacobEvelyn were you able to get this working? 

I'm getting the same error (ERROR: Cache export is not supported for the docker driver.) even after upgrade to docker version `25.0.3`. I'm using the exact commands from the AWS post you linked. Did you need to enable containerd on the buildkite instance too?
