### ISSUE TITLE
Stack creation in eu-central-2 fails

### ISSUE THREAD

**Issue by ihorch** [buildkite/elastic-ci-stack-for-aws#1297]
**Describe the bug**
Creation of AWS Buildkite CI stack (v6.12.0) fails in Zurich region.
Error:

> Transform AWS::Serverless-2016-10-31 failed with: Invalid Serverless Application Specification document. Number of errors found: 1. Resource with id [Autoscaling] is invalid. Serverless Application Repository is not available in this region.

**Steps To Reproduce**
1. Switch to Zurich
2. Go to Cloudformation
3. Deploy new stack
4. Deployment almost immediately fails

**Expected behavior**
Stack is created normally.

**Actual behaviour**
Stack creation fails almost immediately with the error above.

**Stack parameters (please complete the following information):**
 - AWS Region: eu-central-2
 - Version v6.12.0

**Additional context**
None

**Comment by moskyb** [comment]
hi @ihorch! unfortunately this is a limitation on AWS's side - the Zurich region doesn't have the Serverless Application Repository service available (yet?). it's a dependency of the elastic stack, so until AWS adds support for SAR in Zurich, we won't be able to launch elastic stacks there.

**Comment by namnd** [comment]
> hi [@ihorch](https://github.com/ihorch)! unfortunately this is a limitation on AWS's side - the Zurich region doesn't have the Serverless Application Repository service available (yet?). it's a dependency of the elastic stack, so until AWS adds support for SAR in Zurich, we won't be able to launch elastic stacks there.

Hi @moskyb ,
We have same issue where we would like to deploy elastic stack to a region where SAR is not available. 
Is that possible to have an alternative for this, rather than completely depends on AWS adding support for SAR? I guess it must have something to do with Intellectual Property owned by Buildkite, but worth taking a shot at asking anyway
