### ISSUE TITLE
Missing "build" folder for packe

### ISSUE THREAD

**Issue by kenny-ferrer** [buildkite/elastic-ci-stack-for-aws#1374]
**Describe the bug**
Missing build folder from the repo

buildkite-ami.pkr.hcl for Linux has a Provisioner file 

`  provisioner "file" {
    destination = "/tmp/build"
    source      = "../../build"
  }`

This is located in elastic-ci-stack-for-aws/packer/linux/buildkite-ami.pkr.hcl line 90

This will fail the image cration

**Comment by DrJosh9000** [comment]
Hi @kenny-ferrer, the `build` folder is created prior to running packer by some actions in the Makefile, e.g.:

https://github.com/buildkite/elastic-ci-stack-for-aws/blob/c7167d4a71c60daf52c70b9cf5078bd41bb517dc/Makefile#L51

**Comment by kenny-ferrer** [comment]
Thank you @DrJosh9000, I should have search better.
