### ISSUE TITLE
Document adding an SSH key into secrets bucket in Getting Started

### ISSUE THREAD

**Issue by j-clark** [buildkite/elastic-ci-stack-for-aws#140]
Right now, you must define your SecretsBucket as part of the CloudFormation configuration and only then are you able to override it with an environment variable.

It would be great to be able to set this using only environment variables, so that I could use the default CloudFormation stack and only need to use buildkite to configure this.

**Comment by lox** [comment]
The issue is that the CloudFormation stack needs to create permissions for the secrets bucket. Having a variable secrets bucket makes that very hard to do.

**Comment by j-clark** [comment]
Okay! That makes sense. Buildkite support asked me to create this issue.

Another idea would be to make it more explicit in the step-by-step setup instructions. I assume most people are going to need an SSH key in order to download the code, so this might could just be added as a step so other people don't get tripped up by it

**Comment by lox** [comment]
Yup, makes sense. It's got a section in https://github.com/buildkite/elastic-ci-stack-for-aws#secrets-bucket-support, but it would be good to get it in the step-by-step.

**Comment by lox** [comment]
New README addresses this!
