### ISSUE TITLE
Smarter autoscaling with multiple agents per instance

### ISSUE THREAD

**Issue by sgringwe** [buildkite/elastic-ci-stack-for-aws#144]
We are using aws ci stack with multiple agents per instance. It looks like the buildkite scheduler picks (seemingly) random agents from the pool of instances when picking containers for builds. This seems to result in the auto-scaler having more capacity than needed because even if we are only using 20 agents, they are spread out across all 10 instances, each instance having 2 agents being used.

Preferably the scheduler would pick agents from the instances that are already being used so that the other instances can scale down and save $$.

**Comment by lox** [comment]
That seems like it could backfire, wouldn't that lead to higher latency in most situations, as you'd be assigning builds to agents on the same host and it would slow down? 

The scheduler will pick the agent that last ran a similar build, to optimize cache, but aside from this will pick a random host.

**Comment by lox** [comment]
Auto-scaling should happen based on scheduled jobs, so theoretically if there is an oversupply of agents, it should correct itsself regardless of whether there are agents running jobs on the machines that get shut down.
