### ISSUE TITLE
Add support for AWS spot fleets

### ISSUE THREAD

**Issue by shuber** [buildkite/elastic-ci-stack-for-aws#147]
http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/spot-fleet.html

We ran into issues today when the spot price for the instance type that we're using skyrocketed. We ended up just spinning up a separate stack with an alternative instance type in the meantime. It would be cool to be able to specify a few different instance types and let spot fleet handle issues like these.

![screenshot 2016-09-19 11 42 26](https://cloud.githubusercontent.com/assets/2419/18650840/6480d4f4-7e7c-11e6-90c3-51411b8d348d.png)

**Comment by lox** [comment]
I'd suggest running two stacks, one spot and one non-spot. The issue with spot fleet is that (as of last time I looked) there wasn't a way to scale it based on need.

**Comment by toolmantim** [comment]
@lox I think that changed somewhat recently: https://aws.amazon.com/blogs/aws/new-auto-scaling-for-ec2-spot-fleets/

**Comment by lox** [comment]
Oh I totally forgot about that, apologies. Happened whilst I was on holidays :) 

In that case, I'm on it.

**Comment by lox** [comment]
Ok, am starting to dev on this now. Of course the complexity is that each region has slightly different spot instances available.

**Comment by caarlos0** [comment]
+1

Can I help with anything?

**Comment by atyndall** [comment]
+1. This would be great for us also, being able to choose several instance types around the same performance threshold will help us avoid spot price fluctuations.

**Comment by lox** [comment]
Starting work on this in ##269

**Comment by tspacek** [comment]
For anyone who wants to give this a shot manually (outside of Cloudformation): make a new Spot Fleet request, copy the config from Buildkite's ASG Launch Configuration, then hook the Spot Fleet into the same auto-scaling events. Turn off the ASG. Done.

Only wrinkle so far is that the number of agents per instance isn't aware of the number of vCPUs, as far as I know.

**Comment by jtoy** [comment]
just checking in on this :)

**Comment by KevinGrandon** [comment]
@tspacek Thanks for the manual implementation steps above. Just wondering if you're still using this approach and how you're finding it. If you are using it I'm also wondering how you hooked this up to the autoscaling events and if this works with the new lambda scaler. Thanks!

**Comment by keithduncan** [comment]
With the multi-instance type functionality exposed through Launch Templates and Auto Scale groups allowing instance requests to span on-demand and spot, I don’t think there’s a need to integrate EC2 Fleets directly anymore 🥳
