### ISSUE TITLE
Cloudformation rolls back creation in `us-east-1c`

### ISSUE THREAD

**Issue by chrislloyd** [buildkite/elastic-ci-stack-for-aws#156]
This mightn't be an issue with this repo, but when I try and spin up a cluster in N. Virginia, it consistently gets rolled back.

```
AWS::EC2::Subnet
Subnet2
Value (us-east-1c) for parameter availabilityZone is invalid. Subnets can currently only be created in the following availability zones: us-east-1e, us-east-1a, us-east-1d, us-east-1b.
```

Googling around looks like it's a [common problem](https://github.com/deis/deis/issues/1601) but mightn't have any immediate outcomes. Perhaps some documentation on what to do if people run into this scenario?

**Comment by lox** [comment]
Yup, it's an annoying one. Tracking it in https://github.com/buildkite/elastic-ci-stack-for-aws/issues/41.

**Comment by lox** [comment]
Workaround here https://github.com/buildkite/elastic-ci-stack-for-aws/issues/41#issuecomment-254076772
