### ISSUE TITLE
Blocked builds if secret environment variables incorrect

### ISSUE THREAD

**Issue by ahawkins** [buildkite/elastic-ci-stack-for-aws#158]
The `BUILDKITE_SECRETS_KEY` is required to get objects from the secrets bucket. However if you have it set incorrectly builds will block when adding an SSH key. The build blocks waiting for input on STDIN. Is there some way we can prevent this so builds fail?

**Comment by lox** [comment]
Relevant code is https://github.com/buildkite/elastic-ci-stack-for-aws/blob/master/packer/conf/buildkite-agent/hooks/environment#L48-L60. We should be able to make this fail more gracefully.
