### ISSUE TITLE
Set KMS Download of Secrets to be the default approach

### ISSUE THREAD

**Issue by gugahoi** [buildkite/elastic-ci-stack-for-aws#160]
Now that we have KMS integration into the BuildKite agents for secret management I would like to have that as the default way of copying from the S3 secrets bucket instead of having to specify the environment variable `BUILDKITE_USE_KMS`. 

This implies that by default (without having to configure pipelines) BuildKite agents would attempt to decrypt the secrets from S3 using KMS, we could still allow the use of PASSPHRASE for encryption with the same approach it has now (if the ENV variable exists than use it).

Happy to create the pull request if you would like.

**Comment by lox** [comment]
Just ran into this. Caused some head scratching. Made worse by https://github.com/buildkite/elastic-ci-stack-for-aws/issues/158. 

/cc @kiwwa

**Comment by lox** [comment]
Would happily accept a PR @gugahoi.
