### ISSUE TITLE
Using with ECR isn't clear

### ISSUE THREAD

**Issue by chrislloyd** [buildkite/elastic-ci-stack-for-aws#166]
A few bugs / tough things I've encountered:

* "Must specify a region" when using `AWS_ECR_LOGIN=true`. I got around this by force setting the env var `AWS_DEFAULT_REGION`.
* ECR Permissions. I continually get:

```
An error occurred (AccessDeniedException) when calling the GetAuthorizationToken operation: User: arn:aws:sts::053722134931:assumed-role/buildkite-IAMRole-XXX is not authorized to perform: ecr:GetAuthorizationToken on resource: *
```

I think either more documentation around ECR or having the CloudFormation script add an ECR would make this way easier.

**Comment by lox** [comment]
This is fixed in master (hopefully), let me know if it's still not clear!
