### ISSUE TITLE
Increase metrics poll duration

### ISSUE THREAD

**Issue by toolmantim** [buildkite/elastic-ci-stack-for-aws#169]
Related to buildkite/buildkite-metrics#10, to ease up the RPM on the API, it'd be nice to increase the [PollInterval](https://github.com/buildkite/elastic-ci-stack-for-aws/blob/6c0a82766d256333899bdeec8187e0897de02fc3/templates/metrics.yml#L13) from 15s. Perhaps 30s? 60s?

**Comment by lox** [comment]
Yup, that sounds sensible. Apologies for hammering the API.

**Comment by lox** [comment]
This is now 60 seconds, by virtue of the new Lambda stuff.
