### ISSUE TITLE
Managed Policies no longer work after ECR changes

### ISSUE THREAD

**Issue by denmat** [buildkite/elastic-ci-stack-for-aws#173]
It appears that https://github.com/buildkite/elastic-ci-stack-for-aws/pull/167 has introduced a bug to and now managed policies no longer work.

Stack updates with a comma delimited list now produce this error:
`Value of property ManagedPolicyArns must be of type List of String`

I have a copy of a prior stack and the diff between them looks like this:

```
$ diff -uN stack.json buildkite-stack.json
--- stack.json	2016-11-18 14:37:18.000000000 +1100
+++ buildkite-stack.json	2016-11-22 09:06:49.000000000 +1100
@@ -113,17 +113,36 @@
     "IAMRole": {
       "Type": "AWS::IAM::Role",
       "Properties": {
-        "ManagedPolicyArns": {
-          "Fn::If": [
-            "UseSpecifiedIamPolicies",
-            {
-              "Ref": "ManagedPolicyArns"
-            },
-            {
-              "Ref": "AWS::NoValue"
-            }
-          ]
-        },
+        "ManagedPolicyArns": [
+          {
+            "Fn::If": [
+              "UseSpecifiedIamPolicies",
+              {
+                "Ref": "ManagedPolicyArns"
+              },
+              {
+                "Ref": "AWS::NoValue"
+              }
+            ]
+          },
+          {
+            "Fn::If": [
+              "UseECR",
+              {
+                "Fn::FindInMap": [
+                  "ECRManagedPolicy",
+                  {
+                    "Ref": "ECRAccessPolicy"
+                  },
+                  "Policy"
+                ]
+              },
+              {
+                "Ref": "AWS::NoValue"
+              }
+            ]
+          }
+        ],
```

This looks to be the cause:
https://github.com/buildkite/elastic-ci-stack-for-aws/blob/master/templates/buildkite-elastic.yml#L242

ManagedPolicies changes from a hash to an array.

cc:
@lox

**Comment by lox** [comment]
😱

Sorry about that!

**Comment by pvdvreede** [comment]
Is this fix deployed to S3 yet? - I am still getting this issue right now...

**Comment by lox** [comment]
Apologies, not yet, will get this fixed shortly and update docs on how to
refer to old stacks.

**Comment by lox** [comment]
Just pushed a fix out for this, can you let me know how you for @pvdvreede?

**Comment by holmesjr** [comment]
Is this up in S3? I just tried to update using the latest stack at https://s3.amazonaws.com/buildkite-aws-stack/aws-stack.json and had the same issue: IAMRole - UPDATE_FAILED - Value of property ManagedPolicyArns must be of type List of String
