### ISSUE TITLE
Choosing an ECRAccessPolicy w/ causes stack update/create failure

### ISSUE THREAD

**Issue by toolmantim** [buildkite/elastic-ci-stack-for-aws#177]
![failure](https://cloud.githubusercontent.com/assets/153/20551148/da379ff6-b190-11e6-9989-d5a1758beac4.png)

The error is "Value of property ManagedPolicyArns must be of type List of String"

**Comment by denmat** [comment]
I was about to raise the same question - this did not fix it @lox https://github.com/buildkite/elastic-ci-stack-for-aws/pull/176.

I have tried a few combinations but I can't get it to work - that is messing around with these lines:
https://github.com/buildkite/elastic-ci-stack-for-aws/blob/master/templates/buildkite-elastic.yml#L245

**Comment by lox** [comment]
This is fixed in master, could you let me know if this fixes your problem @denmat /  @toolmantim?

**Comment by denmat** [comment]
Fixed for me, thank you.
