### ISSUE TITLE
agent failing on ecr get-login

### ISSUE THREAD

**Issue by micheletest** [buildkite/elastic-ci-stack-for-aws#178]
Especially in the morning, you may see: ERROR: denied: Your Authorization Token has expired. Please run 'aws ecr get-login' to fetch a new one. When this happens, it's an agent that has been running for more than a day. 

Here are some excerpts from a build that had this happen. I modified it and removed parts so let me know if this is sufficient (removed any identifying characteristics of what this job is doing).

```	Running global environment hook	0s
$ /etc/buildkite-agent/hooks/environment
Setting up the environment	1s
Sourcing CloudFormation environment...
 
Starting an SSH Agent...
Agent pid 3354

Running global pre-command hook	0s
$ /etc/buildkite-agent/hooks/pre-command
Running build script	1s
$ docker-compose -f docker-compose.yml down
docker-compose -f docker-compose.yml run our_command bash -c "command is here"
docker-compose -f docker-compose.yml down
Removing network daily_default
WARNING: Network daily_default not found.
Creating network "daily_default" with the default driver
Creating daily-server_1
Pulling container_name (container details)...
ERROR: denied: Your Authorization Token has expired. Please run 'aws ecr get-login' to fetch a new one.
```

**Comment by lox** [comment]
Hi @micheletest sounds like something is going wrong with ECR authentication. Are you running a recent stack version with the `ECRAccessPolicy` parameter?

**Comment by lox** [comment]
The auth token for ECR is 12 hours, which sounds like re-auth somehow isn't happening.

**Comment by micheletest** [comment]
hi @lox I don't think we are setting the ECRAccessPolicy, which would explain this. I am out of the office, but can confirm if that fixes this early next week. Thanks for looking at this.

**Comment by lox** [comment]
@micheletest alternately, set `AWS_ECR_LOGIN=true` in your env vars.

**Comment by micheletest** [comment]
@lox Thanks - setting the AWS_ECR_LOGIN in your env vars worked.

**Comment by lox** [comment]
Great! Updating to the latest stack should fix it too.

**Comment by lox** [comment]
Urgh, this is a regression. Will fix.

**Comment by lox** [comment]
Fixed in master.
