### ISSUE TITLE
Change bootstrap script to pull from s3 or curl

### ISSUE THREAD

**Issue by pvdvreede** [buildkite/elastic-ci-stack-for-aws#196]
Hi there,

I notice that the AuthorziedSshUsers parameter can take a url or an s3 key, and the cfn-init script checks if it starts with `s3:\\` to determine if its a curl or a `aws s3 cp`. Can this same logic be applied to the bootstrap script as well? I want to run a script and would put it in s3 but use an instance profile to allow access to it...

Many thanks.

**Comment by lox** [comment]
Indeed, that would be most sensible! Thanks for the suggestion, happy to accept a PR, or will look at it next time I'm revising the scripts.

**Comment by pvdvreede** [comment]
@lox done!

**Comment by pvdvreede** [comment]
Fixed by #203
