### ISSUE TITLE
KMS for deployment keys failure

### ISSUE THREAD

**Issue by L226** [buildkite/elastic-ci-stack-for-aws#232]
Hi,

I've been trying to use KMS SSE for Bitbucket deployment keys, it seems that either I'm doing something wrong or there's a bug.

I followed the instructions [here](https://github.com/buildkite/elastic-ci-stack-for-aws#build-secrets) exactly:

```
# generate a deploy key for your project
ssh-keygen -t rsa -b 4096 -f id_rsa_buildkite
pbcopy < id_rsa_buildkite.pub # paste this into your github deploy key

aws s3 cp --acl private --sse aws:kms id_rsa_buildkite "s3://${SecretsBucket}/private_ssh_key" 
```

yet when my pipeline initialises I get the following hangup:

```
Running global environment hook	0s
# Executing "/etc/buildkite-agent/hooks/environment"
Setting up the environment	19s
Agent pid 6625
2017-01-16 04:01:48    3.2 KiB private_ssh_key
Downloading ssh key from s3://${SecretsBucket}/private_ssh_key
Enter passphrase for /dev/fd/63:
```

forcing a manual build cancel.

When I add `BUILDKITE_USE_KMS=false` as suggested (and re-upload a new deployment key without KMS SSE) the build runs fine. Is this an issue with Buildkite or my AWS environment?

FWIW I used to use the previous buildkite-agent secrets bucket configuration with $PASSPHRASE based SSE on deployment keys without issue, and now I'm in the process of updating to KMS.

**Comment by lox** [comment]
Sorry you are having issues @L226! What version of the stack are you running?

**Comment by L226** [comment]
v3.0-beta.10

**Comment by L226** [comment]
Hi, so I have investigated the actual agents (2.1.17, 3.0-beta.10 and 3.0-beta.16) on stack versions 1.1, 1.1.1 and 2.0.0-rc1 and the /etc/buildkite-agent/hooks/environment file contains no reference to KMS at all.

However, stack v 2.0.0-rc1 and 'edge' agent i.e. 3.0-beta.17 as well as 'stable' agent i.e. 2.3.2 seem to work as expected. 'experimental' 3.0-beta.16 with stack v 2.0.0-rc1 does not reference KMS.

So I finally managed to get KMS working with the RC stack and stable agents. From what I have seen, stack v1.1.1 does not support KMS at all, with any agent configuration.

**Comment by lox** [comment]
Yup, that is correct @L226. KMS support was added after 1.1.1, which should work with any release of agent. Apologies for the confusion.

**Comment by L226** [comment]
Can you please update documentation to reflect this?

**Comment by lox** [comment]
Yup, will do. It's confusing because the README is shown for the latest
master, rather than the stable version.

We need to do a better job of providing versioned documentation, my
apologies.

**Comment by lox** [comment]
I've made a note in the README, once again, I'm sorry for your wasted time @L226. Feel free to reach out on Slack if I can help debug any future issues.

https://github.com/buildkite/elastic-ci-stack-for-aws/commit/96d3c0f4c3eeccd8f63bd9dbe4086db56106384b
