### ISSUE TITLE
Could the BuildkiteAgentToken be used to collect metrics?

### ISSUE THREAD

**Issue by mdub** [buildkite/elastic-ci-stack-for-aws#239]
The stack currently requires both a `BuildkiteAgentToken` _and_ a `BuildkiteApiAccessToken`.  The API token is used to collect metrics to support auto-scaling.

It seems unfortunate to require both types of token, for a functional stack, since:
- extra complexity of generating and managing two types of credential
- API tokens are tied to a user identity, and will be disabled if that user is disabled/removed

I find myself wishing that the "agent token" could be used to query the length of the queue, making the API token redundant.  It seems appropriate to me that agents, which can take jobs from the queue, could also query the queue size.

Is that already possible, @keithpitt? I suspect not. Assuming not, is it a reasonable thing to wish/ask for? @lox?

**Comment by lox** [comment]
Yes, absolutely. @toolmantim and I have been exploring this. Would love to
make this a reality.

**Comment by mdub** [comment]
Ah, excellent.  I see you've already been discussing it, in https://github.com/buildkite/buildkite-metrics/issues/15#issuecomment-272305230.

**Comment by toolmantim** [comment]
This is completely reasonable, and on the cards! There's also an API change that needs to happen, because the current design won't scale past a trivial amount of build queues.

**Comment by lox** [comment]
This was released in v3.0.0! 🎉
