### ISSUE TITLE
Docker instance missing mounted directory

### ISSUE THREAD

**Issue by kbaum** [buildkite/elastic-ci-stack-for-aws#245]
One of our docker instances started but was missing the mounted app directory

https://vts-monosnap.s3.amazonaws.com/viewthespace_192_2017-02-08_18-41-35__of9gh.png

Here is what the docker logs look like on that instance:

https://gist.github.com/8650cbced79d20f07a4e9d61b0fd449c

Seeing a bunch of broken pipe errors:

write unix /var/run/docker.sock->@: write: broken pipe"

Here are the buildkite agent logs:  https://gist.github.com/471e328df88bc92906ca762e953762e7

And the elastic-stack log : https://gist.github.com/d4c9efb27696ab5249a575305efd77b1

And system logs: https://gist.github.com/13551b65bdc9b78c14d3bf4b778ffbd3

**Comment by lox** [comment]
@kbaum This looks at first glance like an issue with your docker or docker-compose setup within `run.sh` Are you able to provide the contents of that file? DM on aws-stack slack would be fine.

**Comment by kbaum** [comment]
I can definitely provide that to you.  One thought though.  Do you think it could be an issue with our setup if it only happens sporadically?  In this case, it was only happening on one of the 10 aws instances the build was running on.

thx!

**Comment by lox** [comment]
Have you seen this since upgrading to a recent version of the stack @kbaum?
