### ISSUE TITLE
Scheduled Lambda support broken for eu-west-2

### ISSUE THREAD

**Issue by toolmantim** [buildkite/elastic-ci-stack-for-aws#249]
If you try to instantiate the stack in eu-west-2 (London) the CloudFormation stack creation will fail with the following error:

> 13:37:03 UTC+1100 CREATE_FAILED AWS::Events::Rule ScheduledRule Resource is not supported in this region

There's this AWS Forum thread reporting the issue as well (which I'll add to as well):
https://forums.aws.amazon.com/thread.jspa?threadID=248728

**Comment by toolmantim** [comment]
I've just pushed a [use-metrics-stack-instead-of-lambda branch](https://github.com/buildkite/elastic-ci-stack-for-aws/compare/use-metrics-stack-instead-of-lambda) in the meantime for `eu-west-2` that uses the old metrics stack instead of the Lambda function. Once AWS has resolved this we'll be able to ditch this branch and close the issue.

The stack URL for that branch is published at:
https://s3.amazonaws.com/buildkite-aws-stack/use-metrics-stack-instead-of-lambda/aws-stack.json

You'll need to edit the JSON to include the AMI mappings from the [master branch version](https://s3.amazonaws.com/buildkite-aws-stack/master/aws-stack.json):

Here's a zip with the modified version (based on dbf54d7b2acd8dc39d766b31bb8b9d3b9ae2ed1e) which I've tested on eu-west-2: 
[aws-stack.json.zip](https://github.com/buildkite/elastic-ci-stack-for-aws/files/769097/aws-stack.json.zip)

**Comment by toolmantim** [comment]
It's still not working. I've filed a follow-up thread here on the AWS Lambda forum instead:
https://forums.aws.amazon.com/thread.jspa?threadID=249373

**Comment by toolmantim** [comment]
AWS has confirmed this is a bug in CloudFormation and they're working on a fix. I'll update this ticket when I hear more.

**Comment by lox** [comment]
I wonder if this is still broken @toolmantim?

**Comment by toolmantim** [comment]
Nope, this has since been fixed by AWS!
