### ISSUE TITLE
Consider incorporating aws-ecr-gc?

### ISSUE THREAD

**Issue by bjeanes** [buildkite/elastic-ci-stack-for-aws#267]
I wonder if it makes sense to incorporate https://github.com/99designs/aws-ecr-gc as a system-wide hook to cleanup old test images when using ECR.

Thoughts?

**Comment by lox** [comment]
Yup, awesome idea! I wonder how we'd make it generalized? Currently it relies on consistent tag prefixes, right?

**Comment by bjeanes** [comment]
I think so, but that would work in the Buildkite case, I think:

<img width="764" alt="2017-04-07 at 1 55 pm" src="https://cloud.githubusercontent.com/assets/2560/24785058/1803ac3a-1b9a-11e7-8f16-673b453fd9f9.png">

My images all get tagged as `"#{pipeline}-#{compose_service}-build-#{buildkite_build_num}"`. 

Now, I suppose you might be flagging a potential collision with, say, production images. That's fair. In my case, I have a dedicated ECR repo just for my builds and I don't deploy from this image. Others might structure things differently.

Either way, I just brought this up because I had to manually delete a bunch (I haven't wired up aws-ecr-gc myself yet) — fortunately, ECR let's you shift-click to select a group of images so it's actually not so burdensome to do every month or so, but still...

**Comment by lox** [comment]
Agreed that it would be a good feature. A PR would be welcomed, or I'll take a look at it when I get a chance!

**Comment by lox** [comment]
I looked into this a bit, one issue is that `aws-ecr-gc` works per-repository, so you'd need some way to pass a list of repositories to be garbage collected. 

I suspect this might be a better fit for https://github.com/buildkite-plugins/docker-compose-buildkite-plugin?

**Comment by bjeanes** [comment]
@lox Hmm... maybe? It's pretty AWS specific, but I don't have a good mental map of how the projects fit together.

**Comment by lox** [comment]
I agree it's AWS specific, which makes it slightly gnarly to figure out where it fits. The thing that creates those tags is however the docker-compose plugin, so it's in a position to know what can be garbage collected. The downside would be that it would have to be in a build step, rather than asynchronous.

https://github.com/buildkite-plugins/docker-compose-buildkite-plugin/issues/15

**Comment by lox** [comment]
At a minimum, we should install the binary on the stack.

**Comment by toolmantim** [comment]
If this were to live in the elastic stack, you could add stack parameters for "ECR Cleanup" which allowed them to specify a repository, and image pattern.

**Comment by bjeanes** [comment]
Except the repository isn't likely to be the same stack wide. It could be project-specific.

**Comment by bjeanes** [comment]
> At a minimum, we should install the binary on the stack.

Agreed. Then either the docker-compose plugin or a separate plugin could be used to add the requisite hooks.

**Comment by lox** [comment]
Given there is now ECR lifecycle events for removing old images, I'm going to close this one. @bjeanes, feel free to re-open otherwise.
