### ISSUE TITLE
If minimum agents is set to zero, and builds enqueue, a second one spins up before the first starts

### ISSUE THREAD

**Issue by thewoolleyman** [buildkite/elastic-ci-stack-for-aws#273]
I had to tweak the AWS elastic stack params a little bit, I had to up the "quiet" time to wait with a non-empty queue before spinning up an additional worker from 2 minutes to a 6, otherwise it would start a second one before the first one was spun up.  Most people who always keep 1 running probably don't notice, but I had it set to spin down to zero so I wouldn't get charged after hours.  Here's some notes on what I did exactly: https://github.com/thewoolleyman/continuous-everything/blame/5a66bb218a2230a36513171ceff0f9e9195ed55f/README.md#L39

**Comment by lox** [comment]
This is addressed in https://github.com/buildkite/elastic-ci-stack-for-aws/pull/274

**Comment by lox** [comment]
Fixed in master.
