### ISSUE TITLE
Install latest version of aws-cli

### ISSUE THREAD

**Issue by dalberto** [buildkite/elastic-ci-stack-for-aws#277]
I'm opening this issue to follow up on a discussion on slack and to bring visibility to this potential enhancement.

I found that the bundled version of aws-cli is a bit outdated. Currently, Amazon Linux 2017.3 uses aws-cli [1.11.29](https://github.com/aws/aws-cli/releases/tag/1.11.29), tagged December 14th, 2016. I encountered an incompatibility with the [retagging](https://docs.aws.amazon.com/AmazonECR/latest/userguide/retag-aws-cli.html) in the ECR API.

In order to minimize API incompatibility, I believe it makes sense to simply install the latest version of aws-cli in the image instead of relying on the bundled version.

**Comment by lox** [comment]
Check out #278!
