### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by lox** [buildkite/elastic-ci-stack-for-aws#286]
Would be great to get support for Windows AMI's to support Windows builds. 

This would require:

 - Adding a parameter for switching between windows / linux builds
 - Build a Windows AMI in parallel to the linux one (plus all the scripts)
 - Port lifecycle monitoring scripts to windows or golang

**Comment by ozbillwang** [comment]
Thanks, that will be better to have one CFN template to cover both windows and linux systems. 

I need autoscaling, schedule scaling, spot instances or not, cloudwatch logs/alarms, etc.

**Comment by lox** [comment]
It would be quite a big piece of work @ozbillwang!

**Comment by ozbillwang** [comment]
I can contribute my time if required.

**Comment by ozbillwang** [comment]
Another feature is, can we support Docker in this windows ami?

**Comment by lox** [comment]
What version of windows would you expect?

**Comment by lox** [comment]
https://aws.amazon.com/blogs/aws/run-windows-server-2016-on-amazon-ec2/ seems like a pretty good bet.

**Comment by ozbillwang** [comment]
Do we need any GUI in windows? Can we have `Server Core` only?

**Comment by ozbillwang** [comment]
And how about to install `docker for windows` as well? Otherwise, we can only pull/run windows containers.

**Comment by lox** [comment]
Basically it should be at parity with the linux stuff. I'd be pretty tempted to try and put Ubuntu for Windows on it so that the bash scripts don't need to be ported.

**Comment by ozbillwang** [comment]
@lox 

Not sure if you are working on this. Start preparing the `packer` template for windows. Hope we don't work on the same case.

I made a windows template (https://github.com/BWITS/elastic-ci-stack-for-aws/blob/windows_support/packer/buildkite-ami.json) in my fork (https://github.com/BWITS/elastic-ci-stack-for-aws/commit/1dfcd9fe6ae6f9c5d3a68d6be3cdbb9a9c678eb4)  as stage 1

- build from AMI image `Windows_Server-2016-English-Full-Containers-2017.05.10`
- install chocolatey
- use chocolatey to install 7zip, git, later we can add more applications. If you can package buildkite via chocolatey, that will be simpler as well. 

Please take a look.

**Comment by ozbillwang** [comment]
@lox 

What I will do:

1. Set packer template for windows AMI
2. Set AWS CFN templates base on windows AMI

I need your decision on how to organize the files to for linux/windows. We should use same CFN templates as below.  

```
autoscale.yml
description.yml
metrics.yml
outputs.yml
vpc.yml
```
and only customize different `buildkite-elastic.yml` for linux or windows, such as `buildkite-elastic-windows.yml` and `buildkite-elastic.yml`?

**Comment by lox** [comment]
I left some comments in https://github.com/buildkite/elastic-ci-stack-for-aws/pull/289!

**Comment by lox** [comment]
Moving this to https://github.com/buildkite/windows-elastic-ci-stack-for-aws!
