### ISSUE TITLE
Example for setting secrets in the secret bucket

### ISSUE THREAD

**Issue by andrewoh531** [buildkite/elastic-ci-stack-for-aws#292]
I was wondering if there's a gist, documentation or an example for the S3 object to set environment variables. Is it a key/value pair with the object name being the key name or just a `ENV_NAME=ENV_VALUE` in a text file? Was hoping there'd be something to reference rather than figuring it out via trial and error.

Thanks

**Comment by gugahoi** [comment]
It is a bash script named `env` where you can `export SOME_VAR=value`

**Comment by andrewoh531** [comment]
Thanks got it working.

There might be scope to clarify the README. Perhaps you can change `path` in `The following paths in the bucket are checked`  to `file` or `s3 object`.

**Comment by lox** [comment]
How does https://github.com/buildkite/elastic-ci-stack-for-aws/pull/294 sound?

**Comment by andrewoh531** [comment]
Looks good but question around name of the file (`myenv` vs `env`).

Thanks!

**Comment by lox** [comment]
It's `myenv` locally and then `env` when uploaded.

**Comment by andrewoh531** [comment]
Thanks @lox!
