### ISSUE TITLE
Builds waiting due to concurrency lead to spawning of new instances

### ISSUE THREAD

**Issue by legalosLOTR** [buildkite/elastic-ci-stack-for-aws#305]
I have a pipeline where only one build runs at a time due to concurrency. This means there are always waiting builds in this pipeline. The elastic-ci-stack sees "scheduledJobs > 0" and starts spawning new machines. This leads to us running a lot more machines than we need to.

**Comment by lox** [comment]
This is fixed in v3.x and up of the Elastic Stack.
