### ISSUE TITLE
Availability zones limited to 2

### ISSUE THREAD

**Issue by tspacek** [buildkite/elastic-ci-stack-for-aws#311]
If I specify three AZs, it only uses two of them.

Steps:
- Create a new stack
- Specify `ap-southeast-2a, ap-southeast-2b, ap-southeast-2c` as the AZs. Leave VPCs, Subnets etc blank.

Expected:
- The auto scaler's AZs to be `ap-southeast-2a, ap-southeast-2b, ap-southeast-2c`

What happens:
- The auto scaler's AZs are `ap-southeast-2a, ap-southeast-2b`

It looks like the Cloudformation template only creates two subnets.

N. Virginia has 5 AZs

**Comment by tspacek** [comment]
Cross ref: https://github.com/buildkite/elastic-ci-stack-for-aws/pull/157

I think a documentation change would do, to make clear in the Cloudformation params that it only takes two.

**Comment by lox** [comment]
Sorry for the late response! Yup, I think a docs change is the best way to move forward.

**Comment by lox** [comment]
This is fixed in #360.
