### ISSUE TITLE
Support encrypted EBS volumes

### ISSUE THREAD

**Issue by ineffyble** [buildkite/elastic-ci-stack-for-aws#318]
It would be a neat security boost if the stack had an option to enable [EBS encryption](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSEncryption.html).

This would need to be optional, as it limits the instance types you can use with the volumes.

**Comment by lox** [comment]
Sounds sensible, would happily review a PR @ineffyble :)
