### ISSUE TITLE
Scale up/down based on utilization instead of UnfinishedJobsCount

### ISSUE THREAD

**Issue by joshma** [buildkite/elastic-ci-stack-for-aws#322]
(I left a slack message, but wanted to surface here as well.)

Can we consider switching the scale up/down metric based on utilization, e.g. percentage or count of idle agents? The main issue with `UnfinishedJobsCount == 0` is that it only triggers if agents complete **all jobs**, so if our cluster is always running 1 job, then our agents never scale down.

On the other hand, scale up happens if `ScheduledJobsCount > 0`, so during the course of a day, load picks up, jobs are scheduled and not processed quickly enough, and we hit the max cluster size. Jobs get completed, and the queue is empty at times, but instances are often running at least one job, so the cluster never scales down.

If the answer is "add your own alarms", that's fine too, it just didn't seem kosher given we're managing the rest via CloudFormation.

**Comment by lox** [comment]
The difficult part is that there are often more agents then there are hosts, so idle agents needs to be divided by agents per host to be useful. 

I'd absolutely be interested in tweaking this so it's more useful, the other option I've been thinking about is the new Target tracking for Autoscaling: https://aws.amazon.com/blogs/aws/new-target-tracking-policies-for-ec2-auto-scaling/. 

We could possibly add in a scaling rule for CPU utilization by host too?

**Comment by joshma** [comment]
Hm interesting - looks like target tracking is limited to ALB requests, CPU, and network in/out. CPU utilization by host (through target tracking or old school) could work well for us. I'm assuming most folks' jobs are CPU-bound? It might be weird if there's a cluster e.g. waiting for cloudformation templates to apply and that causes scaledown.

Is it actually true that we'd need to divide agents by host? Haven't thought about this too carefully, but terminating an idle host would lower the total number of agents, regardless of how many agents are on it, thus decreasing the % of idle agents (for a fixed number of active agents).

Is there a way for us to test this? I'm finding that cloudwatch doesn't let us do an alarm on `X / Y`, could the lambda function be updated to emit `BusyAgentCount / TotalAgentCount`?

**Comment by joshma** [comment]
For what it's worth, I'm currently using the target tracking on CPU - set it to 50% arbitrarily:

![dd](https://user-images.githubusercontent.com/64739/30242780-ab14a8a4-9551-11e7-8537-eedea9f408af.png)

Graph shows active agents (dark) vs total agents - note the change in behavior after Wednesday, where it drops in agents even as the number of active agents is nonzero. (Wednesday was particularly bad - it stayed at 100 agents, our cap, until the end of the day even though many of them were idle.)

I'm going to experiment with bumping 50% up to 75% - the target tracking isn't as fast as I'd like, but it's reasonable (unfortunately I don't have stats on queue delays). Bumping CPU target up will lower the excess at the top of the graph.

**Comment by joshma** [comment]
Oops accidentally closed.

**Comment by toolmantim** [comment]
The autoscaling we have errs on the side of making agents available (to make sure people aren't waiting for builds) and general, at the cost of it being a bit wasteful… like you've noticed.

> I'm assuming most folks' jobs are CPU-bound

That's a big assumption we can't really make, but having a "Choose what makes sense" approach to the CF template isn't a bad idea! I just wish AWS gave you more fields to be able to customize that.

In the meantime, using your own alarms like you have, is a great way of testing it out. I think you can target track on other metrics too yeah, but they're "per-instance"… so it'd need to be an "active-jobs-per-instance" type metric, or "queued-jobs-per-instance".

**Comment by lox** [comment]
Closing this now we have better auto-scaling via the new lambda scaler.
