### ISSUE TITLE
“latest” version is not the “latest stable” version

### ISSUE THREAD

**Issue by ticky** [buildkite/elastic-ci-stack-for-aws#332]
<https://s3.amazonaws.com/buildkite-aws-stack/aws-stack.json> currently points at v2.2.0-rc4, not v2.1.5 as the releases page would suggest is the latest stable version

**Comment by lox** [comment]
Related to https://github.com/buildkite/elastic-ci-stack-for-aws/pull/327.

**Comment by lox** [comment]
I've ported 133ce0cfd94b91a7bce1e573e106512b04b11bb8 which was on the v2.1.x branch. It's basically a documentation change that now points to https://s3.amazonaws.com/buildkite-aws-stack/latest/aws-stack.json which is the latest stable release. The aforementioned url will continue to include RC's unless someone has a compelling reason to change that.
