### ISSUE TITLE
CloudWatch Logs Not Namespaced

### ISSUE THREAD

**Issue by s01ipsist** [buildkite/elastic-ci-stack-for-aws#342]
![image](https://user-images.githubusercontent.com/13267/30253724-715d115e-96ce-11e7-93a5-ae66a87481d0.png)

We use CloudWatch Logs for a variety of applications, not just BuildKite CI. It would be ideal if the BuildKite logs used a `/buildkite` (configurable, or default empty for backwards compatibility) Log Group prefix in order to:

- enhance readability and maintainability
- allow prefix based IAM permissions for developers

For example AWS CodeBuild uses the `/aws/codebuild` prefix for Log Groups.

**Comment by lox** [comment]
Makes a lot of sense! Will do. Whilst we are there, any other thoughts on how those logs are grouped?

**Comment by s01ipsist** [comment]
Nope. We haven't had cause to actually inspect those logs yet; stuff just works... 👏 👏
