### ISSUE TITLE
Saving caches between builds

### ISSUE THREAD

**Issue by dreyks** [buildkite/elastic-ci-stack-for-aws#352]
Don't know if this is the right place to ask, but is there a way to store caches between builds like heroku or circleci does, i.e. Rails precompiled assets. I know that docker has its own caching, but this layer's cache is always busted because of the app code change

**Comment by dblandin** [comment]
We use buildkite artifact uploading/downloading to share built assets between jobs within the same build, but unfortunately global artifacts between builds aren't yet supported.

Until then, I think you should be able to use S3 to share assets between builds. Something like this might work for you:

```
aws configure set default.s3.max_concurrent_requests 20
aws s3 sync s3://ci-app-assets ./public

docker-compose run \
  -e RAILS_ENV=production \
  -e RAILS_GROUPS=assets \
  -ASSET_HOST \
  --rm \
  --volume /tmp:/tmp \
  --volume "$PWD/public/assets":/app/public/assets \
  app bundle exec rake \
    assets:precompile \
    assets:clean

aws s3 sync --delete ./public s3://ci-app-assets
```

**Comment by dreyks** [comment]
thanks. I think the `tmp/cache/assets` folder needs to be synced too, but I get the idea

**Comment by lox** [comment]
Closing this in favour of a caching plugin.

**Comment by edify42** [comment]
Anyone here tried this? https://github.com/danthorpe/cache-buildkite-plugin

**Comment by julianD77** [comment]
@edify42 bit late, but adding in case still relevant for you or others. I have had more success with this plugin, specifically using the `rsync` method. It has been more recently updated and is actually based on that one you mention: https://github.com/gencer/cache-buildkite-plugin
