### ISSUE TITLE
SQS queues not being cleaned up by lifecycled

### ISSUE THREAD

**Issue by peter-stc** [buildkite/elastic-ci-stack-for-aws#358]
When starting a new buildkite agent instance, lifecycled automatically creates a SQS queue for the instance (https://github.com/lox/lifecycled/blob/master/main.go#L71)

The plan is for lifecycled to remove the queue upon receiving SIGTERM (when the instances shuts down) (https://github.com/lox/lifecycled/blob/master/main.go#L77-L90)

The problem is that lifecycled gets a SIGPIPE instead, thus not cleaning up after itself.
Seems like the problem is that `stderr` is being redirected to `stdout` and piped to syslog.

```
Nov 27 15:21:34 ip-10-0-1-241 lifecycled: time="2017-11-27T15:21:34Z" level=info msg="Looking up instance id from metadata service"
Nov 27 15:21:35 ip-10-0-1-241 lifecycled: time="2017-11-27T15:21:35Z" level=info msg="Listening for lifecycle notifications"
Nov 27 15:21:49 ip-10-0-1-241 init: lifecycled main process (27036) killed by PIPE signal
```

We've been able to get it to work by just redirecing `stdout`, but since lifecycled logs to `stderr` by default we won't get any logs. Unsure if the problem lies within lifecycled or the configuration for upstart.

```
start on startup
respawn
respawn limit unlimited
post-stop exec sleep 65
script
    set -a
    . /etc/lifecycled
    mkfifo /tmp/lifecycled-log-fifo
    ( logger -t lifecycled </tmp/lifecycled-log-fifo & )
    exec >/tmp/lifecycled-log-fifo
    #exec 2>&1
    rm /tmp/lifecycled-log-fifo
    exec /usr/bin/lifecycled
end script
```

**Comment by lox** [comment]
Thanks for the detailed report, and sorry for the radio silence! We've been hoping to entirely replace `lifecycled` with a lambda that centralizes lifecycle management for the entire ASG. If that doesn't get progressed soon I will investigate this issue in some more detail.

**Comment by tonglil** [comment]
Dang, this seemed like it would solve my problems. But if it's going to be abandoned then I'll keep looking I guess.

**Comment by lox** [comment]
We've had a few reports of this and a replacement for lifecycled is a fair way off, so we'll have a look at what we can do to fix this! Thanks for the patience folks.

**Comment by lox** [comment]
I've made some updates to lifecycled (https://github.com/lox/lifecycled/commit/3c5ede2316609d4bea827c7bf912b97601ddb60d) that I'm hoping will at a minimum band-aid over this issue. Will get our a release soon.

**Comment by lox** [comment]
In the meantime, something like this would delete ligecycled SQS queues:

```bash
#!/bin/bash
set -euo pipefail

instances=($(aws ec2 describe-instances \
  --filters "Name=tag:Role,Values=buildkite-agent" "Name=instance-state-name,Values=running" \
  --query 'Reservations[*].Instances[*].InstanceId' \
  --output text))

for queue in $(aws sqs list-queues \
  --queue-name-prefix "lifecycled" \
  --query 'QueueUrls[*]' \
  --output text) ; do

  running=0
  for i in "${instances[@]}" ; do
    queue_instance=$(echo "$queue" | cut -d/ -f5 | sed 's/^lifecycled-//' )
    if [[ "$queue_instance" == "$i" ]] ; then
      running=1
    fi
  done

  if [[ $running == 0 ]] ; then
    aws sqs delete-queue --queue-url "$queue"
  fi
done
```

**Comment by ritchiey** [comment]
We've got the same issue (just got a warning from AWS about our SQS usage). This seems to be deleting the queues. Just needed to set our default region to be where our Elastic stack is.

**Comment by lox** [comment]
@ritchiey what was the warning about?

**Comment by ritchiey** [comment]
Exceeding 85% of our free usage tier for SQS. I think we actually exceeded 1,000,000 messages so there's $0.40c we'll never get back.

**Comment by roblugton** [comment]
Which version of elastic stack is this fix in?

**Comment by lox** [comment]
It isn't yet @roblugton!

**Comment by meganemura** [comment]
@lox 

Same here :sob:

This cleanup script works great.
https://github.com/buildkite/elastic-ci-stack-for-aws/issues/358#issuecomment-378453577

Is there any script for cleaning up SNS topics?

**Comment by lox** [comment]
We created a tool for cleaning up SQS queues: https://github.com/buildkite/lifecycled#cleaning-up-leftover-sqs-queues

@meganemura there shouldn't be multiple SNS topics?

**Comment by Urahara** [comment]
@lox I still facing this problem. :/

![Captura de tela em 2019-05-06 09-36-59](https://user-images.githubusercontent.com/1462548/57226233-eb27ee00-6fe4-11e9-9229-3660a04719fa.png)

**Comment by pauldraper** [comment]
I don't have Go installed, but I do have the AWS CLI.

```sh
aws sqs --output text --query 'QueueUrls' list-queues | tr '\t' '\n' | xargs -L1 aws sqs delete-queue --queue-url```

**Comment by lox** [comment]
What stack version are you using @Urahara and @pauldraper?

**Comment by pauldraper** [comment]
@lox I'm using the Lambda scheduler now.

But looks like the last queue was created on 2019-04-23, and at that time I was using v4.0.0-rc2.

**Comment by Urahara** [comment]
@lox I'm using `3.0.1` version, is there anything more i can provide to you?

**Comment by lox** [comment]
This was fixed in the 4.x series.
