### ISSUE TITLE
Too much data being sent to cloudwatch logs

### ISSUE THREAD

**Issue by legalosLOTR** [buildkite/elastic-ci-stack-for-aws#396]
We recently upgraded to Elastic-stack 2.3.5 and seems like the amount of data being sent to cloudwatch logs drastically increased with this update. We run 30ish machines (4 agents per machine) and we have accumulated a few gigs of logs over the last few days.

We never check these logs (didn't even know they existed). Is there a way to opt-out of this logging? I would like to avoid paying cloudwatch charges.

**Comment by lox** [comment]
That's no good! What's in the logs? Perhaps we can filter it down.

**Comment by legalosLOTR** [comment]
The biggest ones are:
- `/buildkite/docker-daemon` and `/var/log/docker`: Both contain logs at level=debug and lots of iptables stuff like `time="2018-03-16T23:16:17.075813447Z" level=debug msg="/sbin/iptables, [-t filter -C DOCKER-ISOLATION -i br-bd5efbc42f31 -o br-a383a705445a -j DROP]"`
- The buildkite lambda functions are also logging a significant amount of data. Stuff like `2018-03-16T23:52:03.986Z	06d2ca04-2975-11e8-a95c-bd66763be9bf	Skipping agent, doesn't match queue filter deploy`

We'd prefer if there was a config option in the stack template to turn down the log level or select which one of these we want or maybe even a wholesale opt-out for cloudwatch logs.

**Comment by lox** [comment]
Thanks, odd that looks like docker debug logs. I'll check ours and see if we have the same and what costs ours incurs. I think a way to disable these logs would make sense.

**Comment by legalosLOTR** [comment]
Thank you!

**Comment by lox** [comment]
Doesn't look like we're sending docker debug logs, I might close this. Let me know if you are still seeing this.
