### ISSUE TITLE
`fix-buildkite-agent-builds-permissions` did not fix permissions :(

### ISSUE THREAD

**Issue by tduffield** [buildkite/elastic-ci-stack-for-aws#412]
I updated our cluster to 3.1.0 and tried to use the new `fix-buildkite-agents-builds-permissions` stuff. I saw in my logs that the script was executed, but I didn't see any output that it did anything. Subsequently, the job failed because the `git clean` could not remove files created inside the Docker Container.

**Comment by lox** [comment]
Oh no! Sorry it didn't fix things for you @tduffield  😞

Could you drop us a support email with a failing build that we can look at?
