### ISSUE TITLE
Clean up docker containers and network during global environment hook

### ISSUE THREAD

**Issue by arturopie** [buildkite/elastic-ci-stack-for-aws#420]
Sometimes our jobs fail when trying to create a new docker network. 

E.g.:

![image](https://user-images.githubusercontent.com/762752/40258687-66bd504a-5ac0-11e8-8d72-bc6709faaa2e.png)

This would be mitigated if we run a clean up for containers and network at the beginning of the job, when we do the disk clean up.

**Comment by lox** [comment]
Are you using the docker-compose plugin? I think that would be the best spot for this.

**Comment by arturopie** [comment]
@lox after more investigation, I'm closer to the root of the problem.

The docker-compose plugin seems to be properly cleaning up docker networks after a job is done, even when it fails. However, when a job is cancelled, I think the plugin doesn't get a chance to finish the clean up. 

Here is a screenshot of a failing build that properly cleaned up:

![image](https://user-images.githubusercontent.com/762752/40439359-b5bcf0da-5e88-11e8-9c7a-c8aa770ab4f3.png)

Here is a screenshot of a build that was cancelled, and according to the logs, it didn't remove the docker networks:

![image](https://user-images.githubusercontent.com/762752/40439466-01507d46-5e89-11e8-816e-52a67f28a97e.png)

Maybe the docker-compose plugin could do a better job at cleaning up, but I think the stack should also try to clean up, since the plugin won't be able to catch every situation. 

I see the stack has a daily cron job that is pruning networks and containers. Can we also do this clean up during the global environment hook? Same way we are doing for pruning images? I can open a PR with that change if you are ok with it.

**Comment by arturopie** [comment]
FYI, our current workaround is to run it in a local `pre-command` hook. Since we run many agents on the same machine, we sometime get `Error response from daemon: a prune operation is already running` errors. We might need some synchronization mechanism as well.

**Comment by lox** [comment]
@arturopie let's add it to the cron!

**Comment by arturopie** [comment]
The cron is doing it, it just needs to run hourly instead of daily for it to work for us.

See: https://github.com/buildkite/elastic-ci-stack-for-aws/blob/master/packer/conf/docker/cron.hourly/docker-gc#L13

and: https://github.com/buildkite/elastic-ci-stack-for-aws/blob/116fa54bb85615bd9cdc7cba75a378378db59e41/packer/scripts/install-docker.sh#L40

**Comment by lox** [comment]
Ah right. We come full circle. Ok, let's move them to hourly.

**Comment by arturopie** [comment]
@lox here you go #429
