### ISSUE TITLE
aws_cloudformation_stack indefinitely reapplies changes in NoEcho parameters

### ISSUE THREAD

**Issue by dblandin** [buildkite/elastic-ci-stack-for-aws#422]
I just ran into this issue using terraform to manage our Buildkite CloudFormation stacks:

https://github.com/terraform-providers/terraform-provider-aws/issues/55

This diff shows up indefinitely:

```
Terraform will perform the following actions:                                                                                                                 
  ~ module.buildkite.aws_cloudformation_stack.buildkite                                                                  
      parameters.BuildkiteAgentToken: "****" => "<redacted>"
```

My naive fix was to add this to my terraform config:

```hcl
lifecycle {
  ignore_changes = [
    "parameters.BuildkiteAgentToken",
  ]
}
```

but that results in writting `****` as the token value during stack updates, which prevents the agents from booting successfully given the invalid token.

I know Buildkite uses Terraform internally. Have you been able to work around this problem?

Thanks!

**Comment by lox** [comment]
This is a tricky one! Looks to be a gnarly Terraform bug. I'm not sure what to suggest, I think removing `NoEcho` would be a pretty bad decrease in practical security for non-terraform users.

**Comment by arturopie** [comment]
@dblandin we are using the naive fix, and we haven't found issues with it. We are using Terraform v0.11.7.

**Comment by dblandin** [comment]
@arturopie How do you handle terraform diffs that trigger a stack update vs create/destroy?

I've found that with the lifecycle, ignore_changes approach, I need to mark the resource as tainted after any paramater update in order to trigger the recreation of the stack so that the right token value is threaded through.

**Comment by arturopie** [comment]
@dblandin I see. We try to avoid stack updates, since we have ran into other issues with cloudformation stack updates. We treat it as an immutable resource. We destroy it and create it when we change it.

**Comment by lox** [comment]
I actually got the chance to talk to the engineers that maintain the aws integration for terraform. I mentioned this to them, they said it should be fixable and they will see what they can do.

**Comment by mixmatch** [comment]
Also, parameter values being sent to a NoEcho parameter should be marked as sensitive by the aws provider so they are not output in the terminal.

**Comment by pauldraper** [comment]
Yeah, this is a terraform issue.

**Comment by jradtilbrook** [comment]
FYI. PR #601 should resolve this once it is been tagged/released. You will need to change to using an SSM parameter instead so that the value isn't included in the template and instead the template refers to an SSM parameter path

**Comment by yob** [comment]
> I know Buildkite uses Terraform internally. Have you been able to work around this problem?

We use terraform internally, but note with our elastic stacks. Until today, when we ran into this issue as well.

Our short term workaround was a variation of the one proposed here:

```hcl
lifecycle {
  ignore_changes = [
    parameters["BuildkiteAgentToken"],
  ]
}
```

.. but we agree that's not ideal. We'd like to move to `BuildkiteAgentTokenParameterStorePath` described in https://github.com/buildkite/elastic-ci-stack-for-aws/pull/601

**Comment by jufemaiz** [comment]
Hi team, any idea if/when the next release might be tagged to get this going?

**Comment by mogggggg** [comment]
This would be great to have available, the output for this constantly updating resource in the latest version of Terraform is **very** verbose (1200+ lines 😱)

**Comment by nitrocode** [comment]
Since v5.0.0 has been released, we started using `BuildkiteAgentTokenParameterStorePath` instead of the `BuildkiteAgentToken` to get around this.

**Comment by yob** [comment]
We've also "fixed" this by using `BuildkiteAgentTokenParameterStorePath` instead of `BuildkiteAgentToken` on our `v5.0.0` stacks that are managed by terraform.

I think that's our recommended workaround now, so I'll close this. If there's a reason that workaround isn't viable in all situations, give a shout and we can re-open :heart:

**Comment by jufemaiz** [comment]
Can confirm it's a far better solution! Thanks team!
