### ISSUE TITLE
Upgrade Docker version to fix filesystem issue preventing files from being properly deleted

### ISSUE THREAD

**Issue by blueimp** [buildkite/elastic-ci-stack-for-aws#430]
The following filesystem issue is fixed in later Docker versions (still present on the provided version `17.12.1-ce-rc2`):
https://github.com/moby/moby/issues/37176

Please upgrade to a current version, if possible.

**Comment by lox** [comment]
Thanks, will bump to the latest stable docker release in the next stack version!

**Comment by lox** [comment]
This is updated in v3.3.0.
