### ISSUE TITLE
bk-check-disk-space.sh Error: return: can only `return' from a function or sourced script

### ISSUE THREAD

**Issue by arturopie** [buildkite/elastic-ci-stack-for-aws#432]
When `bk-dhcek-disk-space.sh` is ran as part of the `environment` hook. See https://github.com/buildkite/elastic-ci-stack-for-aws/blob/684ca4115ad4b15e38693aeaff42a296e80f6f96/packer/conf/buildkite-agent/hooks/environment#L20 it errors with the following message:

![image](https://user-images.githubusercontent.com/762752/40978035-938ac74a-68a0-11e8-90ff-4c158d82648e.png)

**Comment by lox** [comment]
Yup, you are totally correct, it should be `exit`. I'll either fix it when I get a chance, or would welcome PR's!

**Comment by arturopie** [comment]
@lox I opened a PR to fix this issue: #440
