### ISSUE TITLE
ASG AZRebalance kills jobs

### ISSUE THREAD

**Issue by raylu** [buildkite/elastic-ci-stack-for-aws#435]
The AZRebalance [process](https://docs.aws.amazon.com/autoscaling/ec2/userguide/as-suspend-resume-processes.html) kills jobs, especially if an agent machine is removed from the ASG for any reason. We don't benefit at all from having instances spread perfectly evenly across AZs and the act off rebalancing kills running jobs, so this is pretty much never desirable.

Unfortunately, there isn't an easy way to [use CF](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-as-group.html) to turn off AZRebalance.

**Comment by lox** [comment]
Interesting, have you seen this actually killing hosts? I've never encountered rebalancing like this in our stacks.

**Comment by raylu** [comment]
we see this all the time in our ASGs, including our buildkite one. one example is if some of our spot instances die due to there being no more spot instances available. another is if the underlying hardware for one dies, causing a system check failure

**Comment by arturopie** [comment]
We also see it, but only because we use spot instances. We implemented a system of exit codes so that buildkite only automatically retries 'infrastructure failures' and it won't automatically retry 'CI check failures'

**Comment by lox** [comment]
> We implemented a system of exit codes so that buildkite only automatically retries 'infrastructure failures' and it won't automatically retry 'CI check failures'

That was our intention with Automatic Retries @arturopie, specifically with a view to handle auto-scaling things. 

I'm not sure there is much we can do here @raylu, I think the only sound approach is to design things so that jobs being killed and interrupted is expected. I might close this one unless there is something actionable we can do, lemme know if I've got it wrong.

**Comment by tduffield** [comment]
@lox we just hit this ourselves. For us, the issue happened in our single-use queue (one agent per machine in the ASG) which was spread across three availability zones. It detected an imbalance and terminated instances upon which jobs were currently running. This scaling process seems to ignore whether or not a job is currently running on it.

**Comment by lox** [comment]
Are you using the new autoscaler lambda @tduffield?

**Comment by tduffield** [comment]
@lox we are. We think it has to something to do with the default/native configuration in AWS itself. We haven't dug too much into it.

**Comment by lox** [comment]
I reckon we could probably turn off `AZRebalance` in the lambda 🤔
