### ISSUE TITLE
Faster scale up from 0

### ISSUE THREAD

**Issue by pauldraper** [buildkite/elastic-ci-stack-for-aws#436]
Right now, it seems takes several minutes for the stack to even decide to launch the first EC2 instance.

Having some slack makes sense, but if there are literally 0 instances....it should start one immediately.

**Comment by lox** [comment]
Thanks @pauldraper, we REALLY want this too. It's amazingly difficult to get a general solution in place unfortunately, it's something I've been working on for years (depressingly). Stepped scaling (see https://github.com/buildkite/elastic-ci-stack-for-aws/issues/93) is hard to have custom min/max sizes for and percentage based scaling is really difficult to handle stacks that scale down to zero (which is really important for cost-saving). 

The plan currently is to use a custom Lambda to do the scaling. Keep an eye on https://github.com/buildkite/elastic-ci-stack-for-aws/pull/426.

**Comment by pauldraper** [comment]
@lox , interesting. Will do!

**Comment by lox** [comment]
Fixed via #554.
