### ISSUE TITLE
Document where templates/mappings.yml comes from

### ISSUE THREAD

**Issue by zsims** [buildkite/elastic-ci-stack-for-aws#445]
With a fresh (local) clone of this repo, `$ yarn install && yarn generate` will produce an invalid template as it's missing the `AWSRegion2AMI` mapping as referenced in the `templates/buildkite-elastic.yml` template:

https://github.com/buildkite/elastic-ci-stack-for-aws/blob/63a1fb0e1b3b00933becd5ad7f9a8a7d91780e9b/templates/buildkite-elastic.yml#L502

I've noticed there's some (missing) phony rules in Make that look like they'd download this:
https://github.com/buildkite/elastic-ci-stack-for-aws/blob/63a1fb0e1b3b00933becd5ad7f9a8a7d91780e9b/Makefile#L1

And the Buildkite tests generate a version of this file in CI:
https://github.com/buildkite/elastic-ci-stack-for-aws/blob/63a1fb0e1b3b00933becd5ad7f9a8a7d91780e9b/.buildkite/steps/test.sh#L73-L77

https://github.com/buildkite/elastic-ci-stack-for-aws/blob/63a1fb0e1b3b00933becd5ad7f9a8a7d91780e9b/.buildkite/steps/publish.sh#L132

Is there something I'm missing? `make update-stack` references the phony `download-mappings` dependency but it does nothing.

**Comment by lox** [comment]
Thanks, no you aren't missing anything, I think we broke this with a change at some point. I will investigate.

**Comment by lox** [comment]
This is fixed in master.
