### ISSUE TITLE
Default pre-command hook gives deprecation warning around DOCKER_LOGIN_PASSWORD

### ISSUE THREAD

**Issue by dominics** [buildkite/elastic-ci-stack-for-aws#457]
Upgraded to 4.0.0-rc1 on one of the stacks I look after. In our `env` script in the secrets bucket, we're setting a `DOCKER_LOGIN_PASSWORD`, and we're using the default pre-command hook. (https://github.com/buildkite/elastic-ci-stack-for-aws/blob/master/packer/conf/buildkite-agent/hooks/pre-command)

This seems to run into the deprecation at buildkite-plugins/docker-login-buildkite-plugin#20 because it passes the value as:

```
export BUILDKITE_PLUGIN_DOCKER_LOGIN_PASSWORD="$DOCKER_LOGIN_PASSWORD"
```

So, it gives the warning:

> :warn: The password property of the docker-login plugin has been deprecated, use password-env instead

I guess it should now pass:

```
export BUILDKITE_PLUGIN_DOCKER_LOGIN_PASSWORD_ENV="DOCKER_LOGIN_PASSWORD"
```

**Comment by lox** [comment]
This is fixed!
