### ISSUE TITLE
Enable SQS Encryption by default or have a flag for it

### ISSUE THREAD

**Issue by alikhan-io** [buildkite/elastic-ci-stack-for-aws#458]
Currently when buildkite creaes a lifecycled queue in SQS, it does not enable encryption by default. This is counter to best practices and ineivtably leads to tons of warnings with our security scanners that check for AWS best practices.

To remedy can we either have BK create queues with encryption by default or make it a flag where we can choose a KMS key to enable encryption?

**Comment by lox** [comment]
I'm going to close this as it's a `lifecycled` specific issue.
