### ISSUE TITLE
Missing some logs on 4.0.0-rc1

### ISSUE THREAD

**Issue by dominics** [buildkite/elastic-ci-stack-for-aws#459]
Instances built against the 4.0.0-rc1 version of the stack no longer manage to ship a couple of their logs into Cloudwatch (e.g. `/buildkite/docker-daemon`)

The failure seems to be in the local logging config on the instances, because in `/var/log/awslogs.log` we see:

```
2018-07-22 23:11:09,783 - cwlogs.push.stream - WARNING - 3618 - Thread-1 - No file is found with given path '/var/log/lifecycled'.
2018-07-22 23:11:14,784 - cwlogs.push.stream - WARNING - 3618 - Thread-1 - No file is found with given path '/var/log/docker'.
```

(And yep, those paths are actually missing.)

If I had to guess, this could be caused by the move to journald (systemd) in Amazon Linux 2. (`sudo journalctl -u docker.service` on an instance does show the Docker daemon logs)

**Comment by lox** [comment]
Excellent catch! Will have to investigate how to get these logs out of journald and into the awslogs daemon.
