### ISSUE TITLE
Instance Storage Support

### ISSUE THREAD

**Issue by chendo** [buildkite/elastic-ci-stack-for-aws#464]
I think we'd see a sizeable performance boost on IO-heavy builds if using Instance Storage was supported so we can use the NVME SSD instances (`c5d`, `m5d`).

**Comment by chendo** [comment]
Someone benched GP2 vs NVME here:

https://gist.github.com/ktheory/3c3616fca42a3716346b

Those synthetic benchmarks show NVME being 5-10x faster on throughput and could be potentially orders of magnitude faster in terms of latency and random IO.

**Comment by lox** [comment]
A few folks have sent over this article: https://pythonspeed.com/articles/slow-ci-aws-ec2

I'd be very keen to get something into the stack to do this. Historically, my concern was supporting all the weird and wonderful instance store configurations: https://pythonspeed.com/articles/slow-ci-aws-ec2

**Comment by lox** [comment]
I’m keen to get the script from https://stackoverflow.com/questions/10612440/script-to-format-and-mount-all-available-instance-store-devices in for a test!

**Comment by lox** [comment]
I wonder if the slower boot would make it worthwhile 🤔

**Comment by lox** [comment]
https://gist.github.com/joemiller/6049831

**Comment by joffotron** [comment]
As an aside for people wanting to solve the IO heavy build problem - Your mileage may vary, but we've tried provisioning instances with a big whack of RAM and then

```
echo 'none /var/lib/docker tmpfs size=8G' | sudo tee -a /etc/fstab >/dev/null
echo 'none /var/lib/buildkite-agent/builds tmpfs size=8G' | sudo tee -a /etc/fstab >/dev/null
```

in our AMI build scripts. As we treat these machines as 100% disposable anyway, we don't mind keeping everything in RAM.

It's early days so far, but we're seeing much faster builds. NVMe would be a nice (and a little less scary) option for many
