### ISSUE TITLE
Add an option to set the IAM of the instances

### ISSUE THREAD

**Issue by mikekap** [buildkite/elastic-ci-stack-for-aws#47]
Or some other way to give the machines extra IAM permissions that the builds may need.

**Comment by lox** [comment]
You can specify an external security group when creating the stack, you can attach IAM permissions to that if need be. 

Our tendency at 99designs is to avoid customizing the stack and instead use a IAM keypair in the encrypted secrets that are available to each pipeline that uses the stack.

**Comment by lox** [comment]
I'm going to close this, let me know if the above doesn't help.

**Comment by exidy** [comment]
Hey lox,

What do you mean by "you can attach IAM permissions to that [security group]"? I wasn't aware of any such capability and I can't see any reference to it in the documentation. AFAIK, you can attach a policy to an IAM group, but not a security group.

I think it would be useful to be able to specify additional IAM policies for the agents. For example, using packer is a very common task for an agent and requires a certain set of IAM permissions. Instance roles are more secure than static credentials, even if said credentials are encrypted and are AWS's recommended way to empower instances to perform certain actions.

**Comment by lox** [comment]
Yup, you are correct @exidy, I was getting mixed up. As you say, security groups are for firewall rules, and what you and @mikekap want is IAM capabilities for the instance. Re-opening this and tagging it as a feature enhancement. I'd probably be inclined to do this by allowing a custom IAM Role to be specified as a stack parameter and then conditionally used in https://github.com/buildkite/elastic-ci-stack-for-aws/blob/master/templates/buildkite-elastic.yml#L211. Happy to accept a PR if you feel so inclined.

**Comment by exidy** [comment]
Thanks @lox. I'd be happy to take a crack at this.

**Comment by toolmantim** [comment]
I just had to do this to, but I added the policy to the agent machines by modifying the role that the stack was created (using inline policies so it can easily be replaced/deleted), but that's not sustainable.
