### ISSUE TITLE
Finish git-lfs install

### ISSUE THREAD

**Issue by pauldraper** [buildkite/elastic-ci-stack-for-aws#490]
Currently, for git lfs to work (added in #468), the user must add to their bootstrap script

```sh
su buildkite-agent -l -c 'git lfs install'
```
(This command adds the necessary hooks to ~/.gitconfig.)

**Comment by lox** [comment]
Odd, I thought this was covered in the install already! I wonder if this is something we should do by default?

**Comment by keithduncan** [comment]
Thank you for this report @pauldraper! Sorry this was so long coming but I have added this in #912 for packaging in our next release 🎉  We appreciate you taking the time to help us improve our product :bow:
