### ISSUE TITLE
Missing mappings for AWSRegion2AMI in stable-3-2 and stable-3-3

### ISSUE THREAD

**Issue by robsweet** [buildkite/elastic-ci-stack-for-aws#491]
Hi!

Our deployments happen in us-west-2 and I noticed that whatever generated https://s3.amazonaws.com/buildkite-aws-stack/stable-3-2/aws-stack.json is only putting in mappings for AWSRegion2AMI for the us-east-1 region.  In contrast, https://s3.amazonaws.com/buildkite-aws-stack/v3.3.1/aws-stack.json has most or all of the regions in that mapping.  It seems like we're better off using stable-3-3 so we get small fixes but we can't do that without a more complete mapping.

**Comment by lox** [comment]
We're just preparing for a v3.3.1 release, which will have AMI's in all regions. It takes about 10 minutes to copy them across all regions, so we don't do that for CI runs on branches. 

Sounds like we perhaps need a release channel for major versions and minor versions? The `stable-x-x` convention is really just an internal development detail, vs something we'd considered as a stable API.

**Comment by robsweet** [comment]
That sounds great, @lox .  We didn't realize it wasn't meant to be used like we were.
