### ISSUE TITLE
Bump to docker 18.09

### ISSUE THREAD

**Issue by tekumara** [buildkite/elastic-ci-stack-for-aws#504]
Bumping to docker 18.09 would allow secrets to be securely passed to build contexts when running `docker build` on agents. It also has buildkit support.

More info here: https://medium.com/@tonistiigi/build-secrets-and-ssh-forwarding-in-docker-18-09-ae8161d066

**Comment by lox** [comment]
Hah, I just merged this in https://github.com/buildkite/elastic-ci-stack-for-aws/pull/505!

**Comment by lox** [comment]
I believe you will also need a mechanism to set the experimental flag for the docker daemon though!

**Comment by tekumara** [comment]
Wow, that's fast! Thankyou.
 🏎🏎🏎🏎🏎
