### ISSUE TITLE
Using existing IAM Role

### ISSUE THREAD

**Issue by themohammedali** [buildkite/elastic-ci-stack-for-aws#536]
Are there any plans to allows us to use existing IAM roles when creating stacks, this would really save a lot of effort transferring policies to new roles the stacks cloudformation creates?

 Thanks

**Comment by lox** [comment]
No plans, but sounds like an interesting idea that we’d welcome a PR for!

**Comment by nitrocode** [comment]
I'd like this feature a lot since our iam roles are tied to kms policies which need to be updated whenever we destroy iam roles or move queues to new iam roles.

To get around this issue were trying to make the buildkite queuename the stackname and the iam role so they are all consistent.

**Comment by nitrocode** [comment]
The current param `InstanceRoleName` is simply overwriting the IAM role name but for the IAM role to still be created by the stack so we cannot create a condition on this parameter.

I imagine it would have to be a new parameter like `ReuseIamRole=true` where you could create a condition that says to reuse the iam role passed in if this is set.

The issue with adding new inputs is that cloudformation has a bad limit of 60 input vars and the stack is currently at 57 iirc. What's a good way forward for this change ? @lox @yob

**Comment by nitrocode** [comment]
Scratch that. The 60 parameter limit has recently [been raised to 200](https://aws.amazon.com/about-aws/whats-new/2020/10/aws-cloudformation-now-supports-increased-limits-on-five-service-quotas/). I'll PR a new input parameter for the ability to reuse an existing role.

**Comment by keithduncan** [comment]
> Are there any plans to allows us to use existing IAM roles when creating stacks, this would really save a lot of effort transferring policies to new roles the stacks cloudformation creates?

This should be automatable today using the [`ManagedPolicyARN `](https://github.com/buildkite/elastic-ci-stack-for-aws/blob/441cd37c4170d515c5116f5d630cc68256beb3e4/templates/aws-stack.yml#L295-L298) parameter which accepts a list of IAM policies to [append](https://github.com/buildkite/elastic-ci-stack-for-aws/blob/441cd37c4170d515c5116f5d630cc68256beb3e4/templates/aws-stack.yml#L672-L689) to the role.

I’m going to close this as I believe we have an answer for the outcome you’re looking for without supporting fully replacing the Elastic CI Stack’s role (which would have to support and track the new IAM actions the stack itself needs access to as you update).

Let us know if this parameter isn’t sufficient for your use case and we can look into alternatives 🙇‍♂️

**Comment by nitrocode** [comment]
Appending an iam policy to a role managed by the stack is very different from reusing an existing role.

What if you have an existing iam role with inline policies or an existing iam role name conflict. Now you have to convert your inline iam policies to managed policies, delete the existing iam role, and only to allow the cf stack to unnecessarily manage the iam role? It doesn't make sense. It seems like a limitation that can easily be lifted IMHO.

**Comment by keithduncan** [comment]
> Appending an iam policy to a role managed by the stack is very different from reusing an existing role.

What if you were to provide assume-role permission into your fixed set of roles using a managed policy?
