### ISSUE TITLE
Missing lambda bucket in ca-central-1

### ISSUE THREAD

**Issue by lucas044** [buildkite/elastic-ci-stack-for-aws#543]
Hi all, any chance we could get a lambda bucket in ca-central-1?
I can't see it in the existing list.

In the mean time I'll be downloading the .zip myself. This would be nice to have.

**Comment by lox** [comment]
Will do!

**Comment by lox** [comment]
Finally got all the new regions in the latest agent metrics release, will get this in the stack soon.
