### ISSUE TITLE
Set no-color=true by default

### ISSUE THREAD

**Issue by themikenicholson** [buildkite/elastic-ci-stack-for-aws#556]
Cloudwatch logs appear to contain control colors by default.  This makes reading the logs in cloudwatch difficult along with any machine parsing of the logs.

`no-color=true` should probably be the default for the elastic-ci-stack AMI.

**Comment by lox** [comment]
Fixed in `master`.

**Comment by themikenicholson** [comment]
Any idea when the next release will come out?
