### ISSUE TITLE
Support for multiple Security Groups

### ISSUE THREAD

**Issue by dannykansas** [buildkite/elastic-ci-stack-for-aws#562]
I understand why `SecurityGroupId` is a `String` rather than a `CommaDelimitedList`, but I'd like to launch my stack with several SGs attached.

If this isn't on the radar, I'll probably get around to a PR at some point, but just wanted to check here first.

**Comment by lox** [comment]
We'd happily accept a PR for this.

**Comment by DoingItNow** [comment]
Any updates to whether it is on the radar to add in this capability?

**Comment by lox** [comment]
No specific plans @DoingItNow, would love to hear some more about your usecase though!

**Comment by DoingItNow** [comment]
We currently have two SGs for our buildkite agent, one that allows SSH access and one that needs access to an RDS we are using. Ideally we would like the SGs to be split rather than putting the port 22 and port 3306 rules into one SG

**Comment by dannykansas** [comment]
I'll probably be PRing this in the near future; we've worked out a hack-y
solution internally, but I can add a bit more rigor to it and benefit all.

Should have it by next week.

**Comment by lox** [comment]
Thanks @dannykansas! Looking forward to it!

**Comment by DoingItNow** [comment]
Yeah I did some workarounds to get multiple SGs working but I be happy to see a proper solution merged in soon!

**Comment by DoingItNow** [comment]
Any progress on this issue?
