### ISSUE TITLE
How can I enable datadog integration?

### ISSUE THREAD

**Issue by legalosLOTR** [buildkite/elastic-ci-stack-for-aws#567]
Just saw this post: https://forum.buildkite.community/t/about-our-datadog-integration/216
And wondering how I can enable the datadog integration for agents in our elastic stack.

**Comment by bradleyess** [comment]
I'm not sure this link will work for you too - but the metrics are available without any configuration inside of Datadog.

`buildkite.RunningJobsCount`
`buildkite.IdleAgentCount`
`buildkite.TotalAgentCount`
`buildkite.ScheduledJobsCount`
`buildkite.BusyAgentCount`
`buildkite.UnfinishedJobsCount`

https://app.datadoghq.com/metric/explorer?from_ts=1595314418695&to_ts=1595318018695&live=true&page=0&is_auto=false&tile_size=m&exp_metric=buildkite.RunningJobsCount%2Cbuildkite.IdleAgentCount%2Cbuildkite.TotalAgentCount%2Cbuildkite.ScheduledJobsCount%2Cbuildkite.BusyAgentCount%2Cbuildkite.UnfinishedJobsCount&exp_agg=avg&exp_row_type=metric

**Comment by Temikus** [comment]
@legalosLOTR the datadog integration sends the metrics to dogstatsd on localhost so I presume one needs to modify the startup scripts to install the agent on the machine you're running on.

**Comment by keithduncan** [comment]
@Temikus is correct, the [agent config options](https://github.com/buildkite/agent/blob/59a972094f4839facb4b63d26fda62ddebdf82fe/clicommand/agent_start.go#L401-L416) default to `localhost:8125`.

There are a couple of options for installing software on an Elastic CI Stack instance that might be applicable here.

First, you could use the [bootstrap script parameter](https://github.com/buildkite/elastic-ci-stack-for-aws#customizing-instances-with-a-bootstrap-script) in the Elastic CI Stack CloudFormation template to give your instances a script to execute on boot and install the Datadog agent in there. This is run on each instance when it is booted and may make your scaling less responsive depending on how long your script takes to execute, how reliable the remote resources you are installing, and what is acceptable to your use case.

The second option is to pre-install the Datadog agent in an AMI built on top of the published Elastic CI Stack AMI and provide that image to the template in the ImageId or ImageIdParameter parameters. This option requires more up front infrastructure to maintain but avoids the delay in instance boot associated with installing the software and is more reliable having fewer real time dependencies at boot time.

Let us know if you’d like more details on these options :slightly_smiling_face:
