### ISSUE TITLE
Cloudwatch metrics busted in 4.3.1 with lambda auto scaler

### ISSUE THREAD

**Issue by legalosLOTR** [buildkite/elastic-ci-stack-for-aws#568]
Just upgraded to 4.3.1 and enabled the lambda auto scaler. It's working great!
But the cloudwatch metrics seem busted:
- they are not namespaced by queue/pipeline.
- counts seem pretty off. It's saying total agents is 5 right now whereas the ASG shows 200 running.

**Comment by lox** [comment]
Sorry I missed this one, be aware that the lambda auto scaler only posts a subset of metrics. Check out the FAQ in https://forum.buildkite.community/t/experimental-lambda-based-scaler/425.
