### ISSUE TITLE
Query on whats installed [docker daemon]

### ISSUE THREAD

**Issue by shavo007** [buildkite/elastic-ci-stack-for-aws#570]
Hi,

rather than having docker daemon installed on each machine and needing root access, have you looked at kaniko from google?

It provides an executor to build container images inside a container running on a Kubernetes cluster. 

example of using kaniko and knative I read recently:

https://itnext.io/how-to-use-knative-to-automate-an-application-build-on-kubernetes-904034341f9f

**Comment by lox** [comment]
Yup, have been keeping a pretty close eye on that ecosystem. That would solve the container building part of the puzzle, but what about executing workloads in containers?

https://github.com/uber/makisu is also another one to keep an eye on.

**Comment by lox** [comment]
Rootless Buildkit (unrelated to Buildkite) is another thing to keep an eye on! https://medium.com/@tonistiigi/experimenting-with-rootless-docker-416c9ad8c0d6
