### ISSUE TITLE
AMI template error for ca-central-1 region

### ISSUE THREAD

**Issue by jmajonis** [buildkite/elastic-ci-stack-for-aws#574]
I'm trying to launch the stack in the ca-central-1 region via the link provided from buildkite.com.

https://console.aws.amazon.com/cloudformation/home#/stacks/new?stackName=buildkite&templateURL=https://s3.amazonaws.com/buildkite-aws-stack/aws-stack.json 

After entering information and trying to launch the stack I receive the error message: `Template error: Unable to get mapping for AWSRegion2AMI::ca-central-1::AMI`

Inspecting `aws-stack.json` I see on line 504 that AMI `ami-0e65b12703691e2e0` is defined for the ca-central-1 region. 
Searching community AMIs in ca-central-1 I see this AMI is available. 

I'm not very familiar with Cloudformation so am not sure if there's a problem with the stack template, or maybe I'm missing something. Any help would be appreciated. Thank you.

**Comment by lox** [comment]
Hi @jmajonis 👋🏻 Apologies, it looks like that link is outdated and is referring to the v3.x url of https://s3.amazonaws.com/buildkite-aws-stack/aws-stack.json. The v4 of the stack moved to a different URL format. 

Check out https://github.com/buildkite/elastic-ci-stack-for-aws#getting-started for the latest, which includes `ca-central-1`.

**Comment by harrietgrace** [comment]
I've updated the link on the Buildkite Agent AWS setup page to use the correct template. Thanks for pointing it out @jmajonis! I'm going to close this issue, but feel free to re-open if you're still running into the region problems.
