### ISSUE TITLE
Scale down based on idle workers, not number of scheduled jobs

### ISSUE THREAD

**Issue by bgentry** [buildkite/elastic-ci-stack-for-aws#58]
[Slack comment](https://buildkitechat.slack.com/archives/aws/p1462550386000739)

My understanding of the current scale down policy is that scaling down on `ScheduledJobsCount <= 0` means that even if all workers are 100% busy running jobs, that some may still get killed.

I'm thinking that makes more sense to tie scaling down to the # of idle agents (perhaps being above 0 for X number of minutes).

**Comment by lox** [comment]
The AWS recommendation is to use the same metric for scaling up and down to avoid livelock situations, this seemed like a simple approach when paired with the lifecycle events which will prevent running agents getting killed. I did change the time frame for the scale down event to be much longer, I'll run some more tests and see how it responds. Let's get #59 sorted and see how this current policy works.

**Comment by lox** [comment]
Well, I can't find any mention of aforementioned "AWS Recommendation", so I'm going to say I dreamed that.

**Comment by Vektah** [comment]
The current scale down behaviour is killing instances way too early:
![annotated-bk-scaledown](https://cloud.githubusercontent.com/assets/2247982/15594965/27cee984-23fe-11e6-9e52-9171d5fb29c7.png)

We changed to idle agents == 0 over last 6 minutes, repeating every 2:
![2016-05-27_1190x603](https://cloud.githubusercontent.com/assets/2247982/15595012/93c7c412-23fe-11e6-930f-7f19f4c79048.png)

Its probably still a bit aggressive scaling up, it would be nice if we could base both scale up and scale down on the percentage of busy agents

**Comment by lox** [comment]
Have we fixed this @toolmantim?

**Comment by toolmantim** [comment]
Yeah, but we solved it by changed to UnfinishedJobs
