### ISSUE TITLE
SpotOptions needs "persistent"?

### ISSUE THREAD

**Issue by ianwremmel** [buildkite/elastic-ci-stack-for-aws#599]
I think when SpotPrice is set, the spot request is defaulting to `one-time` instead of `persistent`. Once an instance is scaled out of the group, it never gets replaced.

https://docs.aws.amazon.com/en_us/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-launchtemplate-launchtemplatedata-instancemarketoptions-spotoptions.html

**Comment by lox** [comment]
Thanks @ianwremmel, what version of the stack are you using?

**Comment by ianwremmel** [comment]
I think it's `Description: "Buildkite stack v4.3.3"`. I've cobbled together a script via terraform and the "latest" url is the only url that I could find as working. 

https://s3.amazonaws.com/buildkite-aws-stack/latest/aws-stack.yml

**Comment by ianwremmel** [comment]
I suppose this *may* also be the underlying cause of #596

**Comment by lox** [comment]
That's very odd @ianwremmel, that template uses a LaunchConfiguration, not a LaunchTemplate 🤔 Are you sure you aren't using `master` somehow?

**Comment by lox** [comment]
Can you check what template was used to create the stack and confirm if you have a `LaunchConfiguration` or a `LaunchTemplate`?

**Comment by lox** [comment]
Beyond that, it shouldn't need to be persistent. The auto-scaling group manages that I believe. It has for years with the `LaunchConfiguration` at any rate.

**Comment by ianwremmel** [comment]
The relevant bits my terraform config are:

```hcl
variable "template_url" {
  default = "https://s3.amazonaws.com/buildkite-aws-stack/latest/aws-stack.yml"
}


resource "aws_cloudformation_stack" "this" {
  name = "buildkite-${var.buildkite_queue}"

  parameters = {
    # Buildkite Configuration

    BuildkiteAgentToken = "${var.buildkite_agent_token}"
    BuildkiteQueue      = "${var.buildkite_queue}"

    # Network Configuration

    VpcId   = "${var.vpc_id}"
    Subnets = "${var.subnet_ids}"

    # Instance Configuration

    ArtifactsBucket  = "${module.artifacts_bucket.name}"
    InstanceType     = "${var.instance_type}"
    KeyName          = "${aws_key_pair.this.key_name}"
    ManagedPolicyARN = "${join(",", var.managed_policy_arns)}"
    SecretsBucket    = "${module.secrets_bucket.name}"
    SpotPrice        = "${var.spot_price == "" ? null : "${var.spot_price}"}"

    # Autoscaling Configuration

    MaxSize             = "${var.max_size}"
    MinSize             = "${var.min_size}"
    ScaleCooldownPeriod = "${var.scale_cooldown_period}"
    ScaleDownAdjustment = "-${abs(var.scale_down_adjustment)}"
    ScaleDownPeriod     = "${var.scale_down_period}"
    ScaleUpAdjustment   = "${var.scale_up_adjustment}"

    # Docker Daemon Config

    EnableDockerUserNamespaceRemap = "${var.enable_docker_user_namespace_remap}"

    # Docker Registry Configuration

    ECRAccessPolicy = "${var.ecr_access_policy}"
  }

  template_url = "${var.template_url}"
  capabilities = ["CAPABILITY_IAM", "CAPABILITY_NAMED_IAM"]
  on_failure   = "ROLLBACK"
}
```

I've been finding that:
1. when I set a spot_price on multiple queues, only one queue can start agents
2. when I set a spot_price, agents aren't replaced when they're scaled down

As far as I can tell, I'm using a template with LaunchConfiguration rather than LaunchTemplate. I *think* https://s3.amazonaws.com/buildkite-aws-stack/latest/aws-stack.yml points at https://s3.amazonaws.com/buildkite-aws-stack/v4.3.3/aws-stack.yml, but I can try changing the url, now that I've figured out what the versioned url looks like.

**Comment by ianwremmel** [comment]
> Beyond that, it shouldn't need to be persistent.

Really? I keep seeing my spot request in the `fulfilled` state, which seems to indicate that it's never going to request more: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/spot-bid-status.html

**Comment by lox** [comment]
I believe the ASG uses multiple spot requests, rather than just one persistent one.

**Comment by lox** [comment]
I’m going to close this one, folks have been using this stack with spot instances for 3-4 years now, I reckon the problem will be somewhere else. Happy to help troubleshoot!

**Comment by ianwremmel** [comment]
@lox fair enough. What's the best way to troubleshoot? Open a support ticket?

Also, does #596 fall into the same category?

**Comment by lox** [comment]
Either hello@buildkite.com or jump into #aws-stack in https://chat.buildkite.community and I'll assist!

**Comment by ianwremmel** [comment]
great, thanks! It's still the weekend here, so probably nothing today, but I'll send something this week.

**Comment by ianwremmel** [comment]
Cross posting from #596

> So, I think I worked out what was happening here: it turns out AWS accounts have a limited spot instance count that they don't tell you about. As far as I can tell, I'm limited to roughly two spot instances, so it *appeared* that the first queue was the only one that could allocate spot instance, but it was simply that in my case, the first queue used up my quota.

Might be worth putting something in the docs about that. There error message is in a relatively obvious spot if you've spent a week digging through the EC2 console, but for newcomers to autoscaling and spot pricing, it's less intuitive. I stumbled up it mostly by accident last night.
