### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by juandiegopalomino** [buildkite/elastic-ci-stack-for-aws#604]
Hi there!

So we're really interested in the `disconnect-after-idle-timeout` flag capabilities, and it looks like that isn't in yet on the latest release (4.3.3). We've needed to be wary of long-running ec2 machines (it looks right now like they're only going down if all agents are idle at the same time) and ungracefully terminate them, so something like this would be fantastic. Is there any eta?

**Comment by lox** [comment]
Hi! The latest 4.3.3 release should have support for `disconnect-after-idle-timeout`. That flag will only disconnect when all agents are idle though.

Would love to hear more about why you're wary of long running machines, I'm not sure the idle timeout is designed to help with that per-se.

**Comment by lox** [comment]
https://github.com/buildkite/elastic-ci-stack-for-aws/releases/tag/v4.3.4
