### ISSUE TITLE
Docker Experimental mode broken

### ISSUE THREAD

**Issue by matclayton** [buildkite/elastic-ci-stack-for-aws#608]
I'm fairly sure that the following code is buggy, and we're seeing docker not boot up when experimental mode is enabled

```cat <<< "$(jq '.experimental="buildkite-agent"' /etc/docker/daemon.json)" > /etc/docker/daemon.json```

Is causing docker to not boot up, shouldn't this set experimental to true?

**Comment by lox** [comment]
Oops! Yes you are absolutely correct. Will get a patch out soon!

**Comment by matclayton** [comment]
Amazing :) any chance of releasing the docker 19.03 version as well? We’d love to get BuildKit and the agent dag pipeline stuff as well. We’re really trying to reduce our build times and these three thing combined should shave off a considerable amount of it.

**Comment by benesch** [comment]
I'm seeing a slightly different problem. It's getting set to `"true"` since https://github.com/buildkite/elastic-ci-stack-for-aws/commit/a5adc68d5bcf1513b21a4933aeaeb3a965ab13db, but needs to be set to `true` (the boolean, not the string).

**Comment by lox** [comment]
Ugh, you are completely correct too @benesch 🤦🏼‍♂️

I'll fix this in the stable release and master.

**Comment by lox** [comment]
Fixed in `master` and also https://github.com/buildkite/elastic-ci-stack-for-aws/releases/tag/v4.3.4

**Comment by benesch** [comment]
Oh wow, thanks for the fix on a Saturday!
