### ISSUE TITLE
Missing me-south-1 region

### ISSUE THREAD

**Issue by jozefvaclavik** [buildkite/elastic-ci-stack-for-aws#617]
If you try to lauch stack in Bahrain region, it fails with 

`Template error: Unable to get mapping for AWSRegion2AMI::me-south-1::AMI`

**Comment by lox** [comment]
I didn't even know `me-south-1` existed! We'll look at adding it.

**Comment by jozefvaclavik** [comment]
Any update on this?

**Comment by yob** [comment]
Fixed in #718 and available from 5.0.0.beta1
