### ISSUE TITLE
TimeoutStopSec=infinity broke ExecStopPost in buildkite-agent systemd service

### ISSUE THREAD

**Issue by jeremiahsnapp** [buildkite/elastic-ci-stack-for-aws#629]
The change made in https://github.com/buildkite/elastic-ci-stack-for-aws/pull/622 needs to be reverted. `TimeoutStopSec=infinity` is not a valid value for systemd v219 which is the version used in Amazon Linux 2.

We tried to use the latest linux AMI but it is broken. When the buildkite-agent service is finished it should stop itself and the `ExecStopPost` commands should run to mark the instance unhealthy and shutdown the instance. As you can see in the logs below the buildkite-agent process stops properly but the `stop-post` phase which runs `/usr/local/bin/terminate-instance` is `timed out` immediately so a `SIGTERM` is sent to it. Then that `stop-final-sigterm` is `timed out` immediately so a `SIGKILL` is sent to it resulting in the `buildkite-agent.service entered failed state`. Systemd sees the failed state so it recovers the state by restarting the service. We don't want systemd to recover the state though, especially if the instance was configured to run only a single job and then terminate the instance.

```
buildkite-agent[5787]: 2019-09-10 14:01:46 INFO   dev-buildkite-i-0dcc2bb6ec5bfceb2-1 Job finished. Disconnecting...
buildkite-agent[5787]: 2019-09-10 14:01:46 INFO   dev-buildkite-i-0dcc2bb6ec5bfceb2-1 Disconnecting...
systemd[1]: buildkite-agent.service stop-post timed out. Terminating.
systemd[1]: buildkite-agent.service stop-final-sigterm timed out. Killing.
systemd[1]: Unit buildkite-agent.service entered failed state.
systemd[1]: buildkite-agent.service failed.
systemd[1]: buildkite-agent.service holdoff time over, scheduling restart.
systemd[1]: Started Buildkite Agent.
```

I've done some testing and determined that setting `TimeoutStopSec=infinity` simply doesn't do what you'd expect it to do for the version of systemd installed in Amazon Linux 2. Amazon Linux 2 uses systemd v219 which expects you to set `TimeoutStopSec=0` if you want to disable the timeout as you can see in this section from `man systemd.service`.

```
       TimeoutStopSec=
           Configures the time to wait for stop. If a service is asked to stop, but does not terminate in the specified time, it will be terminated forcibly via SIGTERM, and after another timeout of equal duration with SIGKILL (see KillMode= in systemd.kill(5)).
           Takes a unit-less value in seconds, or a time span value such as "5min 20s". Pass "0" to disable the timeout logic. Defaults to DefaultTimeoutStopSec= from the manager configuration file (see systemd-system.conf(5)).
```

systemd v219 doesn't explicitly state what should happen if you set `TimeoutStopSec=infinity`. The systemd config parser seems to accept `infinity` but in reality it just doesn't work as you see in the logs above.

systemd v229 fixed this by allowing the timeout to be set to `infinity` (or `0` to maintain backwards compatibility) as you can see in the [section of v219 changelog](https://github.com/systemd/systemd/blob/master/NEWS#L4111-L4115) below.

```
        * Most configurable timeouts in systemd now expect an argument of
          "infinity" to turn them off, instead of "0" as before. The semantics
          from now on is that a timeout of "0" means "now", and "infinity"
          means "never". To maintain backwards compatibility, "0" continues to
          turn off previously existing timeout settings.
```

**Comment by lox** [comment]
Darn. Will do! Think we should go for `TimeoutStopSec=` ?

**Comment by tduffield** [comment]
@lox I think we should do a straight revert to begin with to unbreak things. Then we can experiment a bit.

**Comment by lox** [comment]
Done @tduffield
