### ISSUE TITLE
Bash process substitution fails in Windows AMI

### ISSUE THREAD

**Issue by jeremiahsnapp** [buildkite/elastic-ci-stack-for-aws#631]
The new windows AMI was built with a recently released git for windows v2.23.0 which has a bug preventing bash process substitution from working.

https://github.com/git-for-windows/git/issues/2291

This causes the docker-login plugin to fail when it runs `<(env)` here.

https://github.com/buildkite-plugins/docker-login-buildkite-plugin/blob/bed42369829918e369d370cb287a7f91063a4a8e/hooks/pre-command#L10

git for windows has fixed the issue here.

https://github.com/git-for-windows/build-extra/pull/255

But the fix hasn't been released yet. Even once it does get released it might be awhile before it's available in chocolatey.org so the packer template can install it.

One workaround we can do is pin the version in packer by running something like `choco install git --version 2.22.0`.

If that sounds reasonable then I'm happy to make the PR.

**Comment by lox** [comment]
I think pinning the git version is super sensible.
