### ISSUE TITLE
Enable IMSv2

### ISSUE THREAD

**Issue by zsims** [buildkite/elastic-ci-stack-for-aws#647]
We're planning to enforce the instance metadata endpoint v2 (IMSv2): https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-metadata.html#configuring-instance-metadata-options

It would be ideal if the elastic CI stack either had this on by default, or added an option for opting into IMSv2

**Comment by zsims** [comment]
Doesn't look like CloudFormation support for `MetadataOptions` is there yet: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-launchtemplate-launchtemplatedata.html

**Comment by simonfong6** [comment]
Hi, I am also interested in exposing the ability to modify metadata options for IMDSv2 security

**Comment by jamesholmes-linktree** [comment]
This support is now available:
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-launchtemplate-launchtemplatedata-metadataoptions.html#cfn-ec2-launchtemplate-launchtemplatedata-metadataoptions-httptokens

**Comment by yob** [comment]
This sounds like something we should support, however it might have to be considered after the v5.0 release that we're currently stabilizing ahead of a release.

To check my understanding: metadata requests can be made with and without tokens on all instances now and this option would make tokens compulsory? If that's true, before making it configurable I think we'd need to confirm all parts of the stack that make metadata requests use tokens, like:

https://github.com/buildkite/elastic-ci-stack-for-aws/blob/d9b2549ae5f8e98b213351ac1d8e13ee72559f00/packer/linux/conf/buildkite-agent/scripts/terminate-instance#L9-L10.

#696 looks like the other part of it, although it hurts to spend three of our few remaining params. I don't have any good alternative suggestions though :thinking:

**Comment by jamesholmes-linktree** [comment]
> metadata requests can be made with and without tokens on all instances now and this option would make tokens compulsory

Yes, that's right. Those calls, as you showed, would need to use the token method.

**Comment by holmesjr** [comment]
I'm now working on this.

**Comment by holmesjr** [comment]
I’ve checked over the repo and there are a few places that call the metadata service in scripts:
- the install scripts
- the terminate instance scripts
- the docker low disk gc script

The easy way to implement this is to simply get a fresh token each time the metadata service needs to be called - these scripts seems to be one-offs or infrequently used, so that would work. Can folks provide input to make sure I implement this in your preferred way?

**Comment by yob** [comment]
Fetching a token each time seems fine to me, but I'll share this comment with my more experienced AWS colleagues to confirm

**Comment by pda** [comment]
This has landed in https://github.com/buildkite/elastic-ci-stack-for-aws/releases/tag/v5.2.0
