### ISSUE TITLE
Buildkite agent fails with default template options

### ISSUE THREAD

**Issue by janniks** [buildkite/elastic-ci-stack-for-aws#648]
Using the default parameters/template using the `Launch Stack` button, buildkite agent immediately fails with `ROLLBACK`

**Comment by keithduncan** [comment]
Hi @janniks I’ve just checked and you’re right, there’s no indication given that the stack won’t apply. I’m going to try adding some parameter rules in https://github.com/buildkite/elastic-ci-stack-for-aws/pull/873 in addition to the per-parameter validation that is already performed to see whether that helps here.
