### ISSUE TITLE
Cloudwatch logs agent is returning hostname instead of instance id 

### ISSUE THREAD

**Issue by morts1a** [buildkite/elastic-ci-stack-for-aws#649]
Hi,

The latest AMI build for Linux was built with awscli-cwlogs version 1.4.4.  This is causing an issue with 
log naming in cloudwatch, where the hostname is used instead of the Instance ID.

The issue seems to be fixed by updating to version to 1.4.6

see here for more info https://forums.aws.amazon.com/thread.jspa?threadID=312234

**Comment by keithduncan** [comment]
I’ve just confirmed on the most recent version of the Elastic CI Stack AMI and this appears to have been updated some time in the past. Thank you for opening this issue 😁 please let us know if you see any further problems with the CloudWatch agent on your Elastic CI Stack instances 🙇‍♂️
