### ISSUE TITLE
SSM config for agent tokens not in current release

### ISSUE THREAD

**Issue by neilmock** [buildkite/elastic-ci-stack-for-aws#656]
I see this in master as of 3 months ago, but not in the most recent release of 4.3.5 on Nov 4.  Is there a reason it isn't included?  If it is delayed for a reason could we possibly gen the aws-stack.yml from master and expect it to work?

Thanks!

**Comment by keithduncan** [comment]
Hi @neilmock support for this landed in version 5 and is now generally available. Thank you for opening this issue, let us know if you have any questions about SSM support or otherwise! 😁
