### ISSUE TITLE
Access denied for buildkite-agent-metrics in eu-north-1 

### ISSUE THREAD

**Issue by peter-svensson** [buildkite/elastic-ci-stack-for-aws#661]
Seems to be a problem with permission on the S3 bucket for buildkite-agent-metrics in eu-north-1.

`Error: ROLLBACK_COMPLETE: ["The following resource(s) failed to create: [MetricsLambdaExecutionPolicy, MetricsFunction, AgentLifecycleHookRole]. . Rollback requeste
d by user." "Resource creation cancelled" "Resource creation cancelled" "Your access has been denied by S3, please make sure your request credentials have permission to GetObject for buildkite-lambdas-eu-north-1/buildkite-agent-metrics/v4.1.2/handler.zip. S3 Error Code: AccessDenied. S3 Error Message: Access Denied (Service: AWSLambdaInternal; Status Code: 403; Error Code: AccessDeniedException;`

Confirmed with:

` aws s3 cp s3://buildkite-lambdas-eu-north-1/buildkite-agent-metrics/v4.1.2/handler.zip /tmp/a
fatal error: An error occurred (403) when calling the HeadObject operation: Forbidden
`

Works fine for eu-west-1:

`aws s3 cp s3://buildkite-lambdas-eu-west-1/buildkite-agent-metrics/v4.1.2/handler.zip /tmp/a
download: s3://buildkite-lambdas-eu-west-1/buildkite-agent-metrics/v4.1.2/handler.zip to /tmp/a
`

The solution might be as simple as setting correct permissions on the s3 bucket...

**Comment by sj26** [comment]
Hi @peter-svensson,

Apologies, it looks like we added eu-north-1 recently and didn't backfill all of the previous versions. I've just gone ahead and done so, so these objects should now be present and available. https://buildkite-lambdas-eu-north-1.s3.amazonaws.com/buildkite-agent-metrics/v4.1.2/handler.zip is now downloadable for me. Please try it again.

Cheers,
Sam
