### ISSUE TITLE
[Feature request] Scale up N instance when there are N unscheduled job for one minute

### ISSUE THREAD

**Issue by ailisp** [buildkite/elastic-ci-stack-for-aws#673]
Currently N has to be predefined in stack template. This rise to a problem, if N smaller than number of unscheduled jobs, some job will still be unscheduled and based on my experiment need to wait additional 2-3 minute for next scale up to be ready. If N bigger than unscheduled jobs it's kind of waste. Giving system at a time knows how many unscheduled jobs are there before make request to aws, add support to scale exact number of instances as unscheduled jobs will be a nice feature

**Comment by chloeruka** [comment]
Hey @ailisp, yeah, this has been a source of frustration under the old scaling method (Cloudwatch alarm) as it's pretty blunt. You might find the `EnableExperimentalLambdaBasedAutoscaling` feature useful here. If you set it to `true` it'll use a lambda that can more efficiently scale to job demand. There's some more detail about how the lambda itself works in the [buildkite/buildkite-agent-scaler repo](https://github.com/buildkite/buildkite-agent-scaler).

For now this is an experimental feature, but multiple enterprise customers have been using it without many problems for a long time now. We're planning on promoting this experiment to the default behaviour soon!

**Comment by ailisp** [comment]
Great, will give a try!
