### ISSUE TITLE
Downloading secrets from s3 takes ~10s every time

### ISSUE THREAD

**Issue by jessebye** [buildkite/elastic-ci-stack-for-aws#695]
When using Elastic CI stack's s3 secrets, we notice that every step of the build pipeline takes ~10s longer to complete. This wouldn't be bad if it was once in the pipeline, but it happens for every step when reading the secrets from S3.

Is it possible to cache the secrets, or speed up this process somehow? If we have a pipeline of 10 steps, that's 100s of additional wait time, which isn't really acceptable for us.

**Comment by nikwek** [comment]
Thanks for submitting this @jessebye. We've actually been discussing this internally very recently and trying to figure out ways to improve the performance.

**Comment by vgrigoruk** [comment]
we've replaced s3-secrets with https://github.com/mikeknox/aws-paramstore-secrets-buildkite-plugin a while ago and it works much better in terms of performance.

**Comment by jayco** [comment]
@vgrigoruk thanks for sharing the plugin! 👌

 I think a lot of folks will find that extremely useful, I will also share it internally with the team!

**Comment by gencer** [comment]
In EC2 Environment, Now it takes 0 seconds (<1sec) to download secrets from s3. See: https://github.com/buildkite/elastic-ci-stack-s3-secrets-hooks/pull/37

Thank you so much for this!

**Comment by pda** [comment]
https://github.com/buildkite/elastic-ci-stack-for-aws/releases/tag/v5.1.0
