### ISSUE TITLE
Multiple stacks with same queue name

### ISSUE THREAD

**Issue by xiaket** [buildkite/elastic-ci-stack-for-aws#697]
Hi there,

I think we are not properly handling the case where there are multiple CI stacks configured to use the same queue name. I have two stacks running with a same queue name, one ASG with 2 instances running idle, the other ASG with 0 instances. Upon a new build, the expected behaviour is the first ASG will pick up the task while the other will take no action. The observed behaviour is the instances in the first ASG correctly picked up the task, but the other ASG scaled up to provide the capacity which is not needed.

A real world use case for this is an upgrade path for the CI stack. We could setup another stack using the new template while keeping the existing stack running. These two stacks would share the same queue name, and we could manually change the size of the ASG to gradually migrate all the workload from one ASG to the other.

I'm happy to dig into the code and possibly provide a PR for this, but want to hear your opinions first.

**Comment by esalter** [comment]
I think that makes sense.  Thanks!

On first glance the linked issue looks like it would work.  I'll take my comments there.  Thanks for the tip!

**Comment by keithduncan** [comment]
Given that we have merged multiple instance type support, and support draining a stack’s instances by disabling that stack’s scaling lambda, I think all the work needed for this is done 🎉 

I’m going to close this issue but if I’ve missed something in my reading of the comments please let me know and I’ll see what we can do.
