### ISSUE TITLE
ARM support

### ISSUE THREAD

**Issue by nitrocode** [buildkite/elastic-ci-stack-for-aws#703]
Hi. I'm just wondering if bk agents can run on arm instances?

I'd love to run my agents on the new m6g instance types to save money.

Edit: I just noticed this PR https://github.com/buildkite/elastic-ci-stack-for-aws/pull/690. Can this be approved and merged ?

**Comment by sj26** [comment]
Hi @nitrocode! We're hoping to look at it and merge it soon. There are some issues on the branch which need to be resolved, first. Please subscribe to that PR to follow progress. :-)
