### ISSUE TITLE
Upgrade Packer from 1.0.4 (August 2017) to latest version

### ISSUE THREAD

**Issue by nitrocode** [buildkite/elastic-ci-stack-for-aws#704]
Packer is now 1.6.2 (August 2020) and this is currently using 1.0.4 (August 2017). Lots of bugs and additional features have been added since.

https://github.com/hashicorp/packer/blob/master/CHANGELOG.md

**Comment by sj26** [comment]
Packer has been updated to 1.6.2 — thanks :-)
