### ISSUE TITLE
Build is broken. S3 latest cloudformation yml is stuck at v4.3.5 or earlier

### ISSUE THREAD

**Issue by nitrocode** [buildkite/elastic-ci-stack-for-aws#716]
Hi. I was trying to configure multiple security groups today by using a comma separation for SecurityGroupId which is supposed to work and it was failing. I went through my steps.

I've checked the following templates

* https://s3.amazonaws.com/buildkite-aws-stack/latest/aws-stack.yml
* https://s3.amazonaws.com/buildkite-aws-stack/v4.3.5/aws-stack.yml
* https://s3.amazonaws.com/buildkite-aws-stack/v4.4.0/aws-stack.yml
* https://s3.amazonaws.com/buildkite-aws-stack/v4.5.0/aws-stack.yml

The latest aws-stack.yml in `master` branch uses a launch template whereas the one in the above S3 link uses a launch configuration which leads me to believe that the S3 one is old. There must be something wrong in the yml deploy pipeline or perhaps the link is outdated.

Here are all the differences side-by-side

```
diff \
  <(curl -s https://s3.amazonaws.com/buildkite-aws-stack/latest/aws-stack.yml) \
  <(curl -s https://raw.githubusercontent.com/buildkite/elastic-ci-stack-for-aws/master/templates/aws-stack.yml) \
  --side-by-side -W 200 | less
```

I checked the AMIs from the latest stacks and they are all from `2019`...

```
✗ curl -s https://s3.amazonaws.com/buildkite-aws-stack/latest/aws-stack.yml | grep AWSRegion2AMI -A17 -m1
  AWSRegion2AMI:
    us-east-1 : { AMI: ami-00e5ebe843eca1e7f }
    us-east-2 : { AMI: ami-0d259404b19420860 }
    us-west-1 : { AMI: ami-0809dafb1cb2c35df }
    us-west-2 : { AMI: ami-08a0bedbd2f13ac2c }
    ap-south-1 : { AMI: ami-04e65fda2f479f2ff }
    ap-northeast-2 : { AMI: ami-0e7c57e7a04c11b97 }
    ap-southeast-1 : { AMI: ami-0ea4813fc348db8dc }
    ap-southeast-2 : { AMI: ami-037391125aa54e8d9 }
    ap-northeast-1 : { AMI: ami-0ecd3d5b4bdd517b1 }
    ca-central-1 : { AMI: ami-0b49b3042c60ad73a }
    eu-central-1 : { AMI: ami-0a42428db9d639740 }
    eu-west-1 : { AMI: ami-08942cd66f70bec05 }
    eu-west-2 : { AMI: ami-00b39302d59a9e18c }
    eu-west-3 : { AMI: ami-0c53fd2ba1c7a5f13 }
    eu-north-1 : { AMI: ami-002f59c422f68f265 }
    sa-east-1 : { AMI: ami-078e2e733186db619 }
```

```
$ aws ec2 describe-images --owners 172840064832 --image-ids ami-0662826fbca636496 --query 'Images[].CreationDate'
[
    "2019-11-05T00:55:49.000Z"
]
```

When 4.5.0 (July 10) was released, we should be using the AMIs that were created right before.

Using this cli command

```
aws ec2 describe-images --owners 172840064832 --filters "Name=name,Values=buildkite-stack-linux-*" --query 'Images[?CreationDate>=`2020-07-07`][] | sort_by(@, &CreationDate) | [0].[ImageId, CreationDate]' --region us-east-1
```

I created the below map. Most of the AMIs were built on July 8th except for `us-east-1` which was created July 2nd.

```
  AWSRegion2AMI:
    us-east-1 : { linux: ami-0da762b6d9f1023ea }
    us-east-2 : { linux: ami-068cd6306965b17d6 }
    us-west-1 : { linux: ami-0565e004213de4973 }
    us-west-2 : { linux: ami-0a7fad42ba2518459 }
    ap-south-1 : { linux: ami-0c0f522e7c0b3f683 }
    ap-northeast-2 : { linux: ami-0cfdb21a9e405ab71 }
    ap-southeast-1 : { linux: ami-0b13177a9abfe14d5 }
    ap-southeast-2 : { linux: ami-075719c35677e6534 }
    ap-northeast-1 : { linux: ami-0d78c95955efcd10b }
    ca-central-1 : { linux: ami-097cb0df11f1e8904 }
    eu-central-1 : { linux: ami-02bbabfa5866e79a0 }
    eu-west-1 : { linux: ami-02a7c482c4f64b880 }
    eu-west-2 : { linux: ami-03da7a9142c6fbbb8 }
    eu-west-3 : { linux: ami-013c81f0b2d4d303f }
    eu-north-1 : { linux: ami-0c59da4cd7a332b65 }
    sa-east-1 : { linux: ami-052cf6432ab954820 }
```

## Workaround

See gist: https://gist.github.com/nitrocode/5d63df0e00936556fe3d4fd4c6bf9e5b

### Patch

```bash
# Download the latest from the `master` branch
wget https://raw.githubusercontent.com/buildkite/elastic-ci-stack-for-aws/master/templates/aws-stack.yml -O buildkite-stack.yml
# backup original
cp buildkite-stack.yml buildkite-stack.yml.orig
# Download patch from gist
wget https://gist.githubusercontent.com/nitrocode/5d63df0e00936556fe3d4fd4c6bf9e5b/raw/buildkite-stack.yml.ami.patch -O buildkite-stack.yml.ami.patch
# Apply AMI patch
patch -u buildkite-stack.yml -i buildkite-stack.yml.ami.patch
# Compare original to the new one as a sanity check
diff buildkite-stack.yml buildkite-stack.yml.orig
```

### Or download mine

```bash
wget https://gist.githubusercontent.com/nitrocode/5d63df0e00936556fe3d4fd4c6bf9e5b/raw/buildkite-stack.yml -O buildkite-stack.yml
```

### Cloudformation

```bash
# Run cloudformation commands on the new template
aws cloudformation create-stack \
  --output text \
  --stack-name buildkite \
  --template-body file://buildkite-stack.yml \
  --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM \
  --parameters file://config.json
```

Note: Due to the heavy amount of changes, you may notice that
* `ScaleCooldownPeriod` has been removed
* `ScaleDownPeriod` was renamed to `ScaleInIdlePeriod`
* `ScaleDownAdjustment/ScaleUpAdjustment` is superceded by `ScaleOutFactor`.

@yob ping

**Comment by yob** [comment]
Thanks for flagging this.

I believe https://s3.amazonaws.com/buildkite-aws-stack/latest/aws-stack.yml is the latest stable release, currently 4.5.0.

The latest master template is published to https://s3.amazonaws.com/buildkite-aws-stack/master/aws-stack.yml, and you're welcome to use it. We're aiming to release a new stable version in the next few weeks, at which point I believe well update https://s3.amazonaws.com/buildkite-aws-stack/latest/aws-stack.yml.

The us-east-1 AMI for 4.5.0 is ami-00e5ebe843eca1e7f, generated on 2020-07-02. The us-east-2 AMI for 4.5.0 is ami-0d259404b19420860, generated in 2020-07-10. These dates seem to line up with the [release date of 4.5.0](https://github.com/buildkite/elastic-ci-stack-for-aws/releases/tag/v4.5.0) to me.

I believe there's nothing for us to fix here, other than the fact that master has moved on a lot since our last stable release and that's not ideal. Hopefully we'll have the resolved soon :pray:

**Comment by yob** [comment]
oh - I should've also mentioned that the recent 4.x releases have been coming off the [v4-development](https://github.com/buildkite/elastic-ci-stack-for-aws/tree/v4-development) branch.

**Comment by nitrocode** [comment]
Thanks for the quick response. Interesting. I figured since master was updated, those changes would be merged to child branches like v4-development. I just have a few questions regarding the next release.

* When is the next release?
* Will it use the aws-stack.yml from master?
* We're currently using the master branch version of aws-stack. How do you know when the cloudformation stack is stable enough to cut a new release?
* Same for the AMIs. There are a lot of buildkite-stack-linux-* amis. How do these AMIs get deemed to be stable?

Thanks!

**Comment by yob** [comment]
> When is the next release?

Soon! Weeks, not months.

> Will it use the aws-stack.yml from master?

Yup.

> We're currently using the master branch version of aws-stack. How do you know when the cloudformation stack is stable enough to cut a new release?

Ideally we'd keep most development on master, keep master relatively stable, and do small releases regularly. We hope to return to that pattern after the upcoming release.

> Same for the AMIs. There are a lot of buildkite-stack-linux-* amis. How do these AMIs get deemed to be stable?

The AMIs included in a formally versioned cloud formation release are considered stable. Other AMIs generated between releases only evolve slowly and should be fairly stable, but they may contain occasional surprises as we work on feature development.
