### ISSUE TITLE
[request] Please install Slack app on repo so we can follow releases from Slack

### ISSUE THREAD

**Issue by nitrocode** [buildkite/elastic-ci-stack-for-aws#722]
Hi. We'd like to subscribe to buildkite releases using the github/slack integration.

Usually we do the following when subscribing to new repos.

```
# if this works
/github subscribe buildkite/elastic-ci-stack-for-aws releases
# if the above doesn't work, then subscribe to all and unsubscribe from stuff we don't want
/github subscribe buildkite/elastic-ci-stack-for-aws
/github unsubscribe buildkite/elastic-ci-stack-for-aws commits,issues,deployments,statuses,pulls,public
```

However, it says that the Slack app is not installed on this repo and we cannot install it. A workaround is to subscribe to the release feed using the atom feed.

```
/feed subscribe https://github.com/buildkite/elastic-ci-stack-for-aws/releases.atom
```

Thank you

**Comment by sj26** [comment]
Hi @nitrocode! We're not familiar with this slack extension or app, could you link us to some documentation?

**Comment by nitrocode** [comment]
Hi @sj26. When I run the `/github subscribe` above, it says

> Either the app isn't installed on your repository or the repository does not exist. Install it to proceed.
Note: You need to be an organization owner to install the app (or ask one to install it for you).

Since this app is installed on our Github and works for other repos, I believe this app would need to be installed on the github org (or just this repo) for others to subscribe to from Slack.

https://slack.github.com/

**Comment by sj26** [comment]
Hmm, the slack integration wants access to write to our issues, pull requests and deployments. I don't think I can grant this, sorry.

Perhaps you can use that public feed instead?
