### ISSUE TITLE
Instead of terminating instances after ScaleInIdlePeriod, option to shutdown

### ISSUE THREAD

**Issue by nitrocode** [buildkite/elastic-ci-stack-for-aws#731]
Noticed that it takes about 3.5 minutes to scale out a new instance. It seems to be a lot faster to shutdown and start the same instance when a new job requires that queue instead of scaling out a new instance.

Thoughts?

**Comment by ecv** [comment]
You gotta try the Experimental Lambda Scaler. My instances are booted now in ~45sec, and are done installing their bootstraps & coming online after another 45sec of stuff that I make them do. Enormous improvement over the AWS EC2 Autoscaler behavior.

Compelling suggestion regardless, honestly, mind kind of blown; but the win wouldn't be three full minutes.

**Comment by yob** [comment]
Does AWS still charge for instances that are shutdown? If so, maybe it's worth adjusting the idle timeout on the stack to keep the instances running for longer and ready to accept jobs?

**Comment by jamesholmes-linktree** [comment]
No, the only cost will be for EBS volumes used by the shut-down instances.

**Comment by lox** [comment]
> Compelling suggestion regardless, honestly, mind kind of blown; but the win wouldn't be three full minutes.

I couldn't believe it when I first implemented it either @ecv!

**Comment by nitrocode** [comment]
@ecv this is enabled by default in the current master branch, right?

**Comment by nitrocode** [comment]
I suppose if it only takes 45 seconds to create a new instance with the experimental lambda, which may be default in master branch / upcoming 5.x release, then we probably don't need to shut off an instance and turn it back on.

I've been using the master branch cf stack and i have noticed a decrease. Usually it's 3.5 minutes and now i see it using half the time. Around 1.5 min which is a huge improvement.

**Comment by yob** [comment]
> No, the only cost will be for EBS volumes used by the shut-down instances.

Neat, that's not as bad as I feared then.

> this is enabled by default in the current master branch, right?

Correct. In fact, it's the only option - the old scaling system has been removed on the master branch.

Even faster scale ups would be nice I don't think we're outright opposed to the idea of shutting instances down, but it has a few challenges to think through. Primarily, the lambda scaler currently works by just bumping the ASG desired size and I assume this would require the scaler to first look for existing instances it can boot?

For now I think we're focused on releasing v5, but we can leave this issue open to let the idea percolate for a bit :heart:

**Comment by keithduncan** [comment]
@nitrocode I’ve been going through old issues and my impression here is this might be superseded by [warm pools](https://github.com/buildkite/elastic-ci-stack-for-aws/issues/822) if we can get that to work in a way that doesn’t risk starting Buildkite Jobs before instance stop, what do you think?

**Comment by nitrocode** [comment]
Yes I agree with you. The warm pool feature seem like the best method to implement something like this.

**Comment by keithduncan** [comment]
Great! I’ll keep thinking about how best to add that feature 😄
