### ISSUE TITLE
Spot termination leaves hanging agents if "stop-agent-gracefully" blocks for more than the allotted 2 minutes

### ISSUE THREAD

**Issue by bshelton229** [buildkite/elastic-ci-stack-for-aws#733]
When an agent is interrupted due to spot termination, if it is processing a job that doesn't finish 2 minutes after the spot termination signal is received, the ec2 instance ends up terminated in ec2 without properly deregistering the agent in the buildkite control plane. This results in the agent looking like it's still processing the job for some time (minutes?) before the connection is determined to be lost, marking the agent as gone in buildkite. I believe this to be an issue with the instance being hard terminated by ec2 while the `stop-agent-gracefully` script called by `lifecycled` is still waiting for buildkite-agent to gracefully stop.

My understanding of how spot termination is handled in what's currently in master is:

1. Lifecycled is booted up and will handle the spot termination signal from the local ec2 metadata url.
2. This triggers `stop-agent-gracefully` when the spot termination signal is received.
3. `stop-agent-gracefully` calls `systemd stop buildkite-agent` which should send SIGTERM to the agent process and block for the agent to gracefully clear all in flight jobs.
4. The `ExecStopPost` systemd command will then trigger the agent to terminate by calling `terminate-instance`, which works by calling `aws autoscaling terminate-instance-in-auto-scaling-group` with the correct derived values.

Where I believe this breaks down is if spot steps in and hard terminates while `systemctl stop "buildkite-agent"` is still blocking for graceful shutdown, resulting in a hung agent in the UI until Lost Connection is detected some minutes after the instance is gone in ec2.

## Possible Solution

`systemctl stop buildkite-agent` appears to block waiting for the process to die gracefully, so I wasn't sure what the loop waiting for pids was doing in the `stop-agent-gracefully` script, but I think a possible solution is to detect from lifecycled that this termination was due to spot and after 1.5 minutes hard-terminate the agent pids. Maybe we could do the initial SIGTERM backgrounded and loop for less than 2 minutes and if the pid still isn't gone hit it with SIGTERM again. It looks like if the agent receives subsequent SIGTERM it will hard stop? - https://github.com/buildkite/agent/blob/097d299649771ad7da5cdb445090331a249c924d/clicommand/agent_start.go#L774

I haven't looked enough into lifecycled to know if it passes some env vars telling the script which termination method it's responding to. I think we'd want to block for as long as we have to when not being terminated due to spot, which has that 2 minute window.

## Replicating the Issue

I was able to verify this using this method of replicating spot termination - https://ec2spotworkshops.com/running_spark_apps_with_emr_on_spot_instances/tracking_spot_interruptions.html#verifying-that-the-notification-works

The following steps worked to replicate this:

1. Manually spin up a spot fleet of 1 using the launch template my ASG was using. I'm using an agent on a dedicated queue for this testing.
2. Schedule a job/step running a 20 minute sleep using that queue. Wait for the agent to pick it up
3. `sudo journalctl -f -t lifecycled` to tail the logs for lifecycled and decrement the spot fleet to 0, triggering the spot termination process
4. Lifecycle should start the graceful shutdown, but after 2 minutes the instance will start terminating before graceful shutdown is complete.

This should result in the agent still looking active in the buildkite UI for quite some time though the underlying ec2 instance is fully terminated.

**Comment by yob** [comment]
This is a very timely report, we've just been wondering about how graceful
the spot termination behaviour is.

You mention master - have all your experiments been on the master branch?
Have you tried on 4.x by any chance? We're wondering if the behaviour is a
regression.

One idea we've discussed is adding a new signal to the agent. Maybe USR1,
that starts a graceful termination with a timer, then hard stops the job
after a minute or so and leaves the main agent process time to properly
deregister from our API. A quick solution in bash might be worthwhile in
the short term though 🤔

**Comment by bshelton229** [comment]
@yob I think the USR1 approach sounds really nice. Maybe have a configurable timeout that would default to spot termination friendly. Maybe 90 seconds, which assumes the signal gets caught within 30 second. In general I've found spot termination to be about as graceful as an elephant trying to ride a skateboard :).

Updating the agent sounds like a bit more work. Would you mind a PR trying to make it work in the bash script in the interim while I have this test environment booted up? I'm thinking we could read `$1` to detect `ec2:SPOT_INSTANCE_TERMINATION` and start with a `systemctl kill --kill-who=main --signal=SIGTERM buildkite-agent`, loop for ~90 seconds checking for agent pids every second, and if there are still pids after 90 seconds, send `systemctl kill --kill-who=main --signal=SIGQUIT buildkite-agent`. `systemctl kill ...` is non-blocking like `kill ...` so it should allow looping and checking pids after the call. The termination script will probably need to be updated to send `USR1` anyway as you probably only want to go that route in the spot termination case, not necessarily the ASG terminate case.

**Comment by chloeruka** [comment]
Hey @bshelton229 yes please – we're in the process of prepping a release, so if you don't get a chance we'll try to work it in ourselves. Thanks for your detailed steps for reproducing the issue – using a spot fleet is a great idea.

**Comment by bshelton229** [comment]
@chloeruka and @yob I think #737 takes care of this. I didn't have enough time to test what older stacks do, but I see in our code we're handling the `-1` exit code a lot, so I don't think we were ever losing agents gracefully; but I can't be totally sure. I believe with this script modification the happy path shutdowns should work well, both `disconnect-after-idle-timeout` and spot termination.

I've also observed that the unhandled straight ec2 terminate doesn't gracefully kill the agent via the systemd shutdown process. I'm not sure if that's already known or not. It's a little surprising to me, but amazon linux has a notoriously old systemd. It's also been a while since I've tried to make that work. We 100% rely on catching and handling ec2 events to gracefully clean things up from spot and ASG these days, and assume termination is less than graceful, so I've lost a little bit of my systemd graceful stop procedure knowledge :).

## Unsolicited Opinions

I think relying on systemd to trigger `/usr/local/bin/terminate-instance` in `ExecStopPost` is fairly surprising behavior and likely to run into edge cases. I don't know if I have a great alternative, but maybe the agent itself could add a configuration option to exec a script when it decides to stop itself due to `disconnect-after-idle-timeout`. Then, maybe lifecycled could listen on an HTTP port for custom events (or maybe watch for a file or something?). That would allow you to wire up the agent calling a script that would send a custom handleable event to lifecycled in the `disconnect-after-idle-timeout` case. I think it would also be nice to put back the SQS ASG lifecycle hook for lifecycled to consume. This would centralize all graceful shutdown logic to the lifecycled handler script, including shutting down in the ASG when appropriate.

For example, manual scale-in of the ASG is presently unsafe without a termination lifecycle hook, as systemd shutdown isn't gracefully stopping the agent in my testing. The only way to safely terminate an agent without waiting for `Lost Connection` in the control plane is to make sure to `systemctl stop buildkite-agent` yourself, as terminate for whatever reason isn't blocking long enough during systemd shutdown.

**Comment by yob** [comment]
Unsolicited opinions are always welcome @bshelton229!

> maybe the agent itself could add a configuration option to exec a script when it decides to stop itself due to `disconnect-after-idle-timeout`

We've definitely had discussions about whether the agent is a good place to solve some of this problem. We probably don't want AWS-specific termination code, but a way to execute a script during shutdown might be interesting.

It's a particularly interesting option when you consider that the upcoming v5.0 release includes experimental windows support and we definitely can't rely on systemd there.

> I think it would also be nice to put back the SQS ASG lifecycle hook for lifecycled to consume

Interesting. This isn't strictly necessary for gracefully handling spot termination, but it might be useful for other terminations that can still happen (like AZ rebalancing).

For now the bash+systemd hybrid approach you've proposed in #737 is a pragmatic option for v5.0, and we'll let the other ideas marinate before making a call for future releases.

**Comment by lox** [comment]
https://github.com/buildkite/agent/pull/1275 would be a neat candidate for this!

**Comment by yob** [comment]
I'm going to close this as resolved in #737.

Grace termination of spot instances remains an open issue on Windows, but we'll track that separately. Thanks again for the timely contribution @bshelton229.
