### ISSUE TITLE
Add support for mix instances policy

### ISSUE THREAD

**Issue by monemihir** [buildkite/elastic-ci-stack-for-aws#745]
It would be great is you could add support for mix instances when selecting instance type rather than locking it to a single instance type.

I see that with v5.0.0 (which is currently in beta) that you have switched to LaunchTemplate so may be this could be implemented as well?

**Comment by yob** [comment]
Thanks @monemihir. We're definitely interested in this and #710 is our current plan to address it, probably after we release the current master branch as v5.0.0.

Out of interest, we'd love to hear a bit about your use case for mixed instance ASG if you can share.

**Comment by monemihir** [comment]
We have seen it a couple of times now that the desired instance is not available and the ASG just keeps failing with an error of not being able to fill capacity.

In most of our stacks we use mix instances with 4 types of instances which then pretty much guarantees availability.

**Comment by yob** [comment]
Thanks for that. Keep an eye on #710 - hopefully we'll get it merged soon.

**Comment by yob** [comment]
#710 was merged and include in v5.1.0
