### ISSUE TITLE
Add custom tags to AWS resources

### ISSUE THREAD

**Issue by jchanam** [buildkite/elastic-ci-stack-for-aws#750]
Hi!

This is an improvement idea I'd like to share. I'd find it very interesting to be able to add custom tags (other than the cost allocation one) to the AWS resources created.

This is needed to manage the infrastructure due to security reasons. Do you think it's feasible? If you guide me where to start I'll be happy to send you a PR with my proposal.

Thanks!

**Comment by lox** [comment]
I believe you can specify custom tags at a cloudformation level to be applied stack wide!

**Comment by pda** [comment]
> All stack-level tags, including automatically created tags, are propagated to resources that AWS CloudFormation supports. Currently, tags are not propagated to Amazon EBS volumes that are created from block device mappings.
— https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-resource-tags.html

**Comment by jchanam** [comment]
Thanks for answering,

I'd specifically like to add custom tags to the infrastructure (that then will eventually be propagated as you've mentioned).

@lox How can I do so? I've only seen that I can edit the cost allocation one, but I want to add custom ones too.

Thank you!

**Comment by pda** [comment]
If you're launching via the AWS web console, then you add tags during the [Setting AWS CloudFormation stack options](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-console-add-tags.html) phase of [Creating a stack](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-console-create-stack.html), or you can update an existing stack to add/change any tags you want.

If you're using the `aws` CLI, it's the `--tags` option [described here](https://docs.aws.amazon.com/cli/latest/reference/cloudformation/create-stack.html).

**Comment by jchanam** [comment]
Thank you for your help! That works flawlessly.
