### ISSUE TITLE
ASG removed and recreated when updating the launch template parameters

### ISSUE THREAD

**Issue by nitrocode** [buildkite/elastic-ci-stack-for-aws#764]
I'm a bit of a cloud formation noob but i have noticed that the iam role persists between stack updates. If i change values that have to do with the launch template, it destroys my launch template, my instances, and my asg. I noticed that the resources affected are usually the ones suffixed with the cf stack id. My iam role does not have this suffix.

In terraform, it would simply update the launch template version and assign the version to the existing asg. The instances could then be refreshed to get the latest changes from the template. If it works in terraform then this should be available in cf.

Edit: in the cloudformation stack

* The [`LaunchTemplateName`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-launchtemplate.html) is unset so it must be auto generating that
* The [`AutoScalingGroupName`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-as-group.html) is also unset

If the above two parameters are hard coded like the iam role name, is there another parameter to set the asg or LT to use the latest version of the LT or is that the default in cloud formation? 

Providing these values will allow us to update our stacks without having to check if our asg has a desired count greater than zero. If we update while the count is greater than zero then current builds are interrupted.

**Comment by holmesjr** [comment]
The launch template is part of the main stack yaml: https://github.com/buildkite/elastic-ci-stack-for-aws/blob/master/templates/aws-stack.yml#L814

The ASG itself is probably not being replaced, but CF will absolutely replace all the instances in the ASG because the template tell it to: https://github.com/buildkite/elastic-ci-stack-for-aws/blob/master/templates/aws-stack.yml#L971

**Comment by nitrocode** [comment]
If I change the security group, it will replace the asg and the launch template instead of reusing it.

Is there a relevant reason why those lines exist? Or can they be omitted so we can update the asg and lt instead of recreating?

**Comment by lox** [comment]
> I noticed that the resources affected are usually the ones suffixed with the cf stack id. My iam role does not have this suffix.

This is because we specify a name for the IAM role to allow it to be externally referenced: 

https://github.com/buildkite/elastic-ci-stack-for-aws/blob/857e3f72aa0e002d9dcd113b4871f93327bc822a/templates/aws-stack.yml#L637

> If I change the security group, it will replace the asg and the launch template instead of reusing it.

You can look in the Cloudformation docs for how updates are processed for resources:

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-launchtemplate-launchtemplatedata.html

It doesn't look to me like updating your security group will replace the LaunchTemplate, it should update in place. Are you certain that is happening? Can you show us an update plan?

**Comment by nitrocode** [comment]
Interesting. I haven't re-tested the security group but here's another example I saw today.

If I try to update the instance type, it will keep my iam roles, and it ends up creating a new ASG suffixed with the cloudformation ID, updating the AsgProcessSuspenderRole (cause of an inline policy that explicitly allowlists the ASG) and deleting the old ASG and its current instances that are running.

This seems like it could be avoided by setting the `LaunchTemplateName` and `AutoScalingGroupName` attributes.

Is there any reason to not set these?

**Comment by holmesjr** [comment]
For the ASG name, yes:
> This name must be unique per Region per account

Getting that right with a pre-determined name isn't easy. Regardless, CF doesn't just replace an ASG because it feels like it. It replaces it because it needs to.

As for the Launch template, as it's specified in the same template, the Ref pointing to the ID is the correct way to reference this.

Can you show the CF update events that show that the resources are being replaced?

**Comment by chloeruka** [comment]
It looks like this decision was made in #272 and according to the [UpdatePolicy docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-updatepolicy.html) the following conditions will cause a replacement of the ASG:

> For AWS::AutoScaling::AutoScalingGroup resources, AWS CloudFormation invokes one of three update policies depending on the type of change you make or whether a scheduled action is associated with the Auto Scaling group.
> The AutoScalingReplacingUpdate and AutoScalingRollingUpdate policies apply only when you do one or more of the following:
> - Change the Auto Scaling group's AWS::AutoScaling::LaunchConfiguration.
> - Change the Auto Scaling group's VPCZoneIdentifier property
> - **Change the Auto Scaling group's LaunchTemplate property**
> - Update an Auto Scaling group that contains instances that don't match the current LaunchConfiguration.
> - If both the AutoScalingReplacingUpdate and AutoScalingRollingUpdate policies are specified, setting the WillReplace property to true gives AutoScalingReplacingUpdate precedence.

Inside our LaunchTemplate, the security group is referenced like so:
https://github.com/buildkite/elastic-ci-stack-for-aws/blob/374bcc53a89b8c6c97404657f12af01caea4a886/templates/aws-stack.yml#L818-L821
LaunchTemplates are versioned, so changes to security groups should cascade to a new version of the LaunchTemplate and consequently an ASG replacement.

@lox any idea why we did this in #272? Is it worth considering changing it back to reduce ASG churn like this?

**Comment by jamesholmes-linktree** [comment]
Sorry I missed that detail. Yes, this is a full replacement. I've has a number of bad rolling updates before this where the launch config was messed up but the stack rollback wasn't possible - replacing the whole ASG with a blue/green approach is better for stability.

>WillReplace
Specifies whether an Auto Scaling group and the instances it contains are replaced during an update. During replacement, AWS CloudFormation retains the old group until it finishes creating the new one. If the update fails, AWS CloudFormation can roll back to the old Auto Scaling group and delete the new Auto Scaling group.

**Comment by nitrocode** [comment]
I see so it does do the replacement. Thank you for confirming.


Then would it be possible to have an additional input variable to prevent the replacement of the ASG?

**Comment by lox** [comment]
@chloeruka I recall there being times when upgrades would hang due to graceful termination of old instances. The blue/green approach avoids that, but with the cost of rolling the new ASG.

I'm not sure I quite understand why it's a problem @nitrocode, could I trouble you to explain? The current design should be gracefully terminating instances and not interrupting builds, are you not seeing that?

**Comment by nitrocode** [comment]
@holmesjr 

We could set the name to include the region so that it would still be unique per region per account.

**Comment by nitrocode** [comment]
@jamesholmes-linktree 

> I've had a number of bad rolling updates before this where the launch config was messed up but the stack rollback wasn't possible

I've updated a lot of stacks and I don't believe I've seen this issue before. Could you dive further into detail on this?

**Comment by yob** [comment]
> Existing jobs that are currently running will terminate as the asg needs to be recreated so every running ec2 instance will be terminated. This is annoying as we now have to check if there are any jobs running prior to updating which is difficult to enforce.

Does thus termination disruptive (does it kill running jobs), or does it wait for the jobs to finish before the instance shuts down?

One of the changes between v4.5.0 and v5.0.0 is we stopped using life cycle hooks (see #575). Maybe we still need them to keep stack upgrades minimally disruptive?

**Comment by nitrocode** [comment]
@yob yes the recreation can be disruptive however the easiest problem to solve would be to create the asg when the stack is created and prevent the asg from having to be recreated. I can't think of a reason why the asg should be destroyed unless the stack is destroyed.

**Comment by nitrocode** [comment]
Perhaps the easiest way to solve this is to override the `WillReplace` attribute with an input parameter.

What are your thoughts on this?

**Comment by nitrocode** [comment]
Hi all. I noticed that the enhancement label is on this issue. Any comments on the pr I'm proposing? I think a cloudformation param that will overwrite the `WillReplace` attribute is a best of both worlds solution.

We're thinking of cutting our own stack in the mean time but would prefer if this change made it in officially so we can get future updates without having to sync the changes.

**Comment by chloeruka** [comment]
Sorry about the delay @nitrocode — we're a small team so it can take some time for us to get around to items of this nature. Totally understand this would be a useful thing to have, but we're also generally pretty cautious with increasing our parameter count or introducing toggles that might have unexpected consequences, so I want to make sure it gets attention from all the right (very busy) people 😄

**Comment by nitrocode** [comment]
No problem, I believe the parameter count no longer has the previous limit. The new limit of parameters per stack is 200 as of recent if that helps loosen the restrictions 😁

**Comment by yob** [comment]
It's true that the parameter count restriction has been increased, but we still want to consider the benefit/cost of new parameters carefully. The Elastic Stack is in a tricky place trying to support a wide range of users - some who are reasonably new to AWS and only want/need to modify 2 parameters to get going (Agent token, MaxSize, maybe InstanceType), and more experienced AWS users who legitimately want to make significant customisations to the stack behaviour.

At the extreme end, a stack with 200 knobs and dials would be very daunting to the new user who only needs 2.

**Comment by nitrocode** [comment]
That also presumes that all additional parameters _need_  to be set. I'd agree with this sentiment more if there wasn't an ability to set a default. Rightly so, most of the parameters in the stack have a default that the user will not need to override with the exception of the `BuildkiteQueue`.

I'd argue that adding additional parameters for further customization is a good thing provided the default of those parameters do not need to be changed and, of course, the current number of parameters are far from the limit.
