### ISSUE TITLE
Bug: Have to add DOCKER_CLI_EXPERIMENTAL to get docker manifests pushed

### ISSUE THREAD

**Issue by nitrocode** [buildkite/elastic-ci-stack-for-aws#798]
## Problem

The `--platform` option works

```
...
docker build -t snip.dkr.ecr.us-west-2.amazonaws.com/snip --build-arg BASEIMAGE=arm64v8/ubuntu --platform linux/arm64 -f Dockerfile.staging ../
Sending build context to Docker daemon  134.2MB Docker daemon  557.1kB
[2021-02-11T16:31:47Z] Step 1/26 : ARG BASEIMAGE
...
```

The `manifest create` did not

```
...
[2021-02-11T16:49:23Z] docker manifest create snip.dkr.ecr.us-west-2.amazonaws.com/snip --amend snip.dkr.ecr.us-west-2.amazonaws.com/snip --amend snip.dkr.ecr.us-west-2.amazonaws.com/snip
[2021-02-11T16:49:23Z] docker manifest create is only supported on a Docker cli with experimental cli features enabled
...
```

## Workaround

Adding the `DOCKER_CLI_EXPERIMENTAL=enabled` to the pipeline steps seems to work.

```
      env:
          DOCKER_CLI_EXPERIMENTAL: enabled
```

We have `EnableDockerExperimental=true` set in the cloudformation stack but this does not add the above variable. It adds `DOCKER_EXPERIMENTAL` instead.

https://github.com/buildkite/elastic-ci-stack-for-aws/blob/b84d760a66f544c5f582702ba207d280fbac20a1/templates/aws-stack.yml#L934-L938

## Proposed solution

Should both `DOCKER_CLI_EXPERIMENTAL` and `DOCKER_EXPERIMENTAL` be added if `EnableDockerExperimental=true` ? 

or would it be better to add the following to `/etc/docker/daemon.json`

```json
{
  "experimental": true
}
```

**Comment by mogggggg** [comment]
I agree, having the `EnableDockerExperimental ` parameter set the experimental mode on both the daemon and the CLI would be useful for us too.

**Comment by yob** [comment]
> Or would it be better to add the following to /etc/docker/daemon.json

To enable experimental cli behaviour, does that need to go into `/etc/docker/daemon.json` or `~/.docker/config.json`?
