### ISSUE TITLE
Multi-arch support

### ISSUE THREAD

**Issue by sj26** [buildkite/elastic-ci-stack-for-aws#799]
ARM support is becoming available almost everywhere, but the almost is taking a while. It's possible to make adoption easier by adding transparent multi-arch support, so that running foreign binaries on linux works transparently. There's a great guide for how to do this with qemu, and it seems to be what tools like Docker for Mac are doing under the hood:

https://www.stereolabs.com/docs/docker/building-arm-container-on-x86/

These steps require a reboot, which makes them impractical to run in a bootstrap script. Should we ship qemu and binfmt support within the elastic stack? This would be great for the arm64 images at least, where this problem is most painful.

The instructions are, roughly:

```
yum install qemu-user qemu-*-static qemu-kvm-tools qemu-kvm virt-install libvirt libvirt-python libguestfs-tools-c qemu-system-aarch64 glib2-devel pixman-devel -y
wget https://raw.githubusercontent.com/qemu/qemu/master/scripts/qemu-binfmt-conf.sh
wget https://raw.githubusercontent.com/multiarch/qemu-user-static/master/containers/latest/register.sh
chmod +x qemu-binfmt-conf.sh register.sh
sed -i "s/ \\/qemu-binfmt-conf\\.sh/ .\\/qemu-binfmt-conf.sh/" register.sh
```

There's some supporting documentation here:

https://github.com/multiarch/qemu-user-static

**Comment by nitrocode** [comment]
Is this setup easier than using buildx https://github.com/buildkite/elastic-ci-stack-for-aws/issues/765 ?

**Comment by yob** [comment]
@nitrocode I'm not our expert here, but is it possible `buildx` is for build docker images that target different architectures, and the support @sj26 mentions here is for running containers on different architectures?

**Comment by edify42** [comment]
@yob if you can build them it makes sense that you should be able to run them so I think #765 (which I'm in favour of :heart: ) covers arm64 and a few other CPU architectures.
