### ISSUE TITLE
Pre-installing common aws python packages like boto3

### ISSUE THREAD

**Issue by nitrocode** [buildkite/elastic-ci-stack-for-aws#820]
A number of our devs have requested the package `boto3` to be preinstalled.

I'm usually in favor of running everything inside of a docker container instead of relying on preinstalled utils. However, similar to https://github.com/buildkite/elastic-ci-stack-for-aws/issues/817, would you folks be open to preinstalling some aws specific python packages like `boto3` ?

**Comment by sj26** [comment]
Hi @nitrocode!

In this case I think we're already installing the aws cli tools, which contain boto3. If you need that dependency in a python form as well, perhaps you can install it in a bootstrap script?

https://github.com/buildkite/elastic-ci-stack-for-aws#customizing-instances-with-a-bootstrap-script

**Comment by nitrocode** [comment]
Yes, that is what we're currently doing.

**Comment by sj26** [comment]
Great! That sounds like the right solution. :-)

If you wanted to go deeper and bake more dependencies in up front then you could fork our AMI and add tooling you need, but that seems pretty heavy for a python library.

I'll close this if you've already got a solution working.
