### ISSUE TITLE
Support Enhanced Networking

### ISSUE THREAD

**Issue by denyska** [buildkite/elastic-ci-stack-for-aws#821]
Enhanced Networking supports higher transfer rates between EC2 and S3.

https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/enhanced-networking.html

**Comment by keithduncan** [comment]
Hi @denyska, I just tried ssh-ing into an Elastic CI Stack `t3.large` instance and checked the ethtool output:

```
[ec2-user@ip-10-0-1-7 ~]$ ethtool -i eth0
driver: ena
version: 2.4.0g
firmware-version: 
expansion-rom-version: 
bus-info: 0000:00:05.0
supports-statistics: yes
supports-test: no
supports-eeprom-access: no
supports-register-dump: no
supports-priv-flags: no
```

Looks like this is using the ENA driver already. Let us know if there is there a situation where the ENA driver isn’t used and I can look into getting that fixed for you. Thanks!
