### ISSUE TITLE
Cross region S3 secrets bucket unreachable after upgrading to 5.1.0

### ISSUE THREAD

**Issue by samjmarshall** [buildkite/elastic-ci-stack-for-aws#828]
We use a "global" secrets bucket for the vast majority of our agent queues, deployed to different AWS regions.

After upgrading to 5.1.0, agents that do not live in the same region as the S3 secrets bucket can no longer reach it.

```
-- | --
  | Downloading secrets from  buildkite-123456789123 | 0s
-- | --
  | ⚠️ Bucket "buildkite-123456789123" not found: BadRequest: Bad Request | 0s
  | status code: 400, request id: 7.........V, host id: 3........=
  | fatal error: S3 bucket "buildkite-123456789123" not found
```

**Comment by sj26** [comment]
Hm, that's an odd one. Which version did you upgrade from? Perhaps there was a change to aws region handling which is causing issues?

**Comment by sj26** [comment]
I wonder if that error message is accurate, too. If it were a wrong bucket issue, I'd expect a status code of "404" not "400".

**Comment by pda** [comment]
Some pointers into the code:

https://github.com/buildkite/elastic-ci-stack-s3-secrets-hooks/blob/67c4e227b5e591608794776d6330c7fe4ea2273a/s3secrets-helper/secrets/secrets.go#L64-L71

```go
	if ok, err := conf.Client.BucketExists(bucket); !ok {
		if err != nil {
			log.Printf("+++ :warning: Bucket %q not found: %v", bucket, err)
		} else {
			log.Printf("+++ :warning: Bucket %q doesn't exist", bucket)
		}
		return fmt.Errorf("S3 bucket %q not found", bucket)
	}
```

So `BucketExists` was `false` _and_ returned an error (status code: 400).
Here's `BucketExists`:

https://github.com/buildkite/elastic-ci-stack-s3-secrets-hooks/blob/67c4e227b5e591608794776d6330c7fe4ea2273a/s3secrets-helper/s3/s3.go#L58-L77

```go
// BucketExists returns whether the bucket exists.
// 200 OK returns true without error.
// 404 Not Found and 403 Forbidden return false without error.
// Other errors result in false with an error.
func (c *Client) BucketExists(bucket string) (bool, error) {
	if _, err := c.s3.HeadBucket(&s3.HeadBucketInput{Bucket: &bucket}); err != nil {
		if aerr, ok := err.(awserr.Error); ok {
			switch aerr.Code() {
			// https://github.com/aws/aws-sdk-go/issues/2593#issuecomment-491436818
			case "NoSuchBucket", "NotFound":
				return false, nil
			default: // e.g. NoCredentialProviders, Forbidden
				return false, aerr
			}
		} else {
			return false, err
		}
	}
	return true, nil
}
```

That confirms it's not a simple `NoSuchBucket` nor `Forbidden`, but it's hitting the `default: // e.g. NoCredentialProviders, Forbidden` case.

I wonder if there's something different about how credentials are being sourced by the newer Go-based hook.

**Comment by pda** [comment]
For comparison, here's the old bash code:

```bash
s3_exists() {
   local bucket="$1"
   local key="$2"
   local aws_s3_args=("--region=$AWS_DEFAULT_REGION")

   # capture just stderr
   output=$(aws s3api head-object "${aws_s3_args[@]}" --bucket "$bucket" --key "$key" 2>&1 >/dev/null)
   exitcode=$?

   # If we didn't get a Not Found or Forbidden then show the error and return exit code 2
   if [[ $exitcode -ne 0 && ! $output =~ (Not Found|Forbidden)$ ]] ; then
     echo "$output" >&2
     return 2
   elif [[ $exitcode -ne 0 ]] ; then
     return 1
   fi
 }
```

Note that it _does_ explicitly specify `--region=$AWS_DEFAULT_REGION` for the `aws s3api head-object` command. Whereas in Go `c.s3.HeadBucket(&s3.HeadBucketInput{Bucket: &bucket})` does not specify region in the call (but may have region configured in the `c.s3` client…?

**Comment by pda** [comment]
Oh wait, sorry, I'm mixing up `HeadObject` and `HeadBucket`.
The old `HeadBucket` is just `aws s3api head-bucket --bucket "$bucket"` 🤷‍♂️
Maybe it's a problem, though, that our Go S3 client _is_ explicitly passed the region info:

```go
	sess, err := session.NewSession(&aws.Config{
		Region: &region, // $AWS_DEFAULT_REGION
	})
```

I wouldn't have thought that would be a problem, though.

**Comment by sj26** [comment]
I wonder as well if it's a signature issue? Would the cli tools and the golang library have differing support for instance meta-data service versions, instance credentials, and signature versions?

**Comment by nitrocode** [comment]
I hit the same issue on `v5.3.1`

```
Downloading secrets from :amazon-s3: buildkite-snip-managedsecretsbucket
Bucket "buildkite-snip-managedsecretsbucket" not found: BucketRegionError: incorrect region, the bucket is not in 'eu-west-1' region at endpoint ''
```

Our s3 bucket is in `us-west-2`. Not sure if this same output is thrown by the same code blocks mentioned above.
