### ISSUE TITLE
Updating stack parameters doesn't trigger a rolling update

### ISSUE THREAD

**Issue by toolmantim** [buildkite/elastic-ci-stack-for-aws#84]
If you update the buildkite agent queue name, API key, agents per instance or release stream (from stable to beta) you need to manually set the ASG desired size to 0 and force a scale down for it to apply changes, because it's all done in cloud-init. And some people might try just deleting the stack and recreating.

It'd be preferable if you could just update the stack parameters and it's handled for you. This could mean performing a rolling update somehow?

**Comment by lox** [comment]
Hmm, I thought the addition of an UpdatePolicy on the `AgentAutoScaleGroup` (https://github.com/buildkite/elastic-ci-stack-for-aws/blob/master/templates/buildkite-elastic.yml#L493) was supposed to do exactly this.

**Comment by lox** [comment]
Oh I remember now. It will do a rolling update if the `LaunchConfiguration` changes, BUT this doesn't include changes to the `Metadata` stanza. The intention is that this would be handled by the user with something like [cfn-hup](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-hup.html)

**Comment by lox** [comment]
The catch with `cfn-hup` is that there is no co-ordination of how that is run and you could potentially mark all active instances as unhealthy at once. The other catch is that it's based on polling, with a min interval of 5 minutes.

**Comment by exidy** [comment]
Rolling updates are triggered if the UserData changes, so you can try echoing the stack parameters you want to cause a rolling update into your UserData script, as a comment.

**Comment by lox** [comment]
Hah, I came here to say roughly the same @exidy. Wonder if there are any downsides to that approach.

**Comment by exidy** [comment]
Well the downside is that it'll replace the whole instance rather than simply restarting the agent, which will take a little longer and cost a little more. In my mind this isn't a biggie as I would think the buildkite agent queue name, API key, agents per instance or release stream parameters to be relatively stable, perhaps after a little experimentation.

**Comment by toolmantim** [comment]
I'd be fine with replacing the instances via this method.

There's another problem with rolling updates almost always failing, I figured the rolling update policy needs looking at / fixing, but that's another issue. Let's fix this one

**Comment by lox** [comment]
Any idea what the cause of the failing update is?
