### ISSUE TITLE
SSM agent token has to be recreated in every region

### ISSUE THREAD

**Issue by nitrocode** [buildkite/elastic-ci-stack-for-aws#842]
It would be nice to be able to set the ssm token once in a single region and allow buildkite queues cross region to access it.

I think if we can had a parameter that would allow specifying the region of the ssm token, it would be enough to prevent having to recreate the same ssm param in every region.

**Comment by chloeruka** [comment]
Hmm, I like the idea in theory. From what I understand, regions are "meant" to have their own (in many cases, duplicated) parameters, so this might be leaning slightly toward anti-pattern territory as it makes a service in one region (EC2) dependent on a service in another (SSM ParamStore). FWIW, it's relatively easy to copy them, and there are some good tools for copying between regions to alleviate the annoyance of maintaining multiple parameters, e.g. [aws-ssm-copy](https://github.com/binxio/aws-ssm-copy) that could automate the process.

However, I don't necessarily see that as a barrier to us including this. So I'm left with my usual apprehension to adding extra parameters for niche circumstances. The next question is how many people would use it? Some votes (👍🏻) would help!

**Comment by nitrocode** [comment]
If I want to roll the credential, I'd have to update every ssm parameter in every region...

It would be nice to have the option to be explicit about the region. If the explicit region isn't set, the stack can do what it does today which assumes the ssm param is in the region that the cf stack is in. I'd prefer to have the option to be explicit over implicit in this case.

**Comment by keithduncan** [comment]
This is possible today combining [multi-region Secrets Manager secrets](https://docs.aws.amazon.com/secretsmanager/latest/userguide/create-manage-multi-region-secrets.html) with [referencing AWS Secrets Manager secrets from Parameter Store parameters](https://docs.aws.amazon.com/systems-manager/latest/userguide/integration-ps-secretsmanager.html).

I tested creating a multi-region secret and made the following notes when getting an elastic ci stack template to use it:

- Create a secret for the agent token in AWS Secrets Manager, configure the secret to be replicated to multiple regions.
- Configure your elastic ci stack to use an agent token parameter path of `/aws/reference/secretsmanager/$YOUR_SECRET_ID`
- Ensure the agent IAM role has `ssm:GetParameter` permission in the region it will be retrieving the secret from
    - By default the template will grant in-region permission permission only, limiting this role’s utility to the stack’s region only. This isn’t a problem just a caveat to be aware of, don’t expect to assume role and fetch the parameter in multiple regions. We can consider changing the template to use a wildcard region so the same role can be used in multiple regions e.g. `arn:aws:ssm:*:[redacted]:parameter/aws/reference/secretsmanager/$YOUR_SECRET`
- Ensure the agent IAM role has `kms:Decrypt` permission to the key used to encrypt the secret in secrets manager
    - I used the AWS SecretsManager key e.g. aws/secretsmanager in Secrets Manager and then looked up the underlying CMK ID of that key alias in each region I deployed the stack template to, using that value for the `BuildkiteAgentTokenParameterStoreKMSKey` parameter
        - Updating the template to add support for the `arn:aws:kms:[region]:[account]:alias/aws/secretsmanager` ARN format in the template would be helpful here.
- Apply a resource policy to the Secrets Manager secret that grants read access to the secret for each agent IAM role:

```
{
  "Version" : "2012-10-17",
  "Statement" : [ {
    "Effect" : "Allow",
    "Principal" : {
      "AWS" : [
            "arn:aws:iam::[redacted]:role/buildkite-secretsmanager-test2-Role”,
            "arn:aws:iam::[redacted]:role/buildkite-secretsmanager-test3-Role”
          ]
    },
    "Action" : "secretsmanager:GetSecretValue",
    "Resource" : "*"
  } ]
}
```

And that’s it! Now agent token changes in the secret will be replicated from the primary region to each secondary region, and each region now has a readable SSM Parameter for the stack to consume.

**Comment by keithduncan** [comment]
These [docs](https://github.com/buildkite/docs/pull/1088) have landed in the docs site now 🥳
