### ISSUE TITLE
If MinSize > 0, after ScaleInTimeout, agent restarts but remains unresponsive to jobs

### ISSUE THREAD

**Issue by scottjg** [buildkite/elastic-ci-stack-for-aws#850]
Not sure if this is an agent bug or a cf stack bug.

I have an CI pipeline that builds a big docker container and then runs tests in it. Since our build times depend pretty heavily on a warm cache, for now, i set `MinSize` and `MaxSize` to 2. The intention is that we keep these machines alive so their docker caches remain warm. When setting it up, it worked fine, but I came back an hour later and noticed that builds were stuck in the queue. 

In cloudwatch for the agent instances, I can see: 
`May 31 22:29:15 ip-10-0-2-191 buildkite-agent: 2021-05-31 22:29:15 INFO   buildkite-i-0102dd74635cb07ed-1 All agents have been idle for 600 seconds. Disconnecting...`

the agent starts again and after 600 seconds, it dies again. Probably should be harmless. You'd think it would start accepting jobs after it restarts but, unfortunately, it appears after the first time it dies, it now longer accepts jobs. 

I set `ScaleInTimeout` to 0 and that seems to have fixed it, but it seems like the config is maybe broken when `MinSize` > 0. I'm not sure the purpose of the agent being responsible for its own idle out. If the autoscaler shuts down a machine, wouldn't there be time for the agent to report the shutdown before the init system completes the process? I guess it could avoid a race where a job is queued as its shutting down?

**Comment by yob** [comment]
With a fixed size ASG the agent disconnecting and reconnecting is a known issue since the 5.0 release, however our understanding is that the agents reconnect reliably and continue accepting up work.

Out of interest, what stack version are you running?

**Comment by scottjg** [comment]
Buildkite stack v5.3.1

**Comment by scottjg** [comment]
of course its possible there's something else wrong, but both of my build instances had less than 1% cpu usage and the agent logs kept showing the cycling restarts, so i don't think they were totally hung or anything like that.

**Comment by yob** [comment]
Interesting. If you can see the agent logs consistently showing the restarts, I feel fairly confident that the agent process *should* be running and able to accept jobs. It would be *very* unusual for an agent to be connected and running, but unable to accept jobs.

It might be worth emailing support@buildkite.com with a link to this issue, and some links to some impacted builds and agents so we can dig into it a bit further.

**Comment by yob** [comment]
Thanks again for this report @scottjg. We haven't heard from you with extra details so I might close this report, but we're happy to re-open if this continues to be an issue :heart: 

The agent restarts are expected when MinSize>0 (unfortunately), but we're super keen to help debug any sign of the restarted agents not picking up new work.

> I'm not sure the purpose of the agent being responsible for its own idle out. If the autoscaler shuts down a machine, wouldn't there be time for the agent to report the shutdown before the init system completes the process? I guess it could avoid a race where a job is queued as its shutting down?

You're on the money there. The agent being responsible for terminating itself between jobs means we don't need any complex infrastructure  (EC2 lifecycle hooks, signals with timeouts, etc ) to prevent the ASG scale-in process terminating a random instance with a job in progress.
