### ISSUE TITLE
The tag key aws:createdBy is not valid in cost allocation tags

### ISSUE THREAD

**Issue by ysawa0** [buildkite/elastic-ci-stack-for-aws#856]
Tried to deploy v.5.3.2 with Cost allocation tags on and got this CF error
cost allocation tag settings default except
```
  {
    "ParameterKey": "EnableCostAllocationTags",
    "ParameterValue": "true"
  },
```
```
The tag key ?aws:createdBy? is not valid. Tag keys starting with 'aws:' are reserved for internal use. (Service: AmazonEC2; Status Code: 400; Error Code: InvalidTagKey.Malformed; Request ID: 8686fdf5-82c0-4b0e-96ab-c7b44ad3f2db; Proxy: null)
```
![image](https://user-images.githubusercontent.com/8774197/122108713-60c03400-cdd1-11eb-8f68-5308395dfcfa.png)

**Comment by keithduncan** [comment]
Hi @ysawa0 I’ve just tested this and you’re right, when turning on `EnableCostAllocationTags` the default value `CostAllocationTagName` parameter results in an error. A workaround for this is to provide your own tag name to the `CostAllocationTagName` parameter.

Thanks for letting us know, we’ll change the default value of this parameter to a supported value in a future release. 😄
