### ISSUE TITLE
IMDSv2Tokens="required" doesn't work with docker containers

### ISSUE THREAD

**Issue by atyndall** [buildkite/elastic-ci-stack-for-aws#857]
Hi there, I set `IMDSv2Tokens` to `required` in the latest version of the stack, as we're using all the latest versions of the AWS SDK in our builds so I didn't expect any problems, but I noticed that steps we run inside docker containers that are attempting to access the CI instance's credentials now fail.

I'm pretty sure I've encountered this problem before with other tooling, and it's because the docker networking means the default hop limit of `1` won't work, as going through the docker networking stack adds an additional hop. (https://github.com/fog/fog-aws/issues/560)

As mentioned in https://github.com/buildkite/elastic-ci-stack-for-aws/pull/789, the ability to configure the hop limit is probably required after all, as using docker containers that access AWS instance credentials I think is a not-uncommon use-case.

If you're indeed planning to make it the default in 6.0, you'll probably need to change the default hop limit to something higher, or issue some clear guidance for people who run docker containers in this way.

**Comment by keithduncan** [comment]
Hi @atyndall thanks for letting us know about this, we’ve bumped the default limit from 1 to 2 in the template which I’d expect to fix this and will be released in a future update to the published elastic ci stack. Thanks again!
