### ISSUE TITLE
Buildkite agent 3.30.0

### ISSUE THREAD

**Issue by esalter** [buildkite/elastic-ci-stack-for-aws#862]
Hi!  Is there any particular reason that we can't update the stack to use agent version 3.30.0 (latest as of this writing)?  It has metrics support in it which we're hoping to take advantage of.  I'm happy to make a PR if it helps.

Thanks!

**Comment by yob** [comment]
Thanks @esalter. We're hoping to do an elastic stack release in the next week or two, and plan to include a bump to the agent version.

A PR that bumps it to 3.30.0 for linux+windows would be welcome :heart:

**Comment by esalter** [comment]
Thanks @yob , i created a PR!
