### ISSUE TITLE
Cannot create stack in ap-southeast-1

### ISSUE THREAD

**Issue by keithduncan** [buildkite/elastic-ci-stack-for-aws#864]
Haven’t investigated any further but got this deploying the stack to Singapore just now.

![Screenshot 2021-06-24 at 17 55 55](https://user-images.githubusercontent.com/22101/123224879-8ce85d00-d515-11eb-9831-614c98961584.png)

**Comment by yob** [comment]
Were you using a CF template from a released version, or from a branch?

By default the template on has  AMIs for us-east-1. The release process for an final version copies the us-east-1 AMIs to each region and adds them into the CF template.

**Comment by keithduncan** [comment]
> Were you using a CF template from a released version, or from a branch?

🤦‍♂️ I was testing the cost tags one so it was a branch you’re right 😅
