### ISSUE TITLE
Document 5.6.X CloudFormation required capability

### ISSUE THREAD

**Issue by calvinbui** [buildkite/elastic-ci-stack-for-aws#904]
I upgraded from 5.5.1 to 5.6.1 and noticed the `CAPABILITY_AUTO_EXPAND` capability is now required.

This might have to be documented somewhere.

AWS docs: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-iam-template.html#using-iam-capabilities

via console: 

![image](https://user-images.githubusercontent.com/3604363/132147180-058e1209-636a-48a0-b11f-3aaf7b9c7a42.png)

via terraform (assuming it uses the API):

```
Error: error updating CloudFormation stack (arn:aws:cloudformation:us-east-2:xxxxxxxxxxx:stack/buildkite-elastic-ci/xxxxxxxx): InsufficientCapabilitiesException: Requires capabilities : [CAPABILITY_AUTO_EXPAND]

status code: 400, request id: xxxxxxxxx
```

**Comment by keithduncan** [comment]
Hi @calvinbui :wave: sorry you ran into this, this was added in https://github.com/buildkite/elastic-ci-stack-for-aws/pull/685.

Where would be most useful to mention this? I have added a bullet point to the 5.6.0 release notes. Thankfully that error is fairly informative 😄

**Comment by calvinbui** [comment]
lgtm
