### ISSUE TITLE
AWS Cloudformation linux userdata breaks when unquoted variables are passed strings with spaces in them

### ISSUE THREAD

**Issue by twunderlich-grapl** [buildkite/elastic-ci-stack-for-aws#914]
In elastic-ci-stack-for-aws/templates/aws-stack.yml, the bash userdata section (currently lines 960-990) has inconsistent quoting around the variables. Variables not enclosed by quotes are subject to  word splitting and globbing. So when a string with a space is added such as to BuildkiteAdditionalSudoPermissions, the servers booted up will have breakage.
 See https://github.com/koalaman/shellcheck/wiki/SC2046 for more details on the error type

To reproduce:
Set BuildkiteAdditionalSudoPermissions="/usr/bin/killall test".

**Comment by keithduncan** [comment]
Fixed by #916
