### ISSUE TITLE
IMDSv2 = "required" breaks the cultureamp/aws-assume-role plugin.

### ISSUE THREAD

**Issue by jim-barber-he** [buildkite/elastic-ci-stack-for-aws#919]
The `cultureamp/aws-assume-role` plugin breaks when deploying the Buildkite agents via version `v5.6.1` of the `elastic-ci-stack-for-aws` CloudFormation stack and setting: `IMDSv2Tokens = "required"`
It works fine if I used `optional` instead.

I wasn't sure where to raise this case... here or at https://github.com/buildkite/feedback/issues
But I chose here since this is what I used to deploy my agents with, and where I enforced IMDSv2.

I looked at the code in the https://github.com/cultureamp/aws-assume-role-buildkite-plugin repository and all it does to assume a role is the following, so I don't think the blame lies with it:
```
aws sts assume-role \
    --role-arn "$role" \
    --role-session-name "aws-assume-role-buildkite-plugin-${build}" \
    --duration-seconds "$duration" \
    --query Credentials
```

The plugin errors with `Invalid endpoint: https://sts..amazonaws.com` (note the two dots).
It either needs to use `https://sts.amazonaws.com` or `https://sts.<<AWS REGION>>.amazonaws.com` (in our case `https://sts.ap-southeast-2.amazonaws.com`)
We don't have `AWS_REGION` for `AWS_DEFAULT_REGION` set in our pipelines, and possibly this could fix it, but we've never had to set those before.

I'm wondering if the AWS CLI installed on the Buildkite agent image is too old or something?
When I ssh to the agent host and run `aws --version` it returns:
```
aws-cli/1.19.112 Python/2.7.18 Linux/4.14.243-185.433.amzn2.x86_64 botocore/1.20.112
```

**Comment by keithduncan** [comment]
Hi @jim-barber-he :wave:

I’m afraid I can’t reproduce this with v5.6.1 deployed to `ap-southeast-2` and `IMDSv2Tokens: required` 🤔 

What version of the stack are you running? Can you think of any other configuration you have that might influence the reproduction?

**Comment by jim-barber-he** [comment]
Hi @keithduncan 

I'm running version `5.6.1` of the stack as found here: https://s3.amazonaws.com/buildkite-aws-stack/v5.6.1/aws-stack.yml

I was in the process of filling in all sorts of details for this response, but I'm pretty sure going through that process has revealed the issue to me.
I downloaded the top level `environment` file from the Buildkite secrets S3 bucket and it contains the following line:
```
export AWS_DEFAULT_REGION="$(wget -qO- 169.254.169.254/latest/dynamic/instance-identity/document | jq -r '.region')"
```
That command is not going to work when IMDSv2 is enabled, so `AWS_DEFAULT_REGION` will have ended up as an empty string, and that would explain the broken behaviour we are seeing.

I'll go through all the environment files on the secrets bucket, fix them up, and then update or close this case accordingly.

**Comment by keithduncan** [comment]
That certainly looks like it could cause this issue 😅 

That line in your secrets `environment` hook may be redundant as the stack’s [UserData script saves](https://github.com/buildkite/elastic-ci-stack-for-aws/blob/5c64f61111d2502e58a96ccfe68535f0927a00fc/packer/linux/conf/bin/bk-install-elastic-stack.sh#L90-L91) the value provided at [launch time](https://github.com/buildkite/elastic-ci-stack-for-aws/blob/5c64f61111d2502e58a96ccfe68535f0927a00fc/templates/aws-stack.yml#L998) into a file that is [picked up](https://github.com/buildkite/elastic-ci-stack-for-aws/blob/5c64f61111d2502e58a96ccfe68535f0927a00fc/packer/linux/conf/buildkite-agent/hooks/environment#L6) by the `environment` Job Lifecycle Hook.

If you do need it (with the IDMS Token added) there is a new IDMS Region API as of [August last year](https://forums.aws.amazon.com/thread.jspa?threadID=77228) that might be of interest to you. I recently [adopted](https://github.com/buildkite/elastic-ci-stack-for-aws/commit/7377eba87467e7b71008e1ab8956464a2abbfa04#diff-462bc21ec5d7034cb15332f0f3d0e7324c54a56ef8001a14371a0f12eecc0ddc) it throughout the stack in a pass to fix some niggling multi-region issues.

**Comment by jim-barber-he** [comment]
Ah I saw your update too late to see that this var was redundant.
I put this into our file and made sure there was nothing else playing with the metadata in any of the other environment files.
```
export AWS_DEFAULT_REGION="$(
        curl \
                -H "X-aws-ec2-metadata-token: $(
                        curl -H "X-aws-ec2-metadata-token-ttl-seconds: 60" -X PUT -sS http://169.254.169.254/latest/api/token
                )" \
                -sS http://169.254.169.254/latest/meta-data/placement/region
        )"
```
Then I redeployed the agents with IMDSv2 required and everything worked properly.

Thanks for looking into this for me.
I'll close this now.
