### ISSUE TITLE
Stepped scaling support

### ISSUE THREAD

**Issue by toolmantim** [buildkite/elastic-ci-stack-for-aws#93]
For our application our main app requires 27 agents, but other pipelines only require 1 or 2. The only way we can make the stack responsive at the start of the day is to make the scaling policy +27 -27 scale out/in, but it's a waste of $ to do that for just a couple of scheduled jobs.

It'd be much better if we could use stepped scaling, and have it scale in/out in smaller increments

**Comment by toolmantim** [comment]
How could we make generic stack parameters to configure this though?

**Comment by npaufler** [comment]
We scale based on the number of IdleAgents and ScheduledJobsCount in the Buildkite Cloudwatch metrics.

We configure step scaling and ScaleIn/ScaleOut by between 1 and 15 based on those values. Specifically, if ScheduledJobsCount > 1 for 60 seconds, spin up 1-15 instances based on the size of that queue. Likewise, if IdleAgents > 0 for 30 mins (6x 300 second intervals) start scaling in, again 1-15 at a time.

i.e.

`"BuildkiteScalingScaleInPolicy": {
      "Type": "AWS::AutoScaling::ScalingPolicy",
      "Properties": {
        "AdjustmentType": "ChangeInCapacity",
        "AutoScalingGroupName": {
          "Ref": "BuildkiteASG"
        },
        "PolicyType": "StepScaling",
        "MetricAggregationType": "Average",
        "EstimatedInstanceWarmup": "300",
        "StepAdjustments": [
          {
            "ScalingAdjustment": -1,
            "MetricIntervalLowerBound": 0,
            "MetricIntervalUpperBound": 1
          },
          {
            "ScalingAdjustment": -2,
            "MetricIntervalLowerBound": 1,
            "MetricIntervalUpperBound": 2
          },
          {
            "ScalingAdjustment": -3,
            "MetricIntervalLowerBound": 2,
            "MetricIntervalUpperBound": 3
          },
          {
            "ScalingAdjustment": -4,
            "MetricIntervalLowerBound": 3,
            "MetricIntervalUpperBound": 4
          },
          {
            "ScalingAdjustment": -5,
            "MetricIntervalLowerBound": 4,
            "MetricIntervalUpperBound": 5
          },
          {
            "ScalingAdjustment": -6,
            "MetricIntervalLowerBound": 5,
            "MetricIntervalUpperBound": 6
          },
          {
            "ScalingAdjustment": -7,
            "MetricIntervalLowerBound": 6,
            "MetricIntervalUpperBound": 7
          },
          {
            "ScalingAdjustment": -8,
            "MetricIntervalLowerBound": 7,
            "MetricIntervalUpperBound": 8
          },
          {
            "ScalingAdjustment": -9,
            "MetricIntervalLowerBound": 8,
            "MetricIntervalUpperBound": 9
          },
          {
            "ScalingAdjustment": -10,
            "MetricIntervalLowerBound": 9,
            "MetricIntervalUpperBound": 10
          },
          {
            "ScalingAdjustment": -11,
            "MetricIntervalLowerBound": 10,
            "MetricIntervalUpperBound": 11
          },
          {
            "ScalingAdjustment": -12,
            "MetricIntervalLowerBound": 11,
            "MetricIntervalUpperBound": 12
          },
          {
            "ScalingAdjustment": -13,
            "MetricIntervalLowerBound": 12,
            "MetricIntervalUpperBound": 13
          },
          {
            "ScalingAdjustment": -14,
            "MetricIntervalLowerBound": 13,
            "MetricIntervalUpperBound": 14
          },
          {
            "ScalingAdjustment": -15,
            "MetricIntervalLowerBound": 14
          }
        ]
      }
    },
    "BuildkiteScalingScaleOutPolicy": {
      "Type": "AWS::AutoScaling::ScalingPolicy",
      "Properties": {
        "AdjustmentType": "ChangeInCapacity",
        "AutoScalingGroupName": {
          "Ref": "BuildkiteASG"
        },
        "PolicyType": "StepScaling",
        "MetricAggregationType": "Average",
        "EstimatedInstanceWarmup": "60",
        "StepAdjustments": [
          {
            "ScalingAdjustment": 1,
            "MetricIntervalLowerBound": 1,
            "MetricIntervalUpperBound": 2
          },
          {
            "ScalingAdjustment": 2,
            "MetricIntervalLowerBound": 2,
            "MetricIntervalUpperBound": 3
          },
          {
            "ScalingAdjustment": 3,
            "MetricIntervalLowerBound": 3,
            "MetricIntervalUpperBound": 4
          },
          {
            "ScalingAdjustment": 4,
            "MetricIntervalLowerBound": 4,
            "MetricIntervalUpperBound": 5
          },
          {
            "ScalingAdjustment": 5,
            "MetricIntervalLowerBound": 5,
            "MetricIntervalUpperBound": 6
          },
          {
            "ScalingAdjustment": 6,
            "MetricIntervalLowerBound": 6,
            "MetricIntervalUpperBound": 7
          },
          {
            "ScalingAdjustment": 7,
            "MetricIntervalLowerBound": 7,
            "MetricIntervalUpperBound": 8
          },
          {
            "ScalingAdjustment": 8,
            "MetricIntervalLowerBound": 8,
            "MetricIntervalUpperBound": 9
          },
          {
            "ScalingAdjustment": 9,
            "MetricIntervalLowerBound": 9,
            "MetricIntervalUpperBound": 10
          },
          {
            "ScalingAdjustment": 10,
            "MetricIntervalLowerBound": 10,
            "MetricIntervalUpperBound": 11
          },
          {
            "ScalingAdjustment": 11,
            "MetricIntervalLowerBound": 11,
            "MetricIntervalUpperBound": 12
          },
          {
            "ScalingAdjustment": 12,
            "MetricIntervalLowerBound": 12,
            "MetricIntervalUpperBound": 13
          },
          {
            "ScalingAdjustment": 13,
            "MetricIntervalLowerBound": 13,
            "MetricIntervalUpperBound": 14
          },
          {
            "ScalingAdjustment": 14,
            "MetricIntervalLowerBound": 14,
            "MetricIntervalUpperBound": 15
          },
          {
            "ScalingAdjustment": 15,
            "MetricIntervalLowerBound": 15
          }
        ]
      }
    }
`

I'm not sure if you could make the stack completely generic, but maybe you could have some presets and use Fn::If to select between different scaling policies. i.e. have defaults to step scale by 1, 5, 10, or 20, and select them based on an Fn::If evaluated paramter?

**Comment by lox** [comment]
Has something changed such that the scale up is slower? When I last looked it was scaling up to max agents in something close to 5 minutes.

**Comment by lox** [comment]
Alternately, we could have a scheduled "start of day" scale up event.

**Comment by toolmantim** [comment]
I dunno how it'd even be possible to get to max agents in 5 minutes?

Say you want 50 agents max, with +10 -10 scale in/out.

It'd start with an alarm, then a scale in event, then a cool down, then another scale in event, and then a cool down… etc… 5 times. Say the cool down is 2 minutes to let the metrics catch up to the agents that have gone and accepted the work… that's 8 minutes just of cool down there.

Unless I'm going cray?

Stepped scaling means we could have rules for 1 -> 100, and almost in one hit add the number of instances we need depending on the scheduled job count.

**Comment by tigris** [comment]
We recently shifted to use the same logic that @npaufler mentioned above.

The tricky part is getting your InstanceWarmup value correct. If it's not accurate, you will scale your threshold amount more than once.

Which may be how some people get to their max agents in 5 minutes, if you are using SimpleScaling and you don't set your Cooldown value appropriately.
