### ISSUE TITLE
Abrupt agent termination during build

### ISSUE THREAD

**Issue by tinder-jlee** [buildkite/elastic-ci-stack-for-aws#971]
**Describe the bug**
Occasionally an agent is abruptly terminated during the build.
For example: https://buildkite.com/tinder/tinderandroid/builds/7354#76971f65-c17b-40a8-aaa6-8bbf4d4b7e61

**Steps To Reproduce**
N/A

**Expected behavior**
Shouldn't terminate.

**Actual behaviour**
Agent is terminated during the build run with the following message.
```
Exited with status 255 (after intercepting the agent's termination signal, sent because the agent was stopped)
```
In the AWS console, ASG :
```
At 2021-12-02T20:04:43Z instance i-00e36c1ca7637e75c was taken out of service in response to a user request, shrinking the capacity from 49 to 48.
```

**Stack parameters (please complete the following information):**
 - AWS Region: us-east-1
 - Version v5.7.2 (and we also noticed the same problem occurred in v5.6.1)

**Additional context**
We use 100% spot instances. We checked the price history of the spot instance compared to the on-demand just in case the spot price goes above the on-demand price, but during the time, it didn't happen.
Also, the abruptly terminated instance was not the fresh new one. One of them that we checked last time was 2-hour-old one.

**Comment by keithduncan** [comment]
@tinder-jlee thank you for reporting this issue. Is it possible the disk on these instance is filling up and they are being killed due to failing the [hourly instance help check](https://github.com/buildkite/elastic-ci-stack-for-aws/blob/master/packer/linux/conf/docker/cron.hourly/docker-low-disk-gc)?

**Comment by tinder-jlee** [comment]
@keithduncan it doesn't seem like it's the cause since the disk usage of the node remains about 20% ...
![image](https://user-images.githubusercontent.com/25184686/145142111-c5d679dd-8830-45f2-8ad6-ea3baff82de7.png)

also, the AWS CLI command for adjusting ASG is just to change its health status rather than explicitly shrink the desired size -- which results in the ASG log given above:
At 2021-12-02T20:04:43Z instance i-00e36c1ca7637e75c was taken out of service in response to a user request, shrinking the capacity from 49 to 48.

**Comment by keithduncan** [comment]
🤔 is there anything in the `/buildkite/lifecycled` CloudWatch Log Group for this instance that might indicate a spot interruption?

**Comment by tinder-jlee** [comment]
![image](https://user-images.githubusercontent.com/25184686/145504878-bbce3747-2d99-42ed-8b98-81257be74daf.png)
Looking at the metric history of the termination, it seems it's happening only during a certain time frame, i.e., 12:00.
We've just changed 100% to on-demand for all ASGs for linux agents. Let's see how it turns out.

**Comment by tinder-jlee** [comment]
after monitoring the metrics, we don't see any of this any more. 
it seems changing to 100% on-demand instances has resolved this issue. i'll close this out.
