### ISSUE TITLE
Bump buildx to latest version 0.7.1 

### ISSUE THREAD

**Issue by eddeee888** [buildkite/elastic-ci-stack-for-aws#978]
**Is your feature request related to a problem? Please describe.**

Currently, the `buildx` version is pinned at 0.5.1 [here](https://github.com/buildkite/elastic-ci-stack-for-aws/blob/71e847885bf4ee14cf8a7817acd675b44249f5d1/packer/linux/scripts/install-docker.sh#L7). This version is missing some features such as [buildx bake](https://docs.docker.com/engine/reference/commandline/buildx_bake/) is unable to parse docker compose files v2+. 

Here's an example of v0.5.1 ( `99dev.yml` is a `docker-compose` file ):
<img width="1493" alt="Screen Shot 2022-01-07 at 1 54 41 pm" src="https://user-images.githubusercontent.com/33769523/148484015-89be9e37-426c-4c3f-873d-d0d0a160bbf0.png">

Here's an example of v0.7.1 ( docker can parse `99dev.yml` which is a `docker-compose` file )
<img width="1497" alt="Screen Shot 2022-01-07 at 1 57 59 pm" src="https://user-images.githubusercontent.com/33769523/148484632-15acd978-4d04-4125-9c02-d82681fca1cd.png">

**Describe the solution you'd like**

Please bump `buildx` version to 0.7.1. I'm happy to help with some directions.

**Describe alternatives you've considered**

Alternatively, we could install the version downstream but it would be good to have it in the base template :)

**Comment by moskyb** [comment]
hi there @eddeee888! it looks like this was done in https://github.com/buildkite/elastic-ci-stack-for-aws/pull/975, and will be released in the next elastic stack version, which will be very soon! i'll close this issue when we do that :)

**Comment by moskyb** [comment]
hi @eddeee888! this was shipped as part of [v5.8.0](https://github.com/buildkite/elastic-ci-stack-for-aws/releases/tag/v5.8.0), so i'm going to close out this issue for now.
