### ISSUE TITLE
FR: Update to Amazon Linux 2022

### ISSUE THREAD

**Issue by dhalperi** [buildkite/elastic-ci-stack-for-aws#998]
**Is your feature request related to a problem? Please describe.**
Amazon Linux 2 is pretty old; defaults to Python 2.7, etc

**Describe the solution you'd like**
Upgrade to a newer Amazon Linux base. (Draft in preview ; support when it's ready?)

**Describe alternatives you've considered**

**Additional context**

**Comment by edify42** [comment]
It's now amazonlinux2023 and it's in general availability: https://aws.amazon.com/blogs/aws/amazon-linux-2023-a-cloud-optimized-linux-distribution-with-long-term-support/
